feat: implemented openRouter-pkce
tarasglek/chatcraft.org pull request #173
Opened 2023-07-20 09:04 UTC by Chigala

## Pull Request: OpenRouter Integration

### Description

This pull request implements the integration of OpenRouter into the application. The main feature added is a new button that allows users to select the OpenRouter provider and get their API key from openRouter. 

### Changes Made

1. Added a new button to the user interface, allowing users to choose the OpenRouter provider.
2. Implemented the button click event to redirect users to OpenRouter's authorization page.
3. Added logic to retrieve the API key from OpenRouter after the user grants access.
4. Injected the obtained API key into an input field, enabling users to seamlessly use OpenRouter's services.

### How It Works

1. When a user selects the "OpenRouter" provider, the "OpenRouter" button becomes visible.
2. Upon clicking the button, users are redirected to OpenRouter's authorization page.
3. Once the user grants access, the application automatically retrieves the API key from OpenRouter.
4. The obtained API key is then injected into an input field on the user interface.
5. This implementation eliminates the need for users to manually copy and paste the API key.

### Additional Notes

- Error handling has been thoroughly addressed to ensure a smooth user experience.
- The implementation adheres to best practices and security measures while interacting with OpenRouter's service.

### Testing

Extensive testing has been performed to verify the functionality of the OpenRouter integration. Test cases include:
- Button visibility and functionality
- Successful redirection to OpenRouter's authorization page
- Retrieval and injection of the API key into the input field

### Screenshots

![image](https://github.com/tarasglek/chatcraft.org/assets/92148630/e2b1621e-ed50-494c-9e80-b86412c7c8cc)

Please review the changes and provide any feedback or suggestions for improvements. Thank you!

Chigala

2023-07-20 09:32 UTC, tarasglek commented on src/lib/ai.ts
> +    callbackUrl = "http://localhost:5173";
this is wrong, use window.location instead of hardcoding callback url

2023-07-20 09:33 UTC, tarasglek commented on src/router.tsx
> +          return redirect(`/c/${recentChat.id}?code=${openRouterCode}`);
what's the purpose of this code?

2023-07-20 09:35 UTC, tarasglek commented
Please add equivalent functionality to Settings dialog

2023-07-20 09:37 UTC, Chigala commented on src/lib/ai.ts
> +    callbackUrl = "http://localhost:5173";
Ohh,Thanks. I didn't think of that. I'll implement this

2023-07-20 09:45 UTC, Chigala commented
Ohk, I'll check that out

2023-07-20 13:07 UTC, tarasglek commented
@humphd can you comment on these changes? Is this ok to land

2023-07-20 13:28 UTC, Chigala commented on src/hooks/use-codeExchange.ts
> +import { useState, useEffect } from "react";
I'll integrate the logic into the use-settings hooks instead. Then strip the url of the code. Thanks

2023-07-20 13:29 UTC, Chigala commented on src/router.tsx
> +          return redirect(`/c/${recentChat.id}?code=${openRouterCode}`);
Noted. Thanks

2023-07-20 17:25 UTC, humphd requested changes

2023-07-20 17:25 UTC, humphd commented on src/components/Message/AppMessage/Instructions.tsx
> +                Get key from OpenRouter{" "}
s/key/API Key/

2023-07-20 17:25 UTC, humphd commented on src/components/PreferencesModal.tsx
> +                  Get key from OpenRouter{" "}
Same there, s/key/API Key/

2023-07-20 17:25 UTC, humphd commented on src/hooks/use-settings.tsx
> +  //get code from the url
Let's be more clear.  This `code` is for OpenRouter.ai, so let's name it that, and indicate this in the comment.  Also, let's cache the URL params object, so we can work with it later. 

```js
// Get the OpenRouter.ai code, if present on the URL
const searchParams = new URLSearchParams(window.location.search);
const openRouterCode = searchParams.get("code");
```

2023-07-20 17:25 UTC, humphd commented on src/hooks/use-settings.tsx
> +  const handleCodeExchange = (code: string) => {
`handleOpenRouterCodeExchange`

2023-07-20 17:25 UTC, humphd commented on src/hooks/use-settings.tsx
> +          console.error("Error: API key is undefined.");
"OpenRouter OAuth PKCE response missing API key"

2023-07-20 17:25 UTC, humphd commented on src/hooks/use-settings.tsx
> +  // const handleSetApiKey = (apiKey: string) => {
Remove this

2023-07-20 17:25 UTC, humphd commented on src/hooks/use-settings.tsx
> +          const urlWithoutCode = window.location.href.split("?")[0];
This is going to lose data if we ever start relying on the query params later.  I would do something like this:

```js
searchParams.delete('code');
const { origin, pathname, hash } = window.location;
const urlWithoutCode = `${origin}${pathname}${hash}${searchParams.toString()}`
```

2023-07-20 17:25 UTC, humphd commented on src/lib/ai.ts
> +export const openRouterPkceWindow = () => {
`openRouterPkceRedirect` would make more sense

2023-07-20 17:25 UTC, humphd commented on src/lib/ai.ts
> +  const hostname = new URL(callbackUrl).origin;
`window.location` is already a `URL`, why do this again?  Also, why call an `origin` a `hostname`? What I have you before was more clear.

2023-07-20 17:34 UTC, Chigala commented on src/components/Message/AppMessage/Instructions.tsx
> +                Get key from OpenRouter{" "}
Sorry, I don't quite get this.

2023-07-20 17:35 UTC, Chigala commented on src/hooks/use-settings.tsx
> +  //get code from the url
Noted

2023-07-20 17:35 UTC, Chigala commented on src/hooks/use-settings.tsx
> +  const handleCodeExchange = (code: string) => {
Noted

2023-07-20 17:35 UTC, Chigala commented on src/hooks/use-settings.tsx
> +          console.error("Error: API key is undefined.");
I'll add this

2023-07-20 17:35 UTC, Chigala commented on src/hooks/use-settings.tsx
> +  // const handleSetApiKey = (apiKey: string) => {
Noted

2023-07-20 17:37 UTC, Chigala commented on src/components/Message/AppMessage/Instructions.tsx
> +                Get key from OpenRouter{" "}
Ohh,ohk.

2023-07-20 20:01 UTC, humphd commented on src/lib/ai.ts
> +  const hostname = new URL(callbackUrl).origin;
No problem, thanks for working on this.  Ping me when it's ready to review again.

2023-07-21 05:09 UTC, Chigala commented on src/hooks/use-settings.tsx
> +  //get code from the url
Also, where should I cache the URL params object to?

2023-07-21 12:29 UTC, humphd commented on src/hooks/use-settings.tsx
> +  //get code from the url
Exactly what I did in my code (i.e., create a variable here, so we can use it below):

```ts
const searchParams = new URLSearchParams(window.location.search);
```

2023-07-21 14:19 UTC, Chigala commented on src/hooks/use-settings.tsx
> +  //get code from the url
Ohk

2023-07-21 17:22 UTC, humphd approved these changes
Code looks good to me.  @tarasglek can you test with your actual OpenRouter account?  If this works OK for you, I'd say it's good to land.

Nice job @Chigala!

2023-07-22 06:05 UTC, tarasglek commented
It's been working since first push. Only concern was re code quality.
Thanks for getting that sorted to both of you!

2023-07-22 06:06 UTC, merged