contributing doc
tarasglek/chatcraft.org pull request #192
Opened 2023-07-31 17:52 UTC by tarasglek

Feel free to add cloudflare details to this

2023-07-31 17:56 UTC, humphd requested changes
Thanks for starting this

2023-07-31 17:56 UTC, humphd commented on CONTRIBUTING.md
> +- [pnpm](https://pnpm.io) package manager installed globally
Did you want to switch to pnpm from yarn?  That's fine with me.  We'll have to update our scripts, lock file, etc.

2023-07-31 17:56 UTC, humphd commented on CONTRIBUTING.md
> +
Add a note to use `prettier` via VSCode or run the `prettier` script to auto-format.  We also format on commit with Husky.

2023-07-31 18:20 UTC, tarasglek commented on CONTRIBUTING.md
> +- [pnpm](https://pnpm.io) package manager installed globally
i been using pnpm for most of chatcraft history

2023-08-01 12:42 UTC, humphd commented on CONTRIBUTING.md
> +- [pnpm](https://pnpm.io) package manager installed globally
Landed https://github.com/tarasglek/chatcraft.org/pull/193, so now we're using pnpm!

2023-08-07 11:59 UTC, tarasglek commented
```


➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍
--
14:52:01.351 |  
14:52:01.499 | ➤ YN0000: ┌ Resolution step
14:52:04.195 | ➤ YN0061: │ rollup-plugin-terser@npm:7.0.2 is deprecated: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
14:52:05.658 | ➤ YN0061: │ sourcemap-codec@npm:1.4.8 is deprecated: Please use @jridgewell/sourcemap-codec instead
14:52:08.151 | ➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
14:52:12.850 | ➤ YN0061: │ rollup-plugin-inject@npm:3.0.2 is deprecated: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
14:52:12.888 | ➤ YN0032: │ better-sqlite3@npm:8.4.0: Implicit dependencies on node-gyp are discouraged
14:52:19.129 | ➤ YN0002: │ chatcraft.org@workspace:. doesn't provide @codemirror/view (p72df8), requested by @uiw/react-codemirror
14:52:19.130 | ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
14:52:19.136 | ➤ YN0000: └ Completed in 17s 636ms
14:52:19.225 | ➤ YN0000: ┌ Post-resolution validation
14:52:19.226 | ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
14:52:19.226 | ➤ YN0000: └ Completed
14:52:19.226 | ➤ YN0000: Failed with errors in 17s 728ms


```

not sure why this happens

2023-08-07 12:06 UTC, merged