Replace langchain with native openai library v.4.0.0-beta.11.
tarasglek/chatcraft.org pull request #220
Opened 2023-08-17 10:54 UTC by iramykytyn

2023-08-17 12:31 UTC, humphd commented
I see that `v4.0.0` shipped today, might be good to update to that now: https://github.com/openai/openai-node/releases/tag/v4.0.0

@iramykytyn let me know when you want reviews.  I can wait until CI is passing or start sooner, let me know.

2023-08-17 18:00 UTC, iramykytyn commented
> I see that `v4.0.0` shipped today, might be good to update to that now: https://github.com/openai/openai-node/releases/tag/v4.0.0
> 
> @iramykytyn let me know when you want reviews. I can wait until CI is passing or start sooner, let me know.

I need to do some refactoring to let non-streaming function to be working. I will let you know when its ready for review.
Regarding `v4.0.0`, sure I will change it to that version in my next commit.

2023-08-20 12:56 UTC, humphd requested changes
This is a nice code cleanup.  It's looking really good.  I've done a first pass through the code, but not tested it, and made some comments for things to look at.

2023-08-20 12:56 UTC, humphd commented on src/lib/ChatCraftFunction.ts
> +    const openai_parameters: Record<string, unknown> = this.parameters as Record<string, unknown>;
prefer lowerCamelCase in JS/TS: `openAIParamaters`

2023-08-20 12:56 UTC, humphd commented on src/lib/ChatCraftMessage.ts
> +  toOpenAiMessageJson(): OpenAI.Chat.Completions.CreateChatCompletionRequestMessage {
I would drop `Json` from the end of this, as you're returning an object literal.  `toOpenAiMessage()` is probably better.

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +  const chat_completion_params: OpenAI.Chat.CompletionCreateParams = {
`chatCompletionParams`

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +  if (streaming == true) {
`if (streaming)`

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +  const chat_completion_req_options = {
`chatCompletionReqOptions`

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +        let function_name: string = "";
Don't bother assigning a value to these, since you'll throw it away.  Also, `functionName` and `functionArgs`.

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +    response_promise = openai.chat.completions
`responsePromise`

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
So the streaming/non-streaming cases only differ by this `then()` callback?  Can we move those two functions out into `handleStreamingResponse` and `handleNonStreamingResponse` functions or something and only have a single code path here, picking the right handler at runtime?

2023-08-20 12:56 UTC, humphd commented on src/lib/ai.ts
>      // HACK: for some reason, TS thinks this could also be undefined, but I don't see how.
Does this still happen?  I suspect we don't need to manually type this anymore.

2023-08-20 12:56 UTC, humphd commented on src/lib/db.ts
> +export type MessageType = "human" | "ai" | "generic" | "system" | "function";
Can you put this in `ChatCraftMessage.ts` instead and `import` the type here (on line 4 with the other bits from that file)?

2023-08-21 17:48 UTC, iramykytyn commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
I was thinking to do it in that way, and it actually was in my first version pushed here, but then I got build issues since it wasn't able to resolve types runtime. I'm not very confident in TypeScript yet, so maybe I just don't see all the ways to implement it. If you could look at the code and give me the hint I will refactor it 🤗

2023-08-21 18:05 UTC, iramykytyn commented on src/lib/db.ts
> +export type MessageType = "human" | "ai" | "generic" | "system" | "function";
done in [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-21 18:05 UTC, iramykytyn commented on src/lib/ai.ts
>      // HACK: for some reason, TS thinks this could also be undefined, but I don't see how.
Removed [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-21 18:07 UTC, iramykytyn commented on src/lib/ai.ts
> +        let function_name: string = "";
It gives errors if this is not assigned. It says that `Variable 'functionName' is used before being assigned.ts(2454)` 

<img width="807" alt="Screenshot 2023-08-21 at 21 06 13" src="https://github.com/tarasglek/chatcraft.org/assets/6651168/d6051e83-defb-4924-8701-8855c45a3e7e">

2023-08-21 18:07 UTC, iramykytyn commented on src/lib/ChatCraftMessage.ts
> +  toOpenAiMessageJson(): OpenAI.Chat.Completions.CreateChatCompletionRequestMessage {
done in [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-21 18:08 UTC, iramykytyn commented on src/lib/ai.ts
> +  const chat_completion_params: OpenAI.Chat.CompletionCreateParams = {
done in [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-21 18:08 UTC, iramykytyn commented on src/lib/ai.ts
> +  if (streaming == true) {
done in [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-21 18:08 UTC, iramykytyn commented on src/lib/ai.ts
> +  const chat_completion_req_options = {
done in [22dc6ea](https://github.com/tarasglek/chatcraft.org/pull/220/commits/22dc6ea8eb4cdf1d52b5e3c6ca5813d908dda9d2)

2023-08-23 20:30 UTC, humphd requested changes

2023-08-23 20:30 UTC, humphd commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
Why don't we go with your way now, and you can file an issue for someone to refactor this in a follow-up.

2023-08-23 20:37 UTC, iramykytyn commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
I actually did some refactoring. Please take a look at this commit if it looks any better to you [d74c59f](https://github.com/tarasglek/chatcraft.org/pull/220/commits/d74c59fddc71eaf0efcdc72b32c4e3de10e22a19)

2023-08-23 20:45 UTC, iramykytyn commented
> Openrouter is not working yet, it returns some CORS error, I'm investigating it:

@humphd @tarasglek can I create a separate task to fix openrouter issue, since it didn't work as expected before this change, so I believe it's better to handle it in the separate task.

2023-08-23 21:04 UTC, iramykytyn commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
Issue created https://github.com/tarasglek/chatcraft.org/issues/227.

2023-08-26 07:07 UTC, tarasglek commented on src/lib/ai.ts
> +  if (response.choices[0]?.message?.function_call) {
please reduce copy/paste here, put message into a variable..maybe .function_call too

2023-08-26 07:08 UTC, tarasglek commented on src/lib/ai.ts
> +  if (chunk.choices[0]?.delta?.content) {
same here

2023-08-26 07:11 UTC, tarasglek commented on src/lib/ai.ts
> +      .then(async (response: OpenAI.Chat.ChatCompletion) => {
fixing in followup is ok

2023-08-27 06:23 UTC, iramykytyn commented on src/lib/ai.ts
> +  if (chunk.choices[0]?.delta?.content) {
done 
617788c

2023-08-27 06:23 UTC, iramykytyn commented on src/lib/ai.ts
> +  if (response.choices[0]?.message?.function_call) {
done 
617788c

2023-08-27 07:02 UTC, tarasglek commented
This is a big change, solid step forward. Lets land this and fix open router in a followup.
@humphd you ok with that?

2023-08-27 07:07 UTC, tarasglek commented
Found a bug where function calls that throw exceptions don't display errors anymore: working example https://chatcraft.org/c/tarasglek/rQou4E50JmPF_usnFwNAI

2023-08-27 08:05 UTC, iramykytyn commented
> Found a bug where function calls that throw exceptions don't display errors anymore: working example https://chatcraft.org/c/tarasglek/rQou4E50JmPF_usnFwNAI

This is an interesting case because there actually was no function call, it's just GPT generated text response in the same format as our function call.
Double-checked exception handling  and it works as expected, so no issue here.

2023-08-27 08:28 UTC, tarasglek commented
Funny result of my investigation, @humphd would like your ok to land

2023-08-27 16:20 UTC, humphd commented
I'm not going to have time to review this (or anything else) for a while, so if you want to wait that's cool; or if you'd rather go ahead and fix in follow-ups, that's fine with me too.

The last time I read this code, my one concern was about how function calls/results were being converted between OpenAI style and our internal representation.  It's possible that everything is good, but I needed more time to dig into the code, SDK, and OpenAI implementation.

If you do land, please squash this so it's easy to back-out or test changes with bisect later on.

2023-08-28 16:53 UTC, merged