I wanna be able to run ES6 modules and TypeScript
tarasglek/chatcraft.org pull request #222
Opened 2023-08-19 08:28 UTC by tarasglek

Now I can https://chatcraft.org/c/tarasglek/wT9uyV_UCn_DjdGkKwhTm

2023-08-19 12:21 UTC, humphd requested changes
Some mad science going on here, love it!

2023-08-19 12:21 UTC, humphd commented on src/lib/run-code.ts
> +      // no idea how to load the bundled wasm file from esbuild-wasm in vite
Vite can give you a URL to the `.wasm`, see https://vitejs.dev/guide/assets.html#explicit-url-imports:

```ts
import esbuildWasmUrl from "esbuild-wasm/esbuild.wasm?url";

// ...

wasmUrl: esbuildWasmUrl,
```

2023-08-19 12:21 UTC, humphd commented on src/lib/run-code.ts
> +  } catch (error: any) {
Instead of silently failing on re-init, why not add a boolean variable to the module, and set it to `true` on success the first time?

```ts
let initialized = false;

// ...

if (!initialzied) {
  await esbuild.initialize(...);
  initialized = true;
}
```

2023-08-19 12:21 UTC, humphd commented on src/lib/run-code.ts
> +      const module = await import("data:text/javascript;base64," + btoa(code) /* @vite-ignore */);
Data URIs are too limited (can't be more than the size of a URL).  Use a Blob URL, like I do here:

https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/ChatCraftFunction.ts#L143-L147

2023-08-19 12:42 UTC, tarasglek commented on src/lib/run-code.ts
> +  } catch (error: any) {
I started that way, that still occasionally failed

2023-08-19 12:44 UTC, humphd commented on src/lib/run-code.ts
> +  } catch (error: any) {
Race condition?  Maybe we need a value of `'uninitialized' | 'initializing' | 'initialized' | 'error'` instead of a boolean here.

2023-08-19 12:47 UTC, tarasglek commented on src/lib/run-code.ts
> +      // no idea how to load the bundled wasm file from esbuild-wasm in vite
I don't understand this syntax
```text
Error: Failed to download "http://localhost:5173/c/esbuild-wasm/esbuild.wasm?url"
Error: Failed to download "http://localhost:5173/c/esbuild-wasm/esbuild.wasm?url"
    at blob:http://localhost:5173/6500aae8-5933-47e6-9d39-cd7926378d24:652:19
    at Generator.next (<anonymous>)
    at fulfilled (blob:http://localhost:5173/6500aae8-5933-47e6-9d39-cd7926378d24:9:30)
```

2023-08-19 12:49 UTC, humphd commented on src/lib/run-code.ts
> +      // no idea how to load the bundled wasm file from esbuild-wasm in vite
Vite *should* give you a URL to the file in the bundle. This how people load various static assets from within node_modules (e.g., shaders, worker scripts, etc).

I pulled your branch locally and did this and it worked for me.  Want to push your code so I can see?

2023-08-19 12:49 UTC, tarasglek commented on src/lib/run-code.ts
> +  } catch (error: any) {
interesting theory, just need to stick the promise there

2023-08-19 12:59 UTC, tarasglek commented on src/lib/run-code.ts
> +  } catch (error: any) {
no dice, i even tried to disable esbuild worker. For some reason the loaded wasm persists across page reloads whereas my module-global variable does not

2023-08-19 13:01 UTC, tarasglek commented
I can't get the other 2 fixes to work. Do you wanna try?

2023-08-20 15:20 UTC, humphd commented
@tarasglek I made a few changes, pushed a commit.  Seems to work for me.  Can you try?

2023-08-20 17:15 UTC, tarasglek commented
Wow, that's some next level node-foo. I don't recognize either of these fixes.

2023-08-20 17:16 UTC, merged