Add - Size preview iframes to fit contents
tarasglek/chatcraft.org pull request #267
Opened 2023-10-20 02:47 UTC by mingming-ma

Hi, I would like to add this feature that addressed in #205 that supports size preview iframes to fit contents. Let me know about any changes. Thanks a lot!

- [ ] upload test screen shots

2023-10-20 13:10 UTC, humphd requested changes
@mingming-ma this is amazing, thank you!  I've wanted this feature for so long, but never got around to implementing it.  I'm glad you took up the challenge.

I've tested it locally, and it's working well in my limited tests.

I've left some feedback and questions.  Welcome to the ChatCraft dev team :)

2023-10-20 13:10 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          maxHeight={1200}
`1200` seems arbitrary.  Is there a reason you're capping it vs. letting it expand to infinity?  I'm trying to imagine a situation where the LLM writes HTML that produces content too long to be usable.

2023-10-20 13:10 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          checkOrigin={false}
Why is this disabled?

2023-10-20 13:10 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          width="100%"
Why not use their recommended `width` setup https://www.npmjs.com/package/iframe-resizer-react#typical-setup?

2023-10-20 13:58 UTC, mingming-ma commented on src/components/HtmlPreview.tsx
> +          maxHeight={1200}
Yeah, the [minHeight](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#maxheight--maxwidth) not say but by my test it seems use px, and I guess 1200 should be good for most situation, and if more than that, it will goes to scroll mode.

2023-10-20 13:59 UTC, mingming-ma commented on src/components/HtmlPreview.tsx
> +          checkOrigin={false}
This is due to the cdn js, so it will shows warning if true

2023-10-20 14:01 UTC, mingming-ma commented on src/components/HtmlPreview.tsx
> +          width="100%"
Oh, I didn't notice the [example](https://github.com/davidjbradshaw/iframe-resizer-react/blob/master/example/src/app.jsx) uses the different settings. I guess it will works also by the recommended `width` setup. Let me try that.

2023-10-21 00:45 UTC, humphd requested changes

2023-10-21 00:45 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          checkOrigin={false}
This shouldn't be necessary now without CDN, correct?  Let's remove.

2023-10-21 00:47 UTC, mingming-ma commented
@humphd I've made some changes:

- [x] use local js file rather than cdn
- [x] rename variable to `html`
- [x] remove height capping
- [ ] `checkOrigin={false}`
  - This is needed to keep even not using cdn js. After checking I guess the reason is our `iframe`' `src` will starts with` blob:http://localhost`, while the `<script> src` will starts with`http://localhost`
(screenshots: https://github.com/tarasglek/chatcraft.org/assets/133393905/4a8e7dba-37d9-4f7b-a2c4-8959b293d642)
- [x] use recommended width setup

Let me know if there are any other changes needed. Thanks a lot!

2023-10-21 00:51 UTC, mingming-ma commented on src/components/HtmlPreview.tsx
> +          checkOrigin={false}
After trying I think we still need this 😢

2023-10-21 00:56 UTC, humphd approved these changes

2023-10-21 00:56 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          checkOrigin={false}
OK, your explanation makes sense.

2023-10-21 00:56 UTC, humphd commented on src/components/HtmlPreview.tsx
> +          scrolling={true}
Is this necessary if we don't have a height set?

2023-10-21 01:02 UTC, mingming-ma commented on src/components/HtmlPreview.tsx
> +          scrolling={true}
Yeah, should be ok to the content height 😄

2023-10-21 01:04 UTC, merged

2023-10-21 01:05 UTC, humphd commented
Really nice work @mingming-ma, great job!  Can't wait to use this.  I've wanted it for a long time.

2023-10-21 01:08 UTC, humphd commented
Live and working on https://chatcraft.org!:

<img width="1166" alt="Screenshot 2023-10-20 at 9 07 24 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/afee89dc-f95d-4170-afdc-32559b2d5a0f">

@mingming-ma if you'd like to fix another bug, we should disable updates during `loading`, because it flickers so much and jumps the page.

2023-10-21 01:10 UTC, mingming-ma commented
@humphd  Thank you so much for your encouragement! I will definitely try to fix that!

2023-10-21 02:14 UTC, tarasglek commented
@mingming-ma congrats on getting your first contribution in, thank you!

2023-10-21 14:22 UTC, mingming-ma commented
@tarasglek Thank you! More to come!