Fix viewport scroll bug
tarasglek/chatcraft.org pull request #271
Opened 2023-10-24 03:08 UTC by Amnish04

The `main` element of the application has a lot of extra height (about 2.5 times) that of the main grid in `ChatBase` component. The additional scrollbar is hidden from the user because of the use of `overflow: hidden` style. 

Now whenever a sidebar link is clicked, the view loads the correct chat but scrolls to the link that was clicked. However, the user is not able to scroll back up as there is no scrollbar for the actual page due to overflow: hidden` hack.
This creates an impression that the router is messing things up by shifting the viewport.

I've added a fix for this issue, where on each render of this page the document is scrolled to top, preventing the UI from messing up.

**Note:** I might be wrong, but I believe the layout could have some fundamental flaws as 2 scrollbars side by side is a bad design and a red flag.

2023-10-24 12:58 UTC, humphd commented
<img width="1074" alt="Screenshot 2023-10-24 at 8 57 44 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/f020236c-edae-4f7a-8fa4-6b2e5ad55f80">

Go to  chat, scroll down a ways to and click the date.  Whole page scrolls up.

2023-10-24 17:22 UTC, Amnish04 commented
I see. In that case, its better to go after the root cause.

I tried to find problematic item by rebuilding the entire grid piece by piece. Everything was fine until I put in the `PromptForm`.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/fa2ba86b-85f8-4317-ae67-4d1f4b2a526c)

Digging deeper and deeper, I found that this `Menu` for different chat models is the culprit.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/aaa46e41-deb4-4400-adc6-3c0a44cc69c7)

It tries to create space to open downwards, hence adding extra height to the viewport.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/3d35e041-7612-46e5-ae25-39b70de340af)

Making these changes fixes the overflow.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/83958b12-7764-4aab-935f-2e962456418f)

1. Using position `fixed` instead of `absolute`.
2. Fixing the height of chat client menu and adding a scrollbar fixes the overflow.
3. Changed the **Sidebar** `rowSpan` from 3 to 2, as only 2 more rows are available.

2023-10-26 13:00 UTC, humphd requested changes
I think you're onto something, great work! See my feedback for further improvements.

2023-10-26 13:00 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +        <MenuList height={400} overflowY={"auto"}>
Same issue.

2023-10-26 19:34 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +        <MenuList height={400} overflowY={"auto"}>
You're right, I forgot to consider that. Just updated

2023-10-26 19:35 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +        <MenuList height={400} overflowY={"auto"}>
You're right, I forgot to consider that. Just updated

2023-10-26 19:37 UTC, Amnish04 commented
@humphd Just pushed the requested changes.

2023-10-26 19:45 UTC, humphd reviewed
The one downside I see to this approach is that on Mac (at least), you have no visual indication that the menu can be scrolled when it's cropped at 400.

Will letting it expand vertically actually cause problems now, with the other fixes?

I also noticed https://github.com/tarasglek/chatcraft.org/issues/273 while review this, and filed for follow-up.

2023-10-26 20:11 UTC, Amnish04 commented
Yes, the problem with not limiting height is that some of the options get cut off after a certain number.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/2c9479d1-42fb-4402-9558-72c49cbc21cf)

As for the scrollbars in Mac, I am not a 100% sure. But I think this could be the reason:
https://stackoverflow.com/questions/46734299/macs-not-reliably-displaying-horizontal-scroll-bars
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/1493b998-14ee-481b-92b5-45ae4c61c936)


Lastly, for the z-index bug, I wasn't able to reproduce it as my API key has expired and I have no idea how to get a free one.

But the `MenuList` component has a `xIndex` prop that we can use to put it higher in the stack.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/500a4c67-e94a-42d0-b114-c6b37a2d76ed)

I am not sure if its appropriate to define it here, or if we are following any special conventions for these indices in the project.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/7c881a48-4cb5-4b4b-9f93-6d00d71ee232)

2023-10-27 18:51 UTC, humphd commented
I think I would rather not cap the height, and let it expand up into the page.  the user can scroll up if they want, which I think is better than cutting it off and not showing things at all.

I might be wrong about the UX here, and if so, we can fix it in follow-up.

Don't bother with scrollbar stuff (always a bad idea on the web), and don't worry about z-index thing--that's for follow-up.

Summary: get rid of `maxHeight={400}` and leave the rest.

2023-10-27 19:45 UTC, Amnish04 commented
I feel like removing the scroll from the list and not fixing the height of our list box would be a bad design due to the following reasons:

1. We would need to allow the entire page to scroll which would bring 2 scrollbars side by side. And I am pretty sure **double scrollbars** is a bad UX.
2. The list of options can keep growing with time. Not setting a max height for such a large list would force the users to scroll the entire page, when they really just need to focus on the options. This would be a distaction and unnecessary wastage of the browser's real estate.
3. If we still allow the list to expand as much as it wants, that would add extra space below the chat input box, essentially, reintroducing the bug we are trying to fix.

One thing we can do is setting the `maxHeight` to a greater value, so the user does not have to scroll as much.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/5d0e0071-7d4a-4daa-94a5-3a5fb589b1dd)

2023-10-27 19:58 UTC, Amnish04 commented
Another thing I have noticed is having these height props on the chat response container, causes it to have an unnecessary scroll even when not needed.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/e067748c-fd1b-465d-89f9-fe00216241f3)

For example, in a new chat
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/955aaa1e-bff9-4281-a107-858e2925b1a5)


Removing those styles, fixes that problem as well.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/35946fd6-44f8-43ca-931e-c06ce1ac928c)

2023-10-27 21:40 UTC, humphd commented
OK, you've convinced me.  What if we do something like `maxH="80vh"` or something, so it's constrained by the viewport (80 is picked out of the air, there might be a better number)?

2023-10-27 21:50 UTC, Amnish04 commented
I think we can either of the following.

**60vh:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/71ff58fb-dadf-4f59-a56a-6f7a344e7a32)


**70vh:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/2e8eca22-0eb3-4139-b40d-66064a4584f4)

**80vh:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/c94d7dbb-4b6b-444b-ba07-ad592d6c02dd)

I can do whatever you prefer out of these.

2023-10-27 21:54 UTC, humphd commented
I'd say `70` based on your screenshots, but you choose.  I'm on a larger screen, so it's hard to judge.

2023-10-27 21:57 UTC, Amnish04 commented
Also, I found a minor issue on a mobile screen. When expanded, the menu is stuck to right border of window without any spacing.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/37fc598a-d5c8-46bd-85c2-2e9ad64af198)

Setting an offset for mobile fixes the problem:
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/f1dfb56f-063e-463c-b5aa-1a58bddb26a0)

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/b4b75753-e56f-4c58-851a-b64a6306d186)

2023-10-27 21:57 UTC, Amnish04 commented
> I'd say `70` based on your screenshots, but you choose. I'm on a larger screen, so it's hard to judge.

I also prefer 70. Just pushed

2023-10-27 23:03 UTC, humphd approved these changes

2023-10-27 23:04 UTC, humphd commented
I think this is good to land, want to file follow-ups on anything else you think is broken vs. doing here (so we don't expand this beyond it's current scope).

The work you've done here is already amazing, let's get it shipped!  Really impressed with your UI debugging skills.

2023-10-27 23:09 UTC, Amnish04 commented
Thanks a lot! It was my pleasure contributing to the project.
Will file the follow up for the offset bug.

2023-10-28 00:29 UTC, merged