Add 'Save & Submit' button
tarasglek/chatcraft.org pull request #278
Opened 2023-11-08 02:52 UTC by DukeManh

Fixes #277

2023-11-08 19:18 UTC, humphd commented
@DukeManh let me know when you want reviews on this.

2023-11-09 02:32 UTC, DukeManh commented
@humphd, can you review it please.

2023-11-09 14:23 UTC, humphd requested changes
This is looking good.  I have one concern about data loss.

Also, this UI should probably use different colours for Save and Save & Submit:

<img width="907" alt="Screenshot 2023-11-09 at 9 19 53 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/c58ea253-95c4-491d-86c2-2e067aaf2c42">

I think right-most should be CTA and be the primary colour, next one to left should be secondary, and cancel can stay outline or become ghost.

2023-11-09 14:23 UTC, humphd commented on src/components/MessagesView.tsx
> +            await deleteMessages(message.id, "after");
This is surprising.  Why does editing a message and then resubmitting delete anything?

2023-11-10 04:13 UTC, DukeManh commented on src/components/MessagesView.tsx
> +            await deleteMessages(message.id, "after");
So I thought how it works is when you edit a message, the conversation starts again from the editted message similar to chatgpt. Do you have a different idea of how it should work?

2023-11-10 05:08 UTC, DukeManh commented
I changed the 'Save & submit' color, let me know if it looks fine. Since 'Save' is the default action, I moved it to right most.

2023-11-10 12:52 UTC, humphd requested changes
I think this is great.  I have a few things I'd like to see before we land it:

1. Let's rename "Save & Resubmit" to something that better communicates what's going to happen.  The reality is that we're not "Saving" this any more, but we're sort of forking the chat from this point and throwing away the messages that follow.  What about "Re-Ask" or "Save & Restart Chat" or "Save & Continue"?  None of these is perfect, but i want to communicate to the user that this will cause a new thing to happen beyond simply updating the text.
2. Would you mind borrowing the code from the prompt form to advertise that `CTRL + Enter` will save (could happen in follow-up)?  To make room for it, what if we put `Cancel` all the way on the left, and have the two action buttons on the right.

<img width="462" alt="Screenshot 2023-11-10 at 7 45 52 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/0d7b61e7-c830-4e57-8d44-a50be7a8d38a">

3. Let's make `Cancel` use the `ghost` variant, the new button be `outline` and the primary button be `Save`

2023-11-10 16:39 UTC, tarasglek commented
@DukeManh I invited you to the repo for better CI/CD

2023-11-13 01:35 UTC, DukeManh commented
> What about "Re-Ask" or "Save & Restart Chat" or "Save & Continue"?

I like 'Re-Ask', it sounds more precise.

For the the placement of the keyboard hint, I think having the 'Cancel' button on the far left is a bit inconvenient. What about putting it besides button group?

Current
<img width="887" alt="Screenshot 2023-11-12 at 8 28 39 PM" src="https://github.com/tarasglek/chatcraft.org/assets/51073515/82aac2a5-74f7-48f7-a0f5-4eb64a467af0">
Bottom
![Screenshot 2023-11-12 at 8 21 47 PM](https://github.com/tarasglek/chatcraft.org/assets/51073515/50f3513a-af53-4d14-9018-c8dc7f0b2185)
Middle
![Screenshot 2023-11-12 at 8 20 23 PM](https://github.com/tarasglek/chatcraft.org/assets/51073515/6980f3cb-e123-40ac-bcc9-26a3314fa5f2)

2023-11-13 02:06 UTC, humphd approved these changes
I agree with your current placement.  I made one comment, but I think this is good.

Amazing work, Duke!

2023-11-13 02:06 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +      if (e.key === "Escape") {
This is great to have too, nice work.

2023-11-13 02:06 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                          <Kbd>Ctrl</Kbd> + <Kbd>Enter</Kbd>
This will be CMD on Mac.  I think I solved this already in the other part of the code that does this, maybe we can extract a reusable component (could be done in follow-up)?

2023-11-13 03:07 UTC, DukeManh commented on src/components/Message/MessageBase.tsx
> +                          <Kbd>Ctrl</Kbd> + <Kbd>Enter</Kbd>
I will do it in this PR or we might forget about it.
So because we are editing a prompt textarea, I think the default behaviour of Enter is new line and Ctr/cmd + enter is to submit. I don't think it shares the same behaviours with the new prompt such that that we can extract a resusable component.

2023-11-13 11:55 UTC, humphd approved these changes
Excellent work.  Please squash-and-merge when you're ready.

2023-11-14 00:57 UTC, merged