Feature/system prompts table kosty
tarasglek/chatcraft.org pull request #284
Opened 2023-11-10 17:02 UTC by kosty

Overall idea is to move starred system messages to a dedicated table, while keeping other "messages" as they are. Handling "starred" attribute seem difficult in this case. Likely it should become a dynamic check on specific wording being present in "starred" table.

2023-11-11 12:42 UTC, humphd requested changes
This is looking really good @kosty, great work.  I've added some comments of things to fix.  I'll test it locally on some live migrations after you do that.

Appreciate you jumping into this, it's been bugging us for a while.

2023-11-11 12:42 UTC, humphd commented on src/lib/ChatCraftStarredText.ts
> +        if (count == 0) {
This makes me think that we should use the `text` itself as the primary key and drop the `id`.  We don't want duplicates, so let's simply remove the possibility of it happening.

2023-11-11 12:42 UTC, humphd commented on src/lib/db.ts
> +            return tx.table("starred").bulkAdd(promptsEntries, { allKeys: true });
We need to also `.modify()` the `message` records to remove the `starred` property once it's been copied over.

2023-11-11 12:42 UTC, humphd commented on src/lib/ChatCraftStarredText.ts
> +export class ChatCraftStarredText {
Let's rename this to `ChatCraftSavedSystemPrompt` or `ChatCraftStarredSystemPrompt` to be more clear what it is.

2023-11-11 12:42 UTC, humphd commented on src/lib/ChatCraftStarredText.ts
> +  // static fromDB(message: ChatCraftStarredTextTable) {
What's happening with these commented out functions?

2023-11-11 12:42 UTC, humphd commented on src/components/Message/SystemMessage.tsx
> +  const isStarredMessage = useLiveQuery<boolean>(async () => {
`isStarredSystemPrompt`

2023-11-11 12:42 UTC, humphd commented on src/lib/ChatCraftStarredText.ts
> +  static async check(text: string): Promise<boolean> {
Let's name this `exists`

2023-11-11 12:42 UTC, humphd commented on src/lib/ChatCraftStarredText.ts
> +          return Promise.resolve(true);
You can avoid the manual `Promise`s here.  Because you're already returning a `Promise` via the `then()` promise chain, you can simply return your final result, and the containing `Promise` will resolve it.

2023-11-11 18:16 UTC, tarasglek commented on src/components/Message/SystemMessage.tsx
> +          title: `Error changing starred for System Prompt`,
grammar

2023-11-11 18:17 UTC, tarasglek commented on src/components/Message/SystemMessage.tsx
> +          title: `Error changing starred for System Prompt`,
Refusing to change starred prompt?

2023-11-12 12:29 UTC, humphd requested changes
Looks like I reviewed again before you had a chance to fix everything, sorry about that.  I've added more comments.

This is looking better and better.

2023-11-12 12:29 UTC, humphd commented on src/components/Message/SystemMessage.tsx
> +        return Promise.resolve([defaultSystemPrompt()]);
Because you're in an `async` function, all `return` and `throw` statements are automatically wrapped in a `Promise`, you can remove `Promise.resolve()` here and in line 52.

2023-11-12 12:29 UTC, humphd commented on src/components/Message/SystemMessage.tsx
> +  const isStarredSystemPrompt = useLiveQuery<boolean>(async () => {
nit: in an arrow function that only returns a value, drop the `async`, `{...}` body, and `return` statement:

```ts
async () => { return foo() }

// becomes


() => foo()
```

2023-11-12 12:29 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +    this.id = id ?? nanoid();
Remove `id`, use `text` as pk.

2023-11-12 12:29 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +  static async exists(text: string): Promise<boolean> {
Drop `async` on this, you are already returning the `Promise` implicitly.

2023-11-12 12:29 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +  async remove() {
Drop `async` on this, you are already returning the `Promise` implicitly.

2023-11-12 19:40 UTC, tarasglek commented
I am not a fan of this UX. At the moment prompts magically disappear when you switch away from them if you don't star them.

I would prefer to have prompts persist by default + delete button to get rid of em explicitly

2023-11-12 19:44 UTC, kosty commented
I like what @tarasglek  is saying as it has fewer UI gotchas. Currently one has to somehow figure out what "star" means. Either by hovering or just by trial/error. 

One trouble though is that there is difference between saving a message (and it affects any/all messages) and how starred prompts are handled. To get to what @taras is saying we could move all the storage logic to `ChatCraftSystemMessage` yet one would have to come up with eloquent way to present those additional UI butons for "delete". Namely, distinguis between "delete message" and "delete starred system prompt" (aka remove star).

2023-11-12 20:11 UTC, kosty commented
@humphd @tarasglek  added fixes addressing David's comments yet lets keep talking about UI. Would be great if we could navigate to a place that makes ChatCraft and exciting experience

One observation I have is that first message in chat seems to have several different jobs to do
- manage starred prompts
- provide context for rest of the chat

Maybe we could keep star as a way to add texts to stored system prompts and have a dedicated view for management of those, probably somewere in settings, along with export / import.

This would play nicely into next feature - exporting/importing starred text to/from current user's github repo. WDYT?

2023-11-12 20:28 UTC, kosty commented
@tarasglek another naïve idea - what if we just change star UI element to a button that say "Store this promt" / "Forget this pompt" ?

2023-11-13 11:59 UTC, humphd requested changes

2023-11-13 11:59 UTC, humphd commented on src/components/Message/SystemMessage.tsx
> +          title: "Error while checking for presense of Starred System Prompt in db",
```suggestion
          title: "Error while checking for presence of starred System Prompt in db",
```

2023-11-13 18:41 UTC, tarasglek commented
> @tarasglek another naïve idea - what if we just change star UI element to a button that say "Store this promt" / "Forget this pompt" ?

I would prefer to not lose data by default. Just rank prompts by usage if we get too many. It's a good problem to have.

2023-11-14 11:59 UTC, humphd requested changes

2023-11-14 11:59 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +    return db.starred.get(this.text).then((starred) => {
Question: if the text is our PK, why not just write it again vs. bothering with a `get`?  No matter what, we want to end up with the data in the db, so either write or overwrite.

2023-11-14 11:59 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +    return db.starred.get(text).then((entry) => entry !== undefined);
```suggestion
    return db.starred.get(text).then(Boolean);
```

2023-11-14 11:59 UTC, humphd commented on src/lib/db.ts
> +            return tx.table("starred").bulkAdd(promptsEntries, { allKeys: true });
This is still undone, an you add it?

Also, we should be able to drop `starred?: boolean;` from `ChatCraftMessageTable`, etc.

2023-11-15 00:06 UTC, closed without merging