Allow using images as input with gpt-4 vision
tarasglek/chatcraft.org pull request #286
Opened 2023-11-10 23:19 UTC by mingming-ma

Fix #285

2023-11-11 00:10 UTC, mingming-ma commented
## Response cutoff bug investigate
### Results from python scripts for local images vs. chatcraft


<img width="1165" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/281d2bdf-61b4-4d2d-a7b4-7b7cf5ffdebc">


<img width="609" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/793a8fd7-b2fd-4dcb-81a1-967d185d7c68">

2023-11-11 01:25 UTC, humphd commented
This might be worth filing upstream with the https://github.com/openai/openai-node repo itself, since it doesn't seem to be an OpenAI issue.

2023-11-11 17:19 UTC, mingming-ma commented
> This might be worth filing upstream with the https://github.com/openai/openai-node repo itself, since it doesn't seem to be an OpenAI issue.

Yeah, I think the `openai-node` will be updating in the following days, and found another thing, after setting the `max_tokens` in `chatCompletionParams`, seems no cutoff. 

```tsx
    max_tokens: 4096,
```

Result:
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/7863f10b-a5f9-45af-9f15-52fe615b1917)

I found someone said `max_tokens` default to max value of current model, and by looking into `openai-node` code: `ChatCompletionCreateParamsBase` currently only write
```tsx
  model:
    | (string & {})
    | 'gpt-4'
    | 'gpt-4-0314'
    | 'gpt-4-0613'
    | 'gpt-4-32k'
    | 'gpt-4-32k-0314'
    | 'gpt-4-32k-0613'
    | 'gpt-3.5-turbo'
    | 'gpt-3.5-turbo-16k'
    | 'gpt-3.5-turbo-0301'
    | 'gpt-3.5-turbo-0613'
    | 'gpt-3.5-turbo-16k-0613';
```

maybe these given models impact the default max_tokens of `gpt4-vision-preview`, I think I can leave this for now to develop the other tasks.

2023-11-23 13:52 UTC, humphd commented
@mingming-ma this is coming along really well, I'm impressed.  A few things I notice testing this today:

<img width="912" alt="Screenshot 2023-11-23 at 8 48 18 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/70f39fde-18a8-4839-9c68-930312d510ff">

1. I wonder if the close X circle could go over top of the image (maybe top-right corner?) instead of below it. Could happen in follow-up/someone else could do.
2. I want to be able to click on the small version of the image in the prompt form and have it go big so I can see it better (like a light-box that shows in the centre of the screen and you can close?).  Could happen in follow-up/someone else could do.
3. I love how the model changes to when I attach an image, that's smart
4. When I send the image + prompt, I lose the image:

<img width="919" alt="Screenshot 2023-11-23 at 8 51 13 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/4bf77a90-5b04-4a7f-aecf-6352fcc38d86">

We should probably alter the message component so that it can show the image that was attached.

Keep going, you're doing great work here!

2023-11-23 16:24 UTC, mingming-ma commented
@humphd Thanks a lot for the feedback! I just tested store images in db, now we can keep images after submit. Note that since I changed the db schema, better try this in the Incognito Window so that not impact existing IndexedDB. I also tested in my normal Window and seems working as before.

2023-11-24 18:26 UTC, humphd commented
@mingming-ma do you want to fix the conflicts you have in this branch?

2023-11-24 19:17 UTC, mingming-ma commented
@humphd Sure, seems no conflicts on my side for now, let me know I'll fix them.

2023-11-29 15:05 UTC, humphd commented
For some reason, this is showing:

> This branch cannot be rebased due to conflicts

At any rate, some more feedback.

First, I **love** this.  I showed it to some other people and they were blown away too.  Some comments they made:

1. Should be able to paste an image and have it get attached to the current prompt (can happen in follow-up)
2. Images in messages should use width 100%, and be clickable to see full version.

Another optimization we should make: what is the max size of the image that OpenAI will process?  We should resize the image in the browser so we don't waste bandwidth when sending. Can happen in follow-up.

2023-11-29 20:50 UTC, mingming-ma commented
@humphd Oh, It must be that I merged the main branch midway. Thanks a lot for the feed back! I was thinking about implementing the paste function yesterday, and we had the same thought! I'll update the width and check image size for the optimization.

2023-11-29 23:05 UTC, mingming-ma commented
@humphd I've done a rebase. Are there still any conflicts?

2023-11-29 23:09 UTC, humphd commented
No, looks good.  I want to do a pass over the code too, I haven't read it yet.  I'll try to do that this week.

2023-11-29 23:22 UTC, mingming-ma commented
That's great! This PR involves many components, so no rush on the review. Honestly, the code implementation is still quite rough. Can’t wait to see your thoughts on it!

2023-11-30 16:12 UTC, mingming-ma commented
Nice catch 👍  just fixed that

2023-12-05 20:37 UTC, humphd requested changes

2023-12-05 20:37 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                    <img
Do you want to use https://chakra-ui.com/docs/components/image/usage here, and have it fill the width better?

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/ClipIcon.tsx
> +import { useState, useRef } from "react";
Can we rename `Clip` everywhere, including the filename, to be `Attach` or something that better describes what this is for?

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/ClipIcon.tsx
> +  const [colorScheme /*, setColorScheme */] = useState<"blue" | "red">("blue");
if you don't need set, please remove

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +      const modelSupportsImages = models.find((model) => model.supportsImages);
Move this logic to the Model class, similar to other checks we do for OpenAI specific things (e.g., function calling).

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    if (textAreaElement) {
What if I paste an image?

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +      Promise.all(imageFiles.map((file) => getBase64FromFile(file))).then((base64Strings) => {
Add a `.catch()` here so we at least show an error popup, like in other parts of the code that use `alerts`.

2023-12-05 20:37 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +                        <Image
Exactly, do it like this above.

2023-12-05 20:37 UTC, humphd commented on src/lib/ChatCraftMessage.ts
> +    const textAndImage: OpenAI.Chat.Completions.ChatCompletionContentPart[] = [];
This is oddly named, since it might not have an image in it.  I'd call it `content` or something more generic.

2023-12-05 20:37 UTC, humphd commented on src/lib/ChatCraftMessage.ts
> +    if (this.image && this.image.length > 0) {
Why would `this.image` ever be undefined here?

2023-12-05 20:37 UTC, humphd commented on src/lib/ChatCraftModel.ts
> +  get supportsImages() {
Call this in your `useEffect` above.

2023-12-05 20:37 UTC, humphd commented on src/lib/ai.ts
> +    max_tokens: model.supportsImages ? 4096 : undefined,
This worries me.  Is this going to mean we can't go above 4096?  We should confirm this.

2023-12-05 20:37 UTC, humphd commented on src/lib/db.ts
> +  versions?: { id: string; date: Date; model: string; text: string; image: string[] }[];
I think `image: string[]` has to be optional, since no existing data has it.  If you want to include it like you have here, you need to run a migration step to add `[]` to all old messages in the db.

2023-12-12 16:38 UTC, mingming-ma commented
@humphd Absolutely! I didn't have much free time as the end of the semester, but now that it's behind me, I'm committed to making the necessary changes. Thanks a lot for your feedback, and if you can give me another two to three days, I'll do my best to get it done.

2023-12-12 16:45 UTC, mingming-ma commented on src/components/Message/MessageBase.tsx
> +                    <img
Fixed at  [cb915e3](https://github.com/tarasglek/chatcraft.org/pull/286/commits/cb915e357fe1a4cc42b34b35b0907e4af2ecca37)

2023-12-12 16:48 UTC, mingming-ma commented on src/components/PromptForm/ClipIcon.tsx
> +  const [colorScheme /*, setColorScheme */] = useState<"blue" | "red">("blue");
Fixed at [c65d529](https://github.com/tarasglek/chatcraft.org/pull/286/commits/c65d529c4ba77ff2fb2b3e688f5f236e8851abe6)

2023-12-12 16:49 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    if (textAreaElement) {
Yeah, currently supports both image and text copy paste

2023-12-12 16:54 UTC, mingming-ma commented on src/lib/ai.ts
> +    max_tokens: model.supportsImages ? 4096 : undefined,
From this doc https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo, it says "Returns a maximum of 4,096 output tokens." not 100% percent sure for this setting, most likely the reason 
<img width="810" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/a06dead5-baf8-4c07-9327-fb2d2fed0aa3">

My personal test: 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/21ab750d-06d7-4617-9c69-3679274e0b53)

2023-12-12 17:17 UTC, mingming-ma commented on src/lib/db.ts
> +  versions?: { id: string; date: Date; model: string; text: string; image: string[] }[];
Fixed at [5d3143b](https://github.com/tarasglek/chatcraft.org/pull/286/commits/5d3143b4c8fd7fc5381569a1045ed807b3b6e2d1)

2023-12-12 17:33 UTC, mingming-ma commented on src/components/PromptForm/ClipIcon.tsx
> +import { useState, useRef } from "react";
Fixed at [3dea32b](https://github.com/tarasglek/chatcraft.org/pull/286/commits/3dea32b7a73e5ad6afa13fc7cd390ad574c10fc9)

2023-12-12 17:48 UTC, mingming-ma commented on src/lib/ChatCraftMessage.ts
> +    const textAndImage: OpenAI.Chat.Completions.ChatCompletionContentPart[] = [];
Fixed at [21c96ef](https://github.com/tarasglek/chatcraft.org/pull/286/commits/21c96effb4828767df96ded959e1e872a0caea0c)

2023-12-12 18:26 UTC, mingming-ma commented on src/lib/ChatCraftMessage.ts
> +    if (this.image && this.image.length > 0) {
Fixed at [fba7bec](https://github.com/tarasglek/chatcraft.org/pull/286/commits/fba7bec930c0a4222b2f4cca8287dbce32e6fc96)

2023-12-12 21:05 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +      Promise.all(imageFiles.map((file) => getBase64FromFile(file))).then((base64Strings) => {
Fixed at [589c95a](https://github.com/tarasglek/chatcraft.org/pull/286/commits/589c95ab3c03674aaf84ce0e009854e24c1f1e17)

2023-12-13 16:49 UTC, mingming-ma commented
@humphd I think I have fixed most except the 
> [Move this logic to the Model class, similar to other checks we do for OpenAI specific things (e.g., function calling).](https://github.com/tarasglek/chatcraft.org/pull/286#discussion_r1416244517 )
> [Call this in your useEffect above.](https://github.com/tarasglek/chatcraft.org/pull/286#discussion_r1416249489)

I tried to do factor but haven't found a good approach yet. Can you give me a few more hints, or should we consider addressing this in a future pull request?

2024-01-13 16:48 UTC, humphd commented
Two more requests:

1. Support adding more than 1 image at a time in the file picker.  You can add multiple images, but not at once.
2. When there are multiple images, put a number on each one, so it's possible to refer to them.  The LLM seems to understand the order of the images you send in the array, so as long as it matched that order, it might be OK:

<img width="950" alt="Screenshot 2024-01-13 at 11 43 46 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/6e03ae13-6dad-4d6b-9c1e-f459d4ee7bcf">

In the example above, I have 2 screenshots, but no good way to describe them in my prompt.  If there was a "1" and a "2" over top-left corder, similar to your current "X"

2024-01-20 20:14 UTC, rjwignar commented
I've been playing around with this feature for a bit and it's really neat!
One thing I noticed is that when clicking a small image in the input area and then closing the larger version (whether by pressing "Esc" or clicking the Close Button), the input textarea is no longer focused.

Should the prompt be re-focused after closing the full image?

2024-01-25 19:36 UTC, kliu57 reviewed
@mingming-ma
I've tested the following functionalities in my browser and they look good:

- attach multiple images with paperclip icon
- attach multiple images by pasting from clipboard
- remove images in list of attached images
- ask gpt-4-vision-preview to describe images
- ask gpt-4-vision-preview to translate text in image to text
- ask gpt-4-vision-preview to compare two images
- images attached are numbered (index number on top left) and can be removed
- images attached are clickable to see full version
- images stay in chat history
- images sent to chat are sized at width 100% and are clickable

Some questions I have:

- I understand the need to click on an attached image to get a popup with a bigger version of it, but what is the point of being able to click on the image already sent to gpt-4? All you would get is a smaller or equal size version of it.

![question1](https://github.com/tarasglek/chatcraft.org/assets/98062538/cb57146d-cc24-4230-b9d9-ad11a7db57ff)

- When I have attached images but no message written, and click Ask gpt-4-vision-preview, gpt-4 does not answer and the images are wiped. this is the behaviour we want?

![question2](https://github.com/tarasglek/chatcraft.org/assets/98062538/3413cc2c-7778-4001-bb8c-cd2f4d0f6fde)

2024-01-25 21:12 UTC, mingming-ma commented
> I've been playing around with this feature for a bit and it's really neat! One thing I noticed is that when clicking a small image in the input area and then closing the larger version (whether by pressing "Esc" or clicking the Close Button), the input textarea is no longer focused.
> 
> Should the prompt be re-focused after closing the full image?

@rjwignar Thanks for the suggestion. I remember I have did some re-focus in this PR, let me see if this can be added also

2024-01-25 21:34 UTC, mingming-ma commented
@kliu57 Thanks for the testing. 
For the question 1, I think the requirement is coming from some point when the image in history does not have full width of the page.
We need to discuss how to optimize this, by either shows smaller version rather than full width image in history or abandon this popup feature.

For the question 2. I think better send the image and get the response rather than wipe out. Actually I remember I have did this before, let me see why it's not working.

2024-01-27 13:49 UTC, humphd commented
Using this today, I noticed a few things:

First, I love it, and want to see us ship this ASAP!

Second, here are some reflections on the image overlays

![image](https://github.com/tarasglek/chatcraft.org/assets/427398/00e93ccf-54a9-47a9-9f03-561fd4b83243)

The `1` should be round, not an oval.

Both the image number and close button need some margin at the top and left so they aren't so tight.

The close button is clickable, so the cursor pointer needs to change to reflect that.

2024-01-27 15:20 UTC, mingming-ma commented
@humphd Thanks for the feedback! Currently the small picture and close button both clickable, I think I used same `pointer` ![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/c6b24b16-7c6d-4aec-8702-ca0ac09eec1b) for now. Maybe we can change to use`zoom-in` ![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/66b36015-ec06-4c65-91d3-ccb64321b1e2) for the small picture? Any suggestions about the [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) ?

2024-01-27 15:30 UTC, humphd commented
yes, `cursor: pointer` when something is user-clickable.

2024-01-27 15:47 UTC, mingming-ma commented
@humphd like this? 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/d1ba276b-cd97-4aef-860e-b15b9f02871a)

2024-01-27 15:56 UTC, humphd commented
Exactly.

2024-01-29 00:35 UTC, mingming-ma commented
@humphd 1.2 sounds good and I will fix the issues asap

2024-02-07 14:44 UTC, kliu57 reviewed
**Some questions:**

- Q1) I noticed the "attach image" icon is present even when we did not select gpt-4-vision-preview. And when I attach an image we get automatically switched over to gpt-4-vision-preview. Is this the behaviour we want?

If this is the behaviour we want, there is another issue where if you manually change it back to gpt-4 and send the image, we will get an error:

```
Response Error
OpenAI API Returned Error: 400 Invalid content type. image_url is only supported by certain models.
```

**[UPDATE]** As discussed in meeting, the current behaviour is okay.

- Q2) I noticed you changed the image widths in the past messages to not width 100% anymore and when we click on it it shows the image sized at window width 100%. Is this what we want? If it is maybe you can update the PR description with the changed expected behaviour. **[UPDATE]** As discussed in meeting, we want the image to be either centered or 100% width, and when we click on the image, we want the image to go no bigger than its original size.

- Q3) I noticed a past comment by Dave saying we should "Support adding more than 1 image at a time in the file picker. You can add multiple images, but not at once." Right now we are allowing multiple images at once. Was this requirement changed? **[UPDATE]** As discussed in meeting, we DO want to allow attaching multiple images at once.

**Issues:**

- Issue 1) Right now the code in your PR allows users to send blank messages, whereas the code in production does not allow the user to send messages that are blank or only has spaces. This affects not only gpt-4-vision-preview but other models. **[UPDATE]** As discussed in meeting, this issue needs to be fixed. We do not want the user to be able to send blank messages (current behaviour in production)

Everything else looks good to me.

2024-02-07 16:38 UTC, Rachit1313 commented
Follow Ups (for Release 1.2):
- Not being able to send empty messages.
- Don't include images in the body of requests to the model for which images are not supported
Subsequent PRs:
- Image width (either make it 100% or responsive or centered)
- Preview size of the image while clicking whether limit it to the size of original image

2024-02-07 18:02 UTC, kliu57 reviewed
Tested the following vision models on OpenRouter:

- gpt-4-vision-preview (works)
- gemini-pro-vision-vision (works)
- nous-hermes-2-vision-7b (does not work, see ai response below)

```
{"detail":""}{"reason":"error"}
```

Just FYI, if a user wants to use `gemini-pro-vision-vision`, then they would have to upload their images (causing the model to auto-change to `gpt-4-vision-preview`, and then they have to manually change the model to `gemini-pro-vision-vision`. If they change the model to `gemini-pro-vision-vision` first and upload the image it won't work cause we get automatically switched to `gpt-4-vision-preview`

Might be more of an edge case though since I assume not many people would use it.

2024-02-07 21:18 UTC, tarasglek commented
We should definitely not magically switch away from a model that works.

2024-02-08 14:13 UTC, humphd requested changes
@mingming-ma I've gone through the code.  It's really good, you've done a great job managing a very complex change that affects nearly the entire source tree.  Well done.

I have some changes that I want made before we land this on Friday, and some for follow-ups.

To do the rename from `image` to `imageUrls` in lots of places, I suggest you use TypeScript/VSCode and [Rename symbol](https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol).

2024-02-08 14:13 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +  }, [imageModalOpen, inputPromptRef]);
Could these dependencies be added to the previous `useEffect`, since they all do the same thing?

2024-02-08 14:13 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +  const getBase64FromFile = (file: File): Promise<string> => {
We should extract this out into a separate class, maybe a `ChatCraftAttachment` class or something.

Can happen in a follow-up.

cc @rjwignar

2024-02-08 14:13 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    const clipboardData = e.clipboardData;
Should we check the `DataTransfer.types` and only do this for images?

2024-02-08 14:13 UTC, humphd commented on src/lib/db.ts
> +  image?: string[];
I think this should be made a `Blob` in a follow-up, and renamed `attachments` or `files` or something, to indicate it can be various things (cc @rjwignar)

For now, let's rename this to `imageUrls` so it's clear, and do that throughout this PR.

2024-02-08 14:18 UTC, humphd commented on src/components/PromptForm/Attach.tsx
> +        reader.readAsDataURL(files[i]);
Filed #426

2024-02-08 14:19 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +  const getBase64FromFile = (file: File): Promise<string> => {
See #426 for later.

2024-02-08 17:23 UTC, mingming-ma commented on src/Chat/ChatBase.tsx
> +          // Add only image to the chat
seems good, maybe just for fun 😄 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/d3f0247b-e8e6-4fef-95f7-4289082f4b30)

2024-02-08 17:41 UTC, Amnish04 commented on src/components/ImageModal.tsx
> +  Box,
```suggestion
```

Forgot to remove this

2024-02-08 17:43 UTC, Amnish04 reviewed
Oops, forgot to remove the unused import

2024-02-08 17:43 UTC, Amnish04 commented on src/components/ImageModal.tsx
> +  Box,
```suggestion
```

2024-02-08 17:46 UTC, mingming-ma commented on src/components/ImageModal.tsx
> +  Box,
No worries. Thanks for the help.

2024-02-08 23:26 UTC, humphd commented
This needs a rebase for `MessageBase.tsx`.  @mingming-ma please ping us when this is ready for more reviews, let's prioritize getting this merged.

2024-02-09 01:36 UTC, mingming-ma commented
@humphd Got it! Rebased done, just `DataTransfer.types` issue left, will soon to find out.

2024-02-09 01:47 UTC, humphd commented
> @humphd Got it! Rebased done, just `DataTransfer.types` issue left, will soon to find out.

Excited!

2024-02-09 02:12 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    const clipboardData = e.clipboardData;
Have tried that using `DataTransfer.types` and it gives me string `Files`, so we still need some filter on each file like the following
```
      .filter((file): file is File => file != null && file.type.startsWith("image/"));
```

2024-02-09 02:25 UTC, humphd requested changes
Amazing.  A couple small things, and this is good to go from my perspective.

I'm so happy to see this finished, @mingming-ma!  Thank you for following through on what you started in the fall.  This is an epic feature.  People are going to be blown away.

2024-02-09 02:25 UTC, humphd commented on src/Chat/ChatBase.tsx
> +        } else if (imageUrls && imageUrls.length) {
nit: `imageUrls?.length`

2024-02-09 02:25 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    if (inputImageUrls && inputImageUrls.length > 0) {
`inputImageUrls?.length > 0`

2024-02-09 02:25 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    // Assuming models and setSettings are stable and don't need to be in the dependencies array
This may become an issue with the work that @kliu57 is doing to allow switching providers.  Let's add them, it won't cause a lot of re-renders I don't think.

2024-02-09 02:25 UTC, humphd commented on src/lib/ai.ts
> +    max_tokens: model.supportsImages ? 4096 : undefined,
I feel like this may come back to burn us.  Let's try to remember that we did this...

2024-02-09 02:40 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    // Assuming models and setSettings are stable and don't need to be in the dependencies array
Ohh, yeah, this is the last issue to fix I believe 😄 . When using openrouter, mode changes. 

I updated a little bit to this function
```
  get supportsImages() {
    return this.name.includes("vision");
  }
```
It may still goes to the chatgpt4-vision mode. Do you mean we add all the support mode in `supportsImages`?

2024-02-09 02:42 UTC, mingming-ma commented on src/lib/ai.ts
> +    max_tokens: model.supportsImages ? 4096 : undefined,
True. Will check later the newest version frequently.

2024-02-09 03:09 UTC, mingming-ma commented
@humphd  Thanks a bunch for all the feedback! I'm also very excited to tackle this and it's my biggest PR yet! 😄 Luckily, it will be landed soon!

2024-02-09 04:58 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    // Assuming models and setSettings are stable and don't need to be in the dependencies array
OHHH, understand, let me update the dependencies

2024-02-09 15:15 UTC, humphd requested changes

2024-02-09 15:15 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    // Assuming models and setSettings are stable and don't need to be in the dependencies array
I don't understand why this is resolved, it doesn't appear that you fixed this?  Please don't resolve if things aren't done.

2024-02-09 17:40 UTC, mingming-ma commented
@humphd It's strange, I've commit a new one in [f679e4e] so I made that solved. Can you check that again?(https://github.com/tarasglek/chatcraft.org/pull/286/commits/f679e4e8ddc122a24abd71bc59009f6be8107451)

<img width="1045" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/7dee8e43-dfd7-4427-b06a-77564f7eea8f">

2024-02-09 17:41 UTC, humphd commented
@mingming-ma bizarre, I wonder if the GitHub UI was lagging.  It wasn't there when I reviewed.  I apologize.  Thanks for drawing my attention to this.

2024-02-09 17:42 UTC, humphd approved these changes
Ship this 🚢 🚢 🚢!

2024-02-09 17:44 UTC, mingming-ma commented
No worries! Let's make sure all good to land!

2024-02-09 18:36 UTC, humphd commented
@mingming-ma when you're happy, please merge so we can avoid rebase issues.

2024-02-09 18:45 UTC, merged