starred System Prompts table
tarasglek/chatcraft.org pull request #290
Opened 2023-11-15 00:04 UTC by kosty

DB changes to support starred table

Minimal UI updates to make use of the new table

2023-11-15 00:34 UTC, humphd requested changes

2023-11-15 00:34 UTC, humphd commented on package.json
> +    "murmurhash-js": "^1.0.0",
This hasn't been updated in 10 years.  Can we use the built-in stuff that ships in browsers? https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

2023-11-15 00:34 UTC, humphd commented on src/lib/db.ts
> +  starred: Table<ChatCraftStarredSystemPromptTable, string>;
Type issue here

2023-11-15 00:39 UTC, kosty commented on package.json
> +    "murmurhash-js": "^1.0.0",
Thanks for pointing this out! Love how sha-256 is available out of the box and chatcraft codebase is **not** involved with picking seed.

2023-11-15 08:32 UTC, kosty commented on package.json
> +    "murmurhash-js": "^1.0.0",
@humphd async nature of `crypto.subtle.digest` turned out to much for Dexie's transactions. Eventually had to go back to `text` as PK

2023-11-15 13:59 UTC, humphd requested changes

2023-11-15 13:59 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +  remove() {
Make this `static`, rename `delete` to mach how we do it everywhere else in the tree.

2023-11-15 13:59 UTC, humphd commented on src/lib/db.ts
> +        messages: "id, date, chatId, type, text, starred", // Keep the old table and data for now
Can we remove from the old table?  Why keep two copies of this?

2023-11-16 12:18 UTC, humphd requested changes

2023-11-16 12:18 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +  // Find in db or load via URL
Remove the `load via URL` from this comment.

2023-11-16 12:18 UTC, humphd commented on src/lib/db.ts
> +          .delete();
I don't think we want to delete them (that will break old chats).  I think we want to remove the `.starred` property from them, and pull that out of the type.

2023-11-16 12:18 UTC, humphd commented on src/lib/db.ts
> +      messages: "id, date, chatId, type, text",
NOTE: this is only removing the index.  I think we can do this in migration 8 above as part of the upgrade.

2023-11-16 12:23 UTC, humphd requested changes

2023-11-16 12:23 UTC, humphd commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +    this.title = title ?? text.split("\n")[0].substring(0, 42);
Because of the work you want to do in #292, let's make this dynamic (i.e., `get title() {...}`) so we can easily adjust the number use for `42` here, in case you want more/less once you do the UX.

2023-11-16 16:32 UTC, kosty commented on src/lib/ChatCraftStarredSystemPrompt.ts
> +    this.title = title ?? text.split("\n")[0].substring(0, 42);
great point! was wondering how to go about it, and love your take on it.

2023-11-16 16:44 UTC, kosty commented on src/lib/db.ts
> +      messages: "id, date, chatId, type, text",
Not sure how do we go about this. `version(8)` assumes the index on `starred` is there, to perform the migration. So in `version(8)` I could use `.modify({starred: undefined})` or something similar, which will "unset" `starred` attribute. Yet it looks like we still would need `version(9)` to remove an index to an non existing field, if my reading of Dexie docs is right.

2023-11-16 16:45 UTC, kosty commented on src/lib/db.ts
> +          .delete();
I did some trial-testing, and it seemed to work without those starred messages, but I agree it's much safer with them in place. Let's just keep them.

2023-11-16 16:48 UTC, kosty commented on src/lib/db.ts
> +        messages: "id, date, chatId, type, text, starred", // Keep the old table and data for now
Not sure if latter [comment ](https://github.com/tarasglek/chatcraft.org/pull/290#discussion_r1395610048) counters this point or I am missing the point. I like the idea of keeping messages and removing attributes only - safer for user data. Not loosing data is a good thing 😄

2023-11-17 07:18 UTC, kosty commented on src/lib/db.ts
> +      messages: "id, date, chatId, type, text",
@humphd submitted my proposed approach, looking forward to your feedback

2023-11-17 15:23 UTC, humphd commented
@kosty I've made some fixes and cleaned up the types a bit.  See new commit.

2023-11-17 16:13 UTC, kosty commented
looks great to me, learned quite a bit JS/TS while doing this. Neat trick with `get title` and `find(text).then(Boolean)`

2023-11-19 19:21 UTC, merged