Update ai.ts
tarasglek/chatcraft.org pull request #304
Opened 2023-12-11 22:27 UTC by Amir-Helali

Updated the OpenAI's response handling to pick the right handler based on the `streaming` flag. This is done through an interface function which has 2 separate implementations: 1 for handling streaming responses and 1 for handling non-streaming responses. And the `responseHandler` which is in charge of assigning the appropriate function implmenetation based on the value of the `streaming` flag.

Fixes #227

2023-12-12 14:16 UTC, humphd requested changes

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +  const responseHandler: ResponseHandlerStrategy = streaming
Rename this to a verb (it's active, it will "handle the response" vs. passive "responseHandler").  Also, infer the type:

```suggestion
  const handleResponse = streaming
```

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +import {
This formatting looks wrong (run `pnpm prettier` to fix).

Also, these are types, so you should import them as such:

`import type { ChatCompletion, ChatCompletionChunk } from "openai/streaming";`

Move your type imports down below the others and group together:

```ts
import foo from "foo"

import type { bar } from "bar"
```

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +import { Stream } from "openai/streaming";
Move this up with the other imports that are not `type`

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +interface ResponseHandlerStrategy {
A few comments about this:

1. Try to avoid naming new types in TypeScript when they can be inferred.  In this case, you are creating an interface for two functions that already return the same type; that is, both functions you are wrapping return `handleOpenAIResponse()` which is of type `Promise<ChatCraftAiMessage | ChatCraftFunctionCallMessage>`.
2. Whenever you see `any` in TypeScript, it's often a sign that you need to do more work.  Here you are losing the type information I just mentioned above by widening the type to `any` from `ChatCraftAiMessage | ChatCraftFunctionCallMessage`.  Keep it narrow.

If you avoid defining this interface at all, you skip these problems.  I'll show you how below.

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +  const handleStreamingResponse: ResponseHandlerStrategy = async (
You can avoid the return type here and let TS infer it from `return handleOpenAIResponse(content, functionName, functionArgs)`.

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +  const handleNonStreamingResponse: ResponseHandlerStrategy = async (response: ChatCompletion) => {
Same here, drop the return type and infer.  You will end up with the same type for both.

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +    .then(async (response) => {
Simplify this. Both functions take a `response` and return a `Promise`, so you can simply give the function name to use:

```ts
.then(handleResponse)
```

2023-12-12 14:16 UTC, humphd commented on src/lib/ai.ts
> +    .catch((err) => {
Same deal here:

```ts
.catch(handleError)
```

2023-12-13 21:40 UTC, Amir-Helali commented
@humphd Thanks for the feedback. Sorry I've been a bit busy with all the end of the semester work, I will address all the points you provided in your feedback once I am done with the school work.

2023-12-14 03:24 UTC, Amir-Helali commented on src/lib/ai.ts
> +  const responseHandler: ResponseHandlerStrategy = streaming
Done

2023-12-14 03:25 UTC, Amir-Helali commented on src/lib/ai.ts
> +import {
Done

2023-12-14 03:25 UTC, Amir-Helali commented on src/lib/ai.ts
> +import { Stream } from "openai/streaming";
Done

2023-12-14 03:25 UTC, Amir-Helali commented on src/lib/ai.ts
> +interface ResponseHandlerStrategy {
Done

2023-12-14 03:25 UTC, Amir-Helali commented on src/lib/ai.ts
> +  const handleStreamingResponse: ResponseHandlerStrategy = async (
Done

2023-12-14 03:25 UTC, Amir-Helali commented on src/lib/ai.ts
> +  const handleNonStreamingResponse: ResponseHandlerStrategy = async (response: ChatCompletion) => {
Done

2023-12-14 03:33 UTC, Amir-Helali commented on src/lib/ai.ts
> +    .then(async (response) => {
In this case I used parameter type: `any` for `handleNonStreamingResponse()` because `parseOpenAiResponse()` takes a `ChatCompletion`, and if I had used parameter type `ChatCompletion` for `handleNonStreamingResponse()` then I'd got error in `.then(handleResponse)` because the response would be of type `Stream<ChatCompletionChunk>`. Let me know if this needs changing to make the typing narrower.

2023-12-14 03:33 UTC, Amir-Helali commented on src/lib/ai.ts
> +    .catch((err) => {
Done

2023-12-18 17:47 UTC, humphd approved these changes
Looks good, nice simplification.

2023-12-18 17:47 UTC, merged