Added validation for OpenRouter API key
tarasglek/chatcraft.org pull request #306
Opened 2023-12-13 04:03 UTC by kliu57

Closes #230 

Added validation for OpenRouter API key

**Current code (before PR):**
- In `src/lib/ai.ts`, `queryModels()` function, when OpenAI key is invalid, throws an Error
- No validation for OpenRouter key

**PR Code changes:**
- In `src/lib/ai.ts`, `queryModels()` function, use response from https://openrouter.ai/docs#limits to check if OpenRouter API key is valid and throws an Error if `response.ok` is `false`

**Testing:**

Invalid OpenRouter key:

![invalidOpenRouter1](https://github.com/tarasglek/chatcraft.org/assets/98062538/07205159-5865-41e7-846d-8b9991cb54a6)

![invalidOpenRouter2](https://github.com/tarasglek/chatcraft.org/assets/98062538/ba2102de-9353-40ca-8af3-92ca65fe0c4a)

![invalidOpenRouter3](https://github.com/tarasglek/chatcraft.org/assets/98062538/0bd3f8dc-06fd-40dc-bb88-d8b2472503f0)

Valid OpenRouter key:

![validOpenRouter](https://github.com/tarasglek/chatcraft.org/assets/98062538/a020557a-641f-4387-a441-a990ca5ca9dc)

**Regression Testing:**

Invalid OpenAI key:

![invalidOpenAI1](https://github.com/tarasglek/chatcraft.org/assets/98062538/54fbbe53-53b6-4bed-979d-280d8b5dcfc5)

![invalidOpenAI2](https://github.com/tarasglek/chatcraft.org/assets/98062538/c83f6dd3-f3e8-41d8-a32b-1b3c74c00a54)

![invalidOpenAI3](https://github.com/tarasglek/chatcraft.org/assets/98062538/a60a0841-f69f-4426-8549-ffd97b44ea68)

Valid OpenAI key:

![validOpenAI](https://github.com/tarasglek/chatcraft.org/assets/98062538/61a6dddd-04ea-4c3c-8680-960b5468c7a7)

2023-12-13 19:07 UTC, tarasglek commented on src/lib/ai.ts
> +      const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
Note, openrouter is a step toward generic openai compat. Would be good to check if the completion endpoint is openrouter.ai before requiring/initiating the verification

2023-12-13 19:09 UTC, tarasglek commented on src/lib/ai.ts
> +      const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
Example of another endpoint is https://docs.endpoints.anyscale.com/guides/models/

2023-12-13 19:41 UTC, kliu57 commented on src/lib/ai.ts
> +      const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
I have moved the verification code to inside an if block that will only be triggered when apiUrl is for OpenRouter, please let me know if it is ok

2023-12-14 04:15 UTC, tarasglek commented
I like it, thank you for improving this!

2023-12-14 04:18 UTC, tarasglek commented
@kliu57 I added you as a collaborator. For all new work, please push as a branch to chatcraft.org repo, then we can benefit from cloudflare branch deployments.

2023-12-14 04:59 UTC, kliu57 commented
> @kliu57 I invited you as a collaborator, I hope you accept. For all new work, please push as a branch to chatcraft.org repo, then we can benefit from cloudflare branch deployments.

Sure, I can do that for future PRs. Do you need to recreate my current PRs? (this one or PR#308)

2023-12-14 22:51 UTC, tarasglek commented
@humphd ok to accept this one as is?

2023-12-14 22:59 UTC, humphd requested changes

2023-12-15 05:30 UTC, kliu57 commented on src/lib/ai.ts
> +      const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
I have created the generic `validateApiKey()` function and and replaced calls to `validateOpenAiApiKey()` with called to `validateApiKey()`. Please see the updated PR description for full code details. Please review again at your convenience.

Also, I noticed in [`src/hooks/use-models.tsx`](https://github.com/tarasglek/chatcraft.org/blob/main/src/hooks/use-models.tsx) there is a call to `queryModels()`. Now that my OpenRouter validation is not done inside of `queryModels()` anymore, this particular call to `queryModels()` will not be able to validate any OpenRouter keys. Is this something we need to fix?

2023-12-15 13:32 UTC, humphd requested changes
A few small things, this is looking good.

2023-12-15 13:32 UTC, humphd commented on src/lib/ai.ts
> +    return !!(await validateOpenRouterApiKey(apiKey));
Do this `boolean` cast in `validateOpenRouterApiKey` instead, so both functions return the same type, namely, `boolean`.  e.g., return `true` vs. `res` above:

```ts
  if (!res.ok) {
    throw new Error(`${res.status} ${await res.text()}`);
  }

  return true;
```

2023-12-15 13:32 UTC, humphd commented on src/lib/ai.ts
> +  const usingOpenAI = usingOfficialOpenAI();
Don't bother with variables, you can call the the functions in the `if` below

2023-12-15 13:32 UTC, humphd commented on src/lib/ai.ts
> +  } else if (usingOpenRouter) {
No else after return (not needed, since you've already exited, and helps keep code left-aligned and easier to read):

```ts
if (usingOfficialOpenAI()) {
  return validateOpenAiApiKey(apiKey);
}

if (usingOfficialOpenRouter()) {
  return validateOpenRouterApiKey(apiKey);
}

// If not either of those providers, something is wrong
throw new Error('unexpected provider, not able to validate api key');
```

2023-12-15 19:49 UTC, kliu57 commented
@humphd Made the three code fixes as suggested.

Also, I noticed in [`src/hooks/use-models.tsx`](https://github.com/tarasglek/chatcraft.org/blob/main/src/hooks/use-models.tsx) there is a call to `queryModels()`. Now that my OpenRouter validation is not done inside of `queryModels()` anymore, this particular call to `queryModels()` will not be able to validate any OpenRouter keys. Is this something of concern?

2023-12-18 17:52 UTC, humphd commented
@kliu57 This needs to be rebased to pick up the change we just landed in `src/lib/ai.ts`.

I think the call to `queryModels() in `src/hooks/use-models.tsx` doesn't need to be validated, since it will fail if the key is wrong anyway. We only really care about warning people and validating when we are setting the key during setup.

2023-12-18 18:10 UTC, humphd approved these changes

2023-12-18 18:10 UTC, merged

2023-12-18 18:10 UTC, humphd commented
Great work @kliu57.  I hope you'll keep working ChatCraft in the future.