Add .editorconfig and .gitattributes
tarasglek/chatcraft.org pull request #342
Opened 2024-01-15 22:54 UTC by Amnish04

To ensure that all contributors to the project use a **consistent** line ending convention, I have added a [.editorconfig](https://editorconfig.org/#overview) file with the following options.

**1.** end_of_line = lf
**2.** trim_trailing_whitespace = true
**3.** insert_final_newline = true

A list of all options can be found at https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

I've also added [.gitattributes](https://git-scm.com/docs/gitattributes) file, so that git does not use **Windows Line Endings** (\r\n) when checking out files.

2024-01-15 22:55 UTC, humphd requested changes

2024-01-15 22:55 UTC, humphd commented on .editorconfig
> +[src/**.tsx]
I would do this for all files

2024-01-15 23:00 UTC, Amnish04 commented on .editorconfig
> +[src/**.tsx]
That's right, just pushed

2024-01-15 23:07 UTC, humphd approved these changes
One more suggestion, which you can do here or in a follow-up.  Let's add a `.vscode/` directory so this stuff gets done automatically.  We need 2 things:

1. `.vscode/extensions.json` which will list recommended extensions to install for the project:

```json
{
  "recommendations": [
    "editorconfig.editorconfig",
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "streetsidesoftware.code-spell-checker"
  ]
}
```

2. `.vscode/settings.json` project settings for VSCode to do autoformatting and configure the editor for us:

```json
{
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "files.eol": "\n",
  "files.insertFinalNewline": true,
}
```

2024-01-15 23:29 UTC, Amnish04 commented
> One more suggestion, which you can do here or in a follow-up. Let's add a `.vscode/` directory so this stuff gets done automatically. We need 2 things:
> 
>     1. `.vscode/extensions.json` which will list recommended extensions to install for the project:
> 
> 
> ```json
> {
>   "recommendations": [
>     "editorconfig.editorconfig",
>     "dbaeumer.vscode-eslint",
>     "esbenp.prettier-vscode",
>     "streetsidesoftware.code-spell-checker"
>   ]
> }
> ```
> 
>     2. `.vscode/settings.json` project settings for VSCode to do autoformatting and configure the editor for us:
> 
> 
> ```json
> {
>   "editor.insertSpaces": true,
>   "editor.tabSize": 2,
>   "editor.detectIndentation": false,
>   "editor.defaultFormatter": "esbenp.prettier-vscode",
>   "editor.formatOnSave": true,
>   "editor.codeActionsOnSave": {
>     "source.fixAll": true
>   },
>   "files.eol": "\n",
>   "files.insertFinalNewline": true,
> }
> ```

I was also thinking about that. Just pushed, thanks for providing the configurations.

2024-01-15 23:30 UTC, humphd requested changes

2024-01-15 23:30 UTC, humphd commented on .gitignore
>  .vscode/*
I'd consider removing `.vscode/*` from `.gitignore` altogether, now that we're using it. Same with line you added.  All the `.vscode/` stuff can get removed from here.

2024-01-15 23:38 UTC, Amnish04 commented on .gitignore
>  .vscode/*
Makes sense, I've pushed the changes.

2024-01-15 23:39 UTC, humphd approved these changes
Looks good to me, but I haven't tested locally.  Grab a couple other students in Discord to test and review for you.

Nice work.

2024-01-15 23:40 UTC, Amnish04 commented
Sure, will do.

2024-01-16 01:20 UTC, Amnish04 commented
# Testing Instructions

When on a windows machine, you'll commonly notice that VSCode will use **CRLF** (\r\n) as **end of line** symbol by default.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/05072fb1-40a2-4fc8-8765-7f83e3dba5cf)

However, when working on **ChatCraft** (this is true for most other projects), the **formatting standards** align with using an **LF** character (\n) instead.

**More Context:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/52834738-a69c-4666-a0f5-c0524e308754)

## Acceptance Criteria (Steps to Follow)

1. Open **ChatCraft** in **VSCode**, and install [EditorConfog](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) VSCode extenstion.
2. Checkout to [amnish04/editorconfig](https://github.com/tarasglek/chatcraft.org/tree/amnish04/editorconfig) branch.
3. Try opening any source code files, and make sure **EOL** character is set to **LF**.
4. If it is set correctly, manually change it to **CRLF**. This will replace all **EOL** symbols in file with a **\r\n**.
5. Now try saving the file, and make sure the editor does not allow this operation, essentially switching it back to **LF**.

**Note:** If this does not work, you probably need to delete and re-clone the repository so git can set correct line endings using as specified in [.gitattributes](https://github.com/tarasglek/chatcraft.org/blob/49cec408c021f0fc9efaa4a6f649e175c1306751/.gitattributes) file.

2024-01-17 18:51 UTC, kliu57 requested changes
Working:
- extra lines and trailing spaces are removed upon file save (Prettier)
- final empty line is automatically added upon save (Prettier)
Not working:
- recommended extensions are not automatically installed, recommend adding docs to ask users to install recommended extensions
- end of line sequence in VS Code is expected to change to LF automatically but it did not

2024-01-17 19:17 UTC, humphd commented
This needs a rebase, too, since Taras added sops diff info to `.gitattributes`.

2024-01-17 19:31 UTC, Amnish04 commented
Just **rebased**, will look into the issues encountered by @kliu57.

2024-01-18 00:16 UTC, Amnish04 commented
I just test on my macbook and seems to work fine.

![EditorConfig Demo](https://github.com/tarasglek/chatcraft.org/assets/78865303/fb8ee840-f884-424c-8b82-62517db65237)

2024-01-19 16:53 UTC, rjwignar commented
Testing these changes on a Windows 10 computer. I'll report my findings in a bit

2024-01-19 16:54 UTC, Amnish04 commented
> Testing these changes on a Windows 10 computer. I'll report my findings in a bit

Sure, just make sure to install all the recommended extensions.

2024-01-19 18:16 UTC, rjwignar commented
>Sure, just make sure to install all the recommended extensions.

Thanks for the heads up. Here's what I've been able to determine.

Findings
---
## Extra lines and trailing spaces
Both are removed upon file change.
Multiple extra lines are collapsed into one line

## Final empty line
Final empty line is added upon file save

## Recommended extensions installation
I had a similar experience to @kliu57 on the workspace extensions, where the extensions are not installed automatically.
Instead, I received a prompt from VSCode asking to install the `.vscode/extensions.json` extensions not already installed (in my case it was just **EditorConfig for VS Code**):
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/daf537d6-c13d-4c27-a40f-40e6c7600542)

I was able to install all extensions defined `.vscode/extensions.json` by navigating to the `Extensions view` and typing `@recommended` in the searchbar:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/ae308222-a74b-4315-8f10-ed91b9c5f994)
The `@recommended` filter shows the extensions in `.vscode/extensions.json` and clicking the cloud icon circled in red installs all of those extensions at once (if they aren't already installed).

## VS Code End of Line sequence
When I select **CRLF** as my EOL sequence on VSCode, Prettier seems to take notice and marks all the CRLF's:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/97aaec9d-a491-4da3-98af-4410fdbfb613)

When I save the file, the warning markers disappear and the EOL sequence **for that file** changes to **LF**:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/5ca96bc3-d8c9-44b5-8659-25f29c57a25c)

However, when I paste the content of this file into **Notepad++**, it seems to show **CRLF** instead of **LF**.
I don't know if this is just a windows thing:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/ecfcbda2-a682-4559-8376-e289d0b0eec4)

2024-01-19 20:16 UTC, Amnish04 commented
@rjwignar Thanks for the detailed review!

For **VSCode** extensions.json, it is supposed to suggest the [recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions) to users when they open their workspace and is not expected to install them automatically.

Also, your feedback indicates that the **EditorConfig** settings are behaving **as expected**.

@humphd Could you please confirm if this is good to merge?

2024-01-19 21:10 UTC, humphd commented
I think we're good to go here.

2024-01-19 21:44 UTC, merged