Added logic for sorting the retry options
tarasglek/chatcraft.org pull request #344
Opened 2024-01-16 22:10 UTC by Rachit1313

Fixes #316

2024-01-16 23:38 UTC, tarasglek commented
The bottom menu needs sorting too. 

<img width="1134" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/b69ec68f-ea3c-4b9f-90e4-48f8d9a8c26b">

Need to unify this sorting code somewhere. Maybe do it at the point of requesting list models endpoint?

2024-01-16 23:39 UTC, tarasglek commented
Thanks for breaking this up into separate pull req

2024-01-17 13:31 UTC, humphd requested changes
Let's fix this at the source, so it works for every user of `models`, which we get from the `useModels()` hook:

https://github.com/tarasglek/chatcraft.org/blob/a24f51d0f008bb12ae04ecbeece76b696bdf927e/src/hooks/use-models.tsx#L57

If you change the way we do the sort there, it should mean we're good in all UI situations.

2024-01-17 20:42 UTC, humphd requested changes

2024-01-17 20:42 UTC, humphd commented on src/hooks/use-models.tsx
> +          // models.sort();
you can delete vs. comment-out code

2024-01-17 21:12 UTC, tarasglek commented
<img width="838" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/5b626e06-4fde-4c5b-b83b-f72dae3134c7">

Still not sorting bottom menu

2024-01-17 21:14 UTC, humphd commented
Given that we ultimately want the pretty names to be sorted, let's do that in the hook (i.e., convert the models to ChatCraftModel instances, then sort on the `prettyName`) so that all consumers will have this list in the right order.

2024-01-17 21:26 UTC, humphd requested changes

2024-01-17 21:26 UTC, humphd commented on src/hooks/use-models.tsx
> +          models.sort();
Don't bother sorting here if you're going to sort again later.

2024-01-17 21:26 UTC, humphd commented on src/hooks/use-models.tsx
> +    models: models?.sort((a, b) => a.prettyModel.localeCompare(b.prettyModel)) || defaultModels,
Do this above on line 60 so you cache the result in state vs. doing it for every consumer:

```ts
models.sort((a, b) => a.prettyModel.localeCompare(b.prettyModel))
setModels(models);
```

2024-01-17 21:33 UTC, Rachit1313 commented on src/hooks/use-models.tsx
> +          models.sort();
removed

2024-01-17 21:33 UTC, Rachit1313 commented on src/hooks/use-models.tsx
> +    models: models?.sort((a, b) => a.prettyModel.localeCompare(b.prettyModel)) || defaultModels,
done thanks.

2024-01-17 22:59 UTC, humphd approved these changes
Code change looks good to me.  Get some of your colleagues to test the change at the UI level and/or put in some screenshots of it doing what you expect.

2024-01-18 06:56 UTC, tarasglek approved these changes
good to land. this will be very helpful

2024-01-18 06:58 UTC, Rachit1313 commented
> Code change looks good to me. Get some of your colleagues to test the change at the UI level and/or put in some screenshots of it doing what you expect.
<img width="1422" alt="Screenshot 2024-01-18 at 12 27 22 PM" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/ee745c91-5c4a-4755-b9f8-2837455ebd20">
<img width="1310" alt="Screenshot 2024-01-18 at 12 27 29 PM" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/0faaa4bf-527d-4c67-a5dc-9ca404b645ca">

2024-01-18 07:02 UTC, Rachit1313 commented
> good to land. this will be very helpful

Do you want me to squash the commits?

2024-01-18 07:06 UTC, merged