Add Latex Rendering with remark-math and Katex Plugins
tarasglek/chatcraft.org pull request #349
Opened 2024-01-17 21:40 UTC by mingming-ma

Fix #333 #335 

Need to add "formula in LaTeX by enclosing it with $$ display style" or similar to mention the dollar symbol in the prompt.

2024-01-17 22:51 UTC, humphd requested changes
We better update the default system prompt to include a line about using Latex/Katex for any math, so the model does it and we can render it.

2024-01-18 01:22 UTC, humphd requested changes

2024-01-18 01:22 UTC, humphd commented on src/lib/system-prompt.ts
> +- formula in LaTeX by enclosing it with $$ display style
```suggestion
- If responding with math, use KaTeX syntax in your Markdown by enclosing it in $$...$$
```

2024-01-18 01:57 UTC, mingming-ma commented on src/lib/system-prompt.ts
> +- formula in LaTeX by enclosing it with $$ display style
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/09f74d87-80dc-4ba7-98af-829e62029a94) Seems a little bit confusing after rendering, let me try another approach

2024-01-18 02:23 UTC, tarasglek commented
nice

2024-01-18 12:03 UTC, humphd commented on src/lib/system-prompt.ts
> +- formula in LaTeX by enclosing it with $$ display style
You could try these:

- If responding with math, use KaTeX syntax in your Markdown
- If responding with math, use KaTeX syntax in your Markdown by enclosing it in double-dollar signs

2024-01-18 12:51 UTC, humphd requested changes

2024-01-18 12:51 UTC, humphd commented on src/lib/system-prompt.ts
> +- If responding with math, use KaTeX syntax in your Markdown by enclosing it with the dollar symbol rather than parentheses, for example: $$O(nlogn)$$
'...with double-dollar signs...'

I like that you included an example, smart.

2024-01-19 00:20 UTC, humphd approved these changes

2024-01-19 14:27 UTC, merged

2024-01-19 20:45 UTC, tarasglek commented
This has a funny conflict with coding :(
<img width="621" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/4ee41871-ea78-4e87-ab97-38936aaa1adf">

<img width="621" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/6919f671-f540-4fc4-a7a5-89953121df78">

2024-01-19 20:52 UTC, mingming-ma commented
👍 somewhere need to configure so only accept $$, let me fix that

2024-01-19 20:53 UTC, humphd commented
Or never render katex/math in code/pre blocks.