Add Text to Speech Support
tarasglek/chatcraft.org pull request #357
Opened 2024-01-22 23:00 UTC by Amnish04

Regarding issue #354 

I think I was able to implement an initial version of TTS support.

I've added an additional button in the prompt menu that allows users to select if they want to enable this feature.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/f02075b5-61cc-4c63-9f0b-c8f66de613be)

Whenever we ask a question, the response is read using the TTS api.

I am buffering the words received from LLM stream over time and once the `threshold` is reached, I pass it to the TTS method for audio generation.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/575b59f5-a9dc-452d-9f7d-d856d58a91c5)

I've also added a `useAudioPlayer` hook that manages the playback of audio chunks by making sure they play in order.

I feel like its still very rough and lots of optimizations/changes need to be done.

2024-01-23 01:28 UTC, tarasglek commented on src/hooks/use-chat-openai.ts
> +              ttsWordsBuffer.length >= TTS_BUFFER_THRESHOLD
I feel like the buffer should be sentence-based,eg split on '.' and ensure you have > some minimal number of words(3?)..It feels like adding indiv words(eg 2-3 words that fit into 50 chars) to queue would make the experience terrible for slow outputs

2024-01-23 02:14 UTC, Amnish04 commented on src/hooks/use-chat-openai.ts
> +              ttsWordsBuffer.length >= TTS_BUFFER_THRESHOLD
I think there's a confusion. The buffer threshold of 50 is not chars, but words.

But I agree with you that it should be sentence-based because most times the buffer ends in the middle of a sentence (at 50 words interval), and it takes time (about a second) for the next audio chunk to start playing. Doing it based on sentences would only apply a pause at the end of sentence.

However, I'll need to think of a way to add back correct punctuations at the end of each sentence for accurate expressions if we are splitting on those.

2024-01-23 07:28 UTC, tarasglek commented
I tried this, it works! Thank you!

1) Detection shouldn't hardcode official openai..Just use the models endpoint and look for tts* models
<img width="583" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/5439c726-c888-4c63-bbe2-c3ae256a93f0">

2)I think we need to have submenus in message options. Eg I would like TTS to be exposed as "Speak" with a submenu of voices. Would also like to have autospeak and menu items.

Basically there are 2 separate cases: a) hands-free chat using mic and tts to respond and b) using chatcraft to speak messages for producing downloadable audio

2024-01-24 03:23 UTC, tarasglek commented
I think we should move 'retry with' to a submenu, and also add "speak with" submenu. Thus this depends on https://github.com/tarasglek/chatcraft.org/issues/359 to proceed

2024-01-24 17:00 UTC, humphd commented
In our meeting today, we agreed to try and extract a version of this PR that we can land for 1.1 (next Friday) and iterate in future Issues/PRs as we understand things better.

2024-01-25 21:13 UTC, rjwignar reviewed
I've played around with this and I'm having lots of fun with it.
I like how both TTS responses and TTS input are both supported.

I can't offer suggestions on the code but the naming conventions used for methods and variables looks fine.

I did notice a couple things on desktop:
1. The `speech input` button/microphone icon doesn't show a tooltip when hovered. Is this something that should be added?
2. I also noticed that on desktop, using speech input requires users to click and hold the microphone button, releasing the button when they're finished their request. Would it be better to have the user click the button once to start recording, then to click the button again when they're done recording?

I also wonder how the speech input button would behave on a smartphone. Would it behave the same way (user must press + hold the microphone button while talking)? Is there a way we can test this build on our smartphones?

2024-01-25 21:13 UTC, rjwignar commented on pnpm-lock.yaml
> +      '@types/node': 20.8.7
Is a major version jump like this likely to break anything? So far this branch behaves like the current main branch (i.e. nothing seems to be broken), so I think we're safe.

2024-01-25 22:07 UTC, mingming-ma commented
@rjwignar I test the mobile before using the safari on my iphone, I think any browser should be ok, just navigate to the deployed [url](https://amnish04-tts-support-354.console-overthinker-dev.pages.dev), I find sometimes the url will show by bot, but if not you can find that info in the Details in the `All checks`

2024-01-25 23:03 UTC, tarasglek commented
> 2. I also noticed that on desktop, using speech input requires users to click and hold the microphone button, releasing the button when they're finished their request. Would it be better to have the user click the button once to start recording, then to click the button again when they're done recording?

> 
> I also wonder how the speech input button would behave on a smartphone. Would it behave the same way (user must press + hold the microphone button while talking)? Is there a way we can test this build on our smartphones?

Same on mobile. It's glitchy on mobile. I would prefer to change behavior to click once to record and once to stop as you suggest as that will likely be less glitchy.

2024-01-26 02:57 UTC, Amnish04 commented
> I've played around with this and I'm having lots of fun with it. I like how both TTS responses and TTS input are both supported.
> 
> I can't offer suggestions on the code but the naming conventions used for methods and variables looks fine.
> 
> I did notice a couple things on desktop:
> 
>     1. The `speech input` button/microphone icon doesn't show a tooltip when hovered. Is this something that should be added?
> 
>     2. I also noticed that on desktop, using speech input requires users to click and hold the microphone button, releasing the button when they're finished their request. Would it be better to have the user click the button once to start recording, then to click the button again when they're done recording?
> 
> 
> I also wonder how the speech input button would behave on a smartphone. Would it behave the same way (user must press + hold the microphone button while talking)? Is there a way we can test this build on our smartphones?

@rjwignar Thanks for the review! 
I agree with you on that there should be a `tooltip` for **microphone** button as currently it does not have any descriptive text.
And you're right, the microphone part is almost unusable on mobile, but this pull request only focuses on **text to speech** support (#354).

I saw that @tarasglek already mentioned it before in this issue #336 that focuses on better mobile interface.
We can probably have a separate standalone issue for fixing the **mic behaviour**.

2024-01-26 03:03 UTC, Amnish04 commented
> @rjwignar I have tested the mobile version before using the safari on my iphone, I think any browser should be ok, just navigate to the deployed [url](https://amnish04-tts-support-354.console-overthinker-dev.pages.dev), I find sometimes the url will show by bot, but if not you can find that info in the Details in the `All checks`
> 
> I just tried this on my phone and I didn't hear any sound, I tap the TTS enabled but seems not works.

@mingming-ma Thanks for reviewing!

I also tested using your link on my phone and it didn't work for me either.

But I also tested using my codespace on **phone** and its **working** with that.
https://symmetrical-space-doodle-p6wqvr79qrj26gv9-5173.app.github.dev/c/MWt4JUNQcG-d3jyhHzGtS

Not sure why it didn't work for the other one 🤔

2024-01-26 14:01 UTC, humphd commented
> > 2. I also noticed that on desktop, using speech input requires users to click and hold the microphone button, releasing the button when they're finished their request. Would it be better to have the user click the button once to start recording, then to click the button again when they're done recording?
> 
> > I also wonder how the speech input button would behave on a smartphone. Would it behave the same way (user must press + hold the microphone button while talking)? Is there a way we can test this build on our smartphones?
> 
> Same on mobile. It's glitchy on mobile. I would prefer to change behavior to click once to record and once to stop as you suggest as that will likely be less glitchy.

Let's not deal too much with general audio UI in this issue if possible, and move that to an external issue.  I'll file an issue on this change.

2024-01-27 03:09 UTC, rjwignar approved these changes

2024-01-27 03:13 UTC, rjwignar commented
> Let's not deal too much with general audio UI in this issue if possible, and move that to an external issue. I'll file an issue on this change.
> 
> #368

In that case, the current changes look good to me. I'm very satisfied with the TTS button and functionality.

> In our meeting today [Wednesday], we agreed to try and extract a version of this PR that we can land for 1.1 (next Friday) and iterate in future Issues/PRs as we understand things better.

Does anything in this PR have to be changed before we can merge it?

2024-01-27 07:14 UTC, Amnish04 commented
Just modified my buffering algorithm in the way I've been thinking about.

The following **pseudocode** is a summary of what's happening.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/9981660b-e771-483a-a588-e0eb7dab3e13)

This is following the sentence based approach that @tarasglek [suggested](https://github.com/tarasglek/chatcraft.org/pull/357#discussion_r1462622977).

I tried this, and it's much faster than previous way in many cases.

Please let me know if this works!

2024-01-27 07:27 UTC, Amnish04 commented
> I tried this, it works! Thank you!
> 
>     1. Detection shouldn't hardcode official openai..Just use the models endpoint and look for tts* models
> 
> 
> <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/857083/298836122-5439c726-c888-4c63-bbe2-c3ae256a93f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDAzMzQsIm5iZiI6MTcwNjM0MDAzNCwicGF0aCI6Ii84NTcwODMvMjk4ODM2MTIyLTU0MzljNzI2LWM4ODgtNGM2My1iYmUyLWMzYWUyNTZhOTNmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNzIwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzQzMDQ1YmExOTNjNzMwNGQwMDZiZGUxNjczZmM0YjRhNDNiOGY5MjQxODk5N2JlYjhmY2U0NmI0NjEwOTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KurYXavG2htkZq3EtoHrWdJBrYXq511pVS4wX3RagGM">
> 
> 2)I think we need to have submenus in message options. Eg I would like TTS to be exposed as "Speak" with a submenu of voices. Would also like to have autospeak and menu items.
> 
> Basically there are 2 separate cases: a) hands-free chat using mic and tts to respond and b) using chatcraft to speak messages for producing downloadable audio

Also @tarasglek, I couldn't understand your first point.

Is it regarding this function?
<img width="662" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/12d38fe6-d53a-4dfc-b49a-05b025175d5d">

Or the way I have hardcoded `tts-1` here

<img width="694" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/0027a439-fda3-4a06-b3bd-480c2664942e">

2024-01-27 13:30 UTC, humphd commented
@Amnish04 a few thoughts:

1. We have an nlp tokenizer in our tree already, see https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/summarize.ts.  You can use it to get your sentences, words, etc. See docs at https://github.com/spencermountain/compromise.
2. @tarasglek means, "Don't use Is Official OpenAI" as your means for determining if TTS is supported, since other providers can/will also provide the same or similar models.  It would be better to see if the list of models includes `tts-` or something.

@rjwignar thanks for your review and push to get this landed. I'm loving seeing this evolve so quickly.  Great work.

2024-01-31 18:49 UTC, humphd requested changes
This is looking pretty close, a few things I noticed reading the code.

2024-01-31 18:49 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +          <Tooltip label={settings.announceMessages ? "TTS Enabled" : "TTS Disabled"}>
"TTS" might not be something users understand.  In user-facing UI, maybe "Text-to-Speech" might be more clear.

2024-01-31 18:49 UTC, humphd commented on src/hooks/use-chat-openai.ts
> +        async onData({ currentText }) {
You're not actually `await`'ing here.  I also wondered about adding `Promise<string>` vs. `string` to the audio queue.  Can we `await` the values before we add the strings?

2024-01-31 18:49 UTC, humphd commented on src/hooks/use-chat-openai.ts
> +        async onData({ currentText }) {
Reading the code below for `textToSpeech()`, I would `await` all these calls, and have your queue your queue hold `string` instead.

2024-01-31 18:49 UTC, humphd commented on src/hooks/use-audio-player.ts
> +      setQueue((oldQueue) => oldQueue.slice(1));
You should call `URL.revokeObjectURL()` here so you don't leak these MP3 blobs after you are done playing each one.

2024-01-31 20:04 UTC, Amnish04 commented on src/hooks/use-chat-openai.ts
> +            lastTTSIndex = newWordsCount;
Actually, I replaced this entire logic. So these lines are already gone.

2024-01-31 21:11 UTC, Amnish04 commented on src/hooks/use-chat-openai.ts
> +        async onData({ currentText }) {
Actually, I was awaiting it outside initially. That's why I have that `async` keyword there (forgot to remove in cleanup).

The reason why I don't `await` it before pushing is that there is no guarantee when `openai` api finishes processing and resolves a specific url.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/050db22e-012e-402e-a279-86a9db8f7d38)

**Example:**
Let's imagine we have 2 strings that need to be processed - `A` and `B`.

 1. We call the `textToSpeech` function for `A`, and the thread starts handling the next available operation until this is processing.
 2. While processing for `A` was happening, we were receiving more data in `onData` and `textToSpeech` got called for `B`.
 3. Unfortunately, the promise returned by `textToSpeech` got resolved first for `B`, and it gets added to queue.
 4. Ultimately, the audio clip for `A` also gets added.

This means our queue is like this now.
[audio for B, audio for A]
which beats the purpose for having a queue in the first place as the order is incorrect.

Just to confirm this, I tried the approach you mentioned again but got really **weird behaviour**.

2024-01-31 21:12 UTC, Amnish04 commented on src/hooks/use-audio-player.ts
> +      setQueue((oldQueue) => oldQueue.slice(1));
I never knew that. Thanks for sharing!

2024-01-31 21:16 UTC, Amnish04 commented on pnpm-lock.yaml
> +      '@types/node': 20.8.7
I don't see any typescript warning as such, so should be good?

Also, I don't remember upgrading this manually. But I see that its a peer dependency for `openai`, so maybe it got automatically upgraded when I upgraded `openai`.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/0a94d98d-f199-4e42-90a4-723a734e29b9)

2024-01-31 21:17 UTC, Amnish04 commented
@humphd Just pushed some changes as requested and left comments on some.

2024-01-31 21:18 UTC, humphd approved these changes

2024-01-31 21:18 UTC, humphd commented
Make sure all the follow-ups we need to do are filed before you land.

2024-01-31 21:39 UTC, rjwignar commented on pnpm-lock.yaml
> +      '@types/node': 20.8.7
>We should probably update to node 20 from 18 regardless, and could do it in a separate PR. It might affect the CloudFlare build and Workers functions, so it needs a bit of care.

@humphd if `@types/node` is a peer dependency for the `openai` version required for TTS support, do we still need a separate PR for upgrading `@types/node`?
Also, is there a way we can break test the CloudFlare build and worker functions on this PR branch?

2024-01-31 21:49 UTC, humphd commented on pnpm-lock.yaml
> +      '@types/node': 20.8.7
If it built OK in this PR preview with CloudFlare, then it should be fine.

2024-01-31 21:50 UTC, merged

2024-01-31 22:54 UTC, tarasglek commented on src/components/PromptForm/PromptSendButton.tsx
> +              icon={settings.announceMessages ? <AiFillSound /> : <AiOutlineSound />}
I find it nearly impossible to tell apart the 2 icons. I suggest one of the chatcraft suggestions

1. **Volume Up / Volume Off**
   - On: `MdVolumeUp`
   - Off: `MdVolumeOff`

2. **Speaker High / Speaker Mute**
   - On: `FaVolumeUp`
   - Off: `FaVolumeMute`

3. **Microphone / Microphone Slash**
   - On: `FaMicrophone`
   - Off: `FaMicrophoneSlash`

4. **Headphones / Headphones Slash**
   - On: `FaHeadphones`
   - Off: `FaHeadphonesAlt`

5. **Play Circle / Pause Circle**
   - On: `FaPlayCircle`
   - Off: `FaPauseCircle`

6. **Soundwave / No Soundwave**
   - On: `BiVolumeFull`
   - Off: `BiVolumeMute`

7. **Music Note / No Music**
   - On: `IoMusicalNote`
   - Off: `IoMusicalNotes

2024-01-31 22:55 UTC, tarasglek commented
Also tts seems to on always for me. Icons change, but the damn thing wont shut up

2024-01-31 22:55 UTC, tarasglek commented
Need to have audio abort when tts is in progress and one flips icon off

2024-01-31 22:56 UTC, humphd commented
@Amnish04 would you be willing to file those for follow-up so we don't lose?