Fix: Better UX for long messages
tarasglek/chatcraft.org pull request #358
Opened 2024-01-23 23:18 UTC by mingming-ma

Fix #339

2024-01-25 14:07 UTC, WangGithub0 commented on src/components/Message/HumanMessage.tsx
> +  const { text } = message;
can you directly use message instead of extracting text from it?

2024-01-25 14:41 UTC, humphd reviewed
After I click "Show More...", I have to scroll all the way to the bottom to find "Show Less"

<img width="921" alt="Screenshot 2024-01-25 at 9 38 39 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/b39f5768-8de1-458b-836f-35bf989957e1">

This makes it hard to toggle full vs. collapsed view.  I wonder if we should show the "Show Less" at the top and bottom?

2024-01-25 15:58 UTC, mingming-ma commented
@humphd That's a great feedback, we should have a way to quick collapse here!

Meanwhile, adding the button "Show Less" at the top is a little bit of hard because the `CardHeader` is defined in the `MessageBase` component, while the `Show More/Less` button is defined in the footer which can be passed from `HumanMessage` (and other higher component) to `MessageBase`

Currently we have these buttons in the header, 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/2c557cc5-bbb1-4766-9cef-b7a97b7bf938)
I suggest we add a new icon button next to the `copy`, to plays as jump to the end of current card (then user can see the `Show less` button and toggle), it also gives user a choice to quick go to next message, and it is implemented quite [easily](https://stackoverflow.com/a/51828976):

```
const ScrollDemo = () => {
   const myRef = useRef(null)

   const executeScroll = () => myRef.current.scrollIntoView()    
   // run this function from an event handler or an effect to execute scroll 

   return (
      <> 
         <div ref={myRef}>Element to scroll to</div> 
         <button onClick={executeScroll}> Click to scroll </button> 
      </>
   )
}
```

What do you think?

2024-01-25 16:04 UTC, humphd commented
Could you render the "Show Less" button in the message itself, above the content, when the text is long and expanded?

I understand it might be too complicated the way the components are currently written.

Another thought, should we wrap long message contents in an [Accordion](https://chakra-ui.com/docs/components/accordion/usage)?

2024-01-25 16:13 UTC, mingming-ma commented
@humphd The ref can be added at the bottom of the card body

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/781ef434-08c7-4619-add2-b336bd6afe9d)

I have tried locally and works good, let me commit for test.

> Another thought, should we wrap long message contents in an [Accordion](https://chakra-ui.com/docs/components/accordion/usage)?

I'll try this also and let's compare.

2024-01-25 16:14 UTC, humphd commented
At some point we might also redo the structure of how these Messages work.  I never properly designed it, just changed it as we needed to do new things.  I don't think spending time on that for no reason is useful; but if we get to the point that changes are overly complicated, we could.

2024-01-25 16:44 UTC, mingming-ma commented
Have a look at my way [Result](https://mingming-longmessages.console-overthinker-dev.pages.dev/c/chatcraft_dev/FOhhuWdlXQD_mP4AmqZtN)

I'll also try implement the suggestions:
> the render the "Show Less" button in the message
> wrap long message contents in an [Accordion](https://chakra-ui.com/docs/components/accordion/usage)

2024-01-25 17:23 UTC, mingming-ma commented
@humphd I got it! I realized I can update the `MessageBase` directly instead of passing from `HumanMessage`
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/20166b5a-e598-4753-bad0-75dce409177d)

I'm going to fix the alignment and then commit.

2024-01-25 17:25 UTC, tarasglek commented
I find the icon to go to next message to be very confusing..as it shows us going to the right.
 
 for message expansion, https://v0.chakra-ui.com/accordion icon makes more sense.
 
 Maybe we should just use that for system prompt too?

2024-01-25 17:29 UTC, tarasglek commented
I would consider changing our messages to use these accordeons or something similar if possible
<img width="638" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/701131e1-1bce-47f4-a3ef-21e3450b8ea6">

2024-01-25 17:45 UTC, mingming-ma commented
Yeah, the right arrow icon is confusing and accordion makes more sense. So now we don't need the 'Show More.../Less' button I think. And wrap long messages and system prompt in accordion. Let me implement in this way.

2024-01-26 18:34 UTC, humphd requested changes
I'm not a fan of this approach:

<img width="920" alt="Screenshot 2024-01-26 at 1 31 18 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/5472b919-66b3-49df-9bbe-c2354eb5452a">

First, the accordion header doesn't render Markdown, so we get raw text.

Second, the extra borders at the top/bottom of the accordion header are no good.

Third, the margin between the text and the down-arrow chevron needs more space.

Fourth, it's unclear what you're seeing. For example, the ```html... header doesn't indicate that there is more text available.

I think the idea of using accordion-like functionality is OK, but the ChakraUI Accordion component isn't a good fit here.

2024-01-26 18:49 UTC, mingming-ma commented
@humphd I think it will be tricky to render part of content in the header. And if we only use `Show more...` will need to click each time to see the content.
So the approach now is we need to find some toggle like behaviour component and better shows top of the content with rendered result. Let me try to find some examples.

2024-01-26 19:11 UTC, mingming-ma commented
@humphd I just thought maybe we can add the `AccordionIcon`  in the header next to `copy` to let user expand, and it will like before with rendered result, sounds good?

2024-01-26 19:17 UTC, humphd commented
It's worth a try.  We could also include the "Show more..." and "Show Less" buttons still, and they would trigger the same thing.  Best of both worlds.

2024-01-27 02:23 UTC, mingming-ma commented
@humphd I found in the mobile version the icons will not show, so I think there is no need to add the icon for now as the buttons works fine. Maybe we can leave it for other cases.

2024-01-27 05:00 UTC, WangGithub0 commented
If we still retain "Show Less" at the bottom, would it be convenient for users who have already dragged it down below?

2024-01-27 13:58 UTC, humphd requested changes
This is getting really close.  Here's my feedback on the current design.

When a message is long, and you only show the first N-lines, it's unclear that there is more content that isn't being shown:

<img width="917" alt="Screenshot 2024-01-27 at 8 40 42 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/a4f10e5a-a627-4cd8-8011-cce3c2dde4ff">

Take a look at the original issue I filed and the way Discord handles this case:

![image](https://github.com/tarasglek/chatcraft.org/assets/427398/760b41df-d104-46db-b068-60ce53a5f06a)

Here you can see that the bottom of the text element is blurred and intentionally cut-off, so as to indicate that there is more.  We don't need to do exactly what they do, but we need something to indicate that there is more text you aren't seeing.  I'd suggest we somehow change the bottom border to be jagged or blurred or something.

Another change I would make is to move the "Show More..." button to the footer when not expanded.  I think it's more intuitive to the eye to follow the content down vertically until you hit the "Show More..." button, and then it registers that you can do something.

When the user expands the content, I would put the "Show Less" button at the top and bottom (like you do now).  In other words: only put the "Show More..." in the footer, but "Show Less" should go above and below.

2024-01-27 15:08 UTC, mingming-ma commented
@WangGithub0 Absolutely! We should also have in the bottom. Thanks for the suggestion.

@humphd Couldn't agree more! The jagged/blurred idea is pretty cool and `Show more` button being bottom makes more sense. Let me implement that!

2024-01-30 18:58 UTC, humphd approved these changes
This is really fantastic.  The blur leading your eye down to a "Show More..." button is perfect.

I've left one comment about context length, but I think this is ready to land and we can iterate later as we use it.

Amazing work @mingming-ma!

2024-01-30 18:59 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                    {displaySummaryText ? summaryText || text.slice(0, 250).trim() : text}
I wonder if 250 is too short.  It means that we cut it off really fast for content returned by `/import`, and it's hard to know if you care about seeing what's inside, since you don't have enough context:

<img width="932" alt="Screenshot 2024-01-30 at 1 57 04 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/90a4ff76-33be-4483-82bc-4ffd67a1c4fa">

2024-01-30 20:39 UTC, mingming-ma commented on src/components/Message/MessageBase.tsx
> +                    {displaySummaryText ? summaryText || text.slice(0, 250).trim() : text}
True, let's try 500

2024-01-30 21:00 UTC, mingming-ma commented
@humphd 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/2eea9d06-be23-4902-8f5d-6e3d74cd01b2)
Let's try 500 workable and let me increase it later if needed. Thanks!

2024-01-30 21:04 UTC, humphd approved these changes
I think 500 works well, nice!

2024-01-30 21:08 UTC, merged