Create new Blob URL for code
tarasglek/chatcraft.org pull request #361
Opened 2024-01-24 15:09 UTC by WangGithub0

generate a new Blob URL for the code and then open that in a new tab.

<img width="799" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/140febc1-a3b9-4787-8d24-56e2a1e538e4">
<img width="627" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/024ae18a-59cf-4a51-9d42-bfc8f8066d8d">

closes #158

2024-01-24 17:17 UTC, tarasglek commented
Can you please explain the problem/feature being improved here?

2024-01-25 15:14 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +          />
Works well functionality wise!

But I noticed a cosmetic issue. The borders of the the button are inconsistent compared to others.
![ProjectNetworkDiagram](https://github.com/tarasglek/chatcraft.org/assets/78865303/74d2daa1-8a20-40d9-a36f-520338d63ab2)

Its probably because the new button has a roor node of `a`, and Chakra styles those borders in this way.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/5c46f096-0f0a-43e3-9b70-d355c9679fbf)

I am not sure if we have a direct fix for this though as I couldn't find any significant discussions for it online.

2024-01-25 15:29 UTC, humphd commented on src/components/CodeHeader.tsx
> +          />
Get rid of the `as="a"`

2024-01-25 15:35 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +          />
That was the first thing I tried. But doing that does not support `href` property. 

Should that be handled manually then?

ChatCraft says this

```tsx
<IconButton

  size="sm"

  aria-label="Open Code in New Window"

  title="Open Code in New Window"

  icon={<TbExternalLink />}

  color="gray.600"

  variant="ghost"

  onClick={() => {

    if (!isLoading) {

      window.open(url, '_blank', 'noopener,noreferrer');

    }

  }}
/>
```

2024-01-25 15:40 UTC, humphd commented on src/components/CodeHeader.tsx
> +          />
Right, I would do what the other icon buttons are doing in this header:

```jsx
            <IconButton
              size="sm"
              aria-label="Run code"
              title="Run code"
              icon={<TbRun />}
              color="gray.600"
              _dark={{ color: "gray.300" }}
              variant="ghost"
              onClick={handleRun}
              isDisabled={isLoading}
            />
```

2024-01-25 15:41 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +          />
```suggestion
          <IconButton
            size="sm"
            aria-label="Open Code in New Window"
            title="Open Code in New Window"
            icon={<TbExternalLink />}
            color="gray.600"
            variant="ghost"
            onClick={() => {
              if (!isLoading) {
                window.open(url, "_blank", "noopener,noreferrer");
              }
            }}
          />
```

2024-01-25 15:52 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +
```suggestion

  const handlePreviewCode = useCallback(() => {
    window.open(url, "_blank", "noopener,noreferrer");
  }, [url]);
```

2024-01-25 16:14 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +  }, [isLoading, code]);
```suggestion
  const handlePreviewCode = useCallback(() => {
    const url = toUrl(code);

    window.open(url, "_blank", "noopener,noreferrer");
  }, [code]);
```

2024-01-25 16:14 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +import { memo, useCallback, useMemo, type ReactNode } from "react";
```suggestion
import { memo, useCallback, type ReactNode } from "react";
```

2024-01-25 16:18 UTC, Amnish04 commented on src/components/CodeHeader.tsx
> +  }, [isLoading, code]);
I see, didn't know that. Will update

2024-01-25 17:49 UTC, rjwignar commented
> ## Deploying with  [<img alt="Cloudflare Pages" width="16" src="https://user-images.githubusercontent.com/23264/106598434-9e719e00-654f-11eb-9e59-6167043cfa01.png">](https://pages.dev)  Cloudflare Pages
> **Latest commit:**	`7330a15`
> **Status:**	 ✅  Deploy successful!
> **Preview URL:**	https://727704e5.console-overthinker-dev.pages.dev
> **Branch Preview URL:**	https://issue-158-1.console-overthinker-dev.pages.dev
> [View logs](https://dash.cloudflare.com/?to=/:account/pages/view/chatcraft-org/727704e5-b64e-43ee-9eb5-d5116c6d9bec)

I noted some observations when playing around with the CloudFlare pages build but I don't know if it is up to date with the changes made today. I'm going to checkout the branch and run it locally to confirm.

2024-01-25 20:16 UTC, rjwignar requested changes

2024-01-25 20:18 UTC, rjwignar commented on src/components/CodeHeader.tsx
> +          />
Sorry I think I accidentally submitted this review twice.
It's my first time submitting a GitHub review.

2024-01-26 03:21 UTC, rjwignar approved these changes

2024-01-26 13:59 UTC, humphd approved these changes

2024-01-26 13:59 UTC, humphd commented
@Amnish04, @Rachit1313 are we good to land this?  Anything more from you?

2024-01-26 14:02 UTC, Amnish04 commented
Looks good to me!

2024-01-26 14:06 UTC, merged