Created a react-menu component and migrated MessageBase menu to use the component
tarasglek/chatcraft.org pull request #374
Opened 2024-01-29 01:38 UTC by Rachit1313

Fixes #359

2024-01-29 13:59 UTC, humphd requested changes
Thanks for getting started on this.  Some initial feedback:

We discussed this a bit on Discord, but I wanted to circle back on it now that I've had a chance to test.  The react-menu demo page does do highlight-on-hover, why does this not support that?

<img width="342" alt="Screenshot 2024-01-29 at 8 52 08 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/48fa9d1f-4d6c-4566-b924-83ca9777b0f5">

The way you're doing submenus via props on the `Menu`, can we expose more of the react-menu API so you can do things declaratively?

```tsx
<Menu menuButton={<MenuButton>Menu</MenuButton>}>
  <MenuItem>New File</MenuItem>
  <SubMenu label="Edit">
    <MenuItem>Cut</MenuItem>
    <MenuItem>Copy</MenuItem>
    <MenuItem>Paste</MenuItem>
    <SubMenu label="Find">
      <MenuItem>Find...</MenuItem>
      <MenuItem>Find Next</MenuItem>
      <MenuItem>Find Previous</MenuItem>
    </SubMenu>
  </SubMenu>
  <MenuItem>Print...</MenuItem>
</Menu>
```

We've lost the border, which I think is important:

<img width="176" alt="Screenshot 2024-01-29 at 8 55 23 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/c92934ff-f151-421e-a714-e17332fdce8b">

I think you should use their built-in `theming` vs hard-coding colours:


theming | string |   | It sets a CSS class on the container element of menu for theming purpose. E.g., 'dark' will add szh-menu-container--theme-dark.
-- | -- | -- | --

We need things like dividers, to be able to style menu items, etc.

2024-01-29 21:12 UTC, Rachit1313 commented
> The way you're doing submenus via props on the `Menu`, can we expose more of the react-menu API so you can do things declaratively?

By this you mean creating separate components for submenu right i.e creating a saperate SubMenu.tsx?

2024-01-29 21:14 UTC, humphd commented
Right.  I would assume you'd expose the various components from react-menu in a wrapped form so they play nicely with the rest of our stuff.  So you can create `src/components/Menu/*` and put all the different things we want in there.  I'm not sure we need to expose everything at first, but we should have all the common stuff: menu, submenu, menuitems, divider, etc.

2024-01-29 21:56 UTC, Rachit1313 commented
> Right. I would assume you'd expose the various components from react-menu in a wrapped form so they play nicely with the rest of our stuff. So you can create `src/components/Menu/*` and put all the different things we want in there. I'm not sure we need to expose everything at first, but we should have all the common stuff: menu, submenu, menuitems, divider, etc.

Okay., For the duplicate chat until message 
<img width="701" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/ffa4d2af-2fc3-4a81-bfde-ec96009b92db">
This is the current functionality, but the react-menu's MenuItem does not support as or to prop. Is that okay if I handle it with this?
<img width="482" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/eeb27a20-26b0-4a39-be07-b8205804e383">

2024-01-29 22:54 UTC, humphd commented
I think you can do it, see https://github.com/szhsin/react-menu/issues/248#issuecomment-910261822

2024-01-30 19:26 UTC, Rachit1313 commented
> I think you should use their built-in `theming` vs hard-coding colours:
> 
> theming	string	 	It sets a CSS class on the container element of menu for theming purpose. E.g., 'dark' will add szh-menu-container--theme-dark.

I got all the components ready and updated in the MessageBase class declaratively. I need someone's help with css part. I am stuck on that and not able to match the theming perfectly.

2024-01-30 19:27 UTC, humphd commented
@Amnish04 is good at CSS.  Can you help?

2024-01-31 00:16 UTC, Amnish04 commented
I've been looking at this PR for a while, and one thing I noticed **except** theming is that we have a weird **hover resize** on messages that did not exist before.
![MessagesHoverResize](https://github.com/tarasglek/chatcraft.org/assets/78865303/13a4c4ae-f232-4cbc-96ad-3c3dd0b03c80)

I think that's because the `MenuButton` from [React-Menu](https://szhsin.github.io/react-menu#menu-button) is a smaller size than buttons from **Chakra**, and when the appear they resize the container div pushing stuff down.

We can probably use a Chakra [IconButton](https://chakra-ui.com/docs/components/icon-button/usage) from before to fix this issue.

2024-01-31 00:19 UTC, Amnish04 requested changes

2024-01-31 00:19 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +        }
```suggestion
        menuButton={
          <IconButton
            aria-label="Message Menu"
            icon={<TbDots />}
            variant="ghost"
            isDisabled={isLoading}
          ></IconButton>
        }
```

This fixes the issue I mentioned [above](https://github.com/tarasglek/chatcraft.org/pull/374#issuecomment-1918133731)

2024-01-31 00:36 UTC, Amnish04 requested changes
Also added an optional `isLoading` property as I noticed previously `MenuButton` was disabled when loading.

https://github.com/tarasglek/chatcraft.org/blob/9307f3a6a9f3f2ce6045ea7016cb2dce0ef4c35c/src/components/Message/MessageBase.tsx#L299

2024-01-31 00:36 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +import { Menu as ReactMenu, MenuButton } from "@szhsin/react-menu"; // Alias for the imported Menu
```suggestion
import { Menu as ReactMenu } from "@szhsin/react-menu"; // Alias for the imported Menu
```

2024-01-31 00:36 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +  const menuButtonBg = useColorModeValue(theme.colors.gray[100], theme.colors.gray[700]);
```suggestion
```

2024-01-31 00:36 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +  children: React.ReactNode;
```suggestion
  children: React.ReactNode;
  isLoading?: boolean;
```

2024-01-31 00:36 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +const Menu: React.FC<MenuProps> = ({ children }) => {
```suggestion
const Menu: React.FC<MenuProps> = ({ children, isLoading }) => {
```

2024-01-31 00:36 UTC, Amnish04 commented on src/components/Message/MessageBase.tsx
>                <Menu>
```suggestion
              <Menu isLoading={isLoading}>
```

2024-01-31 01:04 UTC, Amnish04 requested changes
I think your custom styling for `MenuItem` was **overriding** the **hover effect** for menu items.
These changes fix that.
![HoverHighlight](https://github.com/tarasglek/chatcraft.org/assets/78865303/c2d39301-2c94-4185-a185-c7f29d5e467f)


Also I renamed `MenuItem` **alias** from `ReactMenuMenuItem` to `ReactMenuItem` if that's okay :)

```
import { MenuItem as ReactMenuItem } from "@szhsin/react-menu";
```

2024-01-31 01:04 UTC, Amnish04 commented on src/components/Menu/MenuItem.tsx
> +import { MenuItem as ReactMenuMenuItem } from "@szhsin/react-menu";
```suggestion
import { MenuItem as ReactMenuItem } from "@szhsin/react-menu";
```

2024-01-31 01:14 UTC, Amnish04 requested changes
I am not sure if these styles are doing anything we need. Looked better to me after removing these.

Please let me know if I am missing something

2024-01-31 01:14 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +  const menuListBorderColor = useColorModeValue(theme.colors.gray[200], theme.colors.gray[600]);
```suggestion
```

2024-01-31 01:14 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +        }}
```suggestion
```

2024-01-31 01:17 UTC, Amnish04 commented
@Rachit1313 I would suggest using this option to add changes to batch instead of **commit suggestion**, so there's only one commit and no CI errors :)
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/9508c78e-d896-4ede-9053-4130165a58e9)

2024-01-31 01:18 UTC, Rachit1313 commented
> @Rachit1313 I would suggest using this option to add changes to batch instead of **commit suggestion**, so there's only one commit and no CI fails :) ![image](https://private-user-images.githubusercontent.com/78865303/301007816-9508c78e-d896-4ede-9053-4130165a58e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQxNzAsIm5iZiI6MTcwNjY2Mzg3MCwicGF0aCI6Ii83ODg2NTMwMy8zMDEwMDc4MTYtOTUwOGM3OGUtZDg5Ni00ZWRlLTkwNTMtNDEzMDE2NWE1OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjc0Y2Y2Zjg1NzkyNTgzOWQ4MzU2ODUwMGJkNmI5Y2Q3NTRmMmNkMTU0Y2RjNzdlZDkxODgxMmExMTBhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-2Kz8UsD5oPPUwD5YbnXYPpAD_PTyhhVj56C2D5YuU)

Thanks and
<img width="894" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/0d9f7ca6-85de-4edf-a210-7c9566144b98">

After checking your changes I see that its good in the light mode but we need to do something for the dark mode.

2024-01-31 01:19 UTC, Rachit1313 commented
> @Rachit1313 I would suggest using this option to add changes to batch instead of **commit suggestion**, so there's only one commit and no CI fails :) ![image](https://private-user-images.githubusercontent.com/78865303/301007816-9508c78e-d896-4ede-9053-4130165a58e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQyMTgsIm5iZiI6MTcwNjY2MzkxOCwicGF0aCI6Ii83ODg2NTMwMy8zMDEwMDc4MTYtOTUwOGM3OGUtZDg5Ni00ZWRlLTkwNTMtNDEzMDE2NWE1OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzY0Njg4ZDFmZjE5MTZkN2M1NjBlZTU4MjM1MWZjNjI1NTE3MTAxNjdjNjBmM2U2N2IxZTgxMzFlMTNmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LweMrWEt4p_zGp87x8GZz35u7R0TcD9lz4Ohw9N7PkA)

btw the add suggestion to batch is disabled for me.

2024-01-31 01:21 UTC, Amnish04 commented
> > @Rachit1313 I would suggest using this option to add changes to batch instead of **commit suggestion**, so there's only one commit and no CI fails :) ![image](https://private-user-images.githubusercontent.com/78865303/301007816-9508c78e-d896-4ede-9053-4130165a58e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQyMTgsIm5iZiI6MTcwNjY2MzkxOCwicGF0aCI6Ii83ODg2NTMwMy8zMDEwMDc4MTYtOTUwOGM3OGUtZDg5Ni00ZWRlLTkwNTMtNDEzMDE2NWE1OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzY0Njg4ZDFmZjE5MTZkN2M1NjBlZTU4MjM1MWZjNjI1NTE3MTAxNjdjNjBmM2U2N2IxZTgxMzFlMTNmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LweMrWEt4p_zGp87x8GZz35u7R0TcD9lz4Ohw9N7PkA)
> 
> btw the add suggestion to batch is disabled for me.

I think you need to go to the Files tab for that

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/28d54545-11bc-4204-9f1f-6cce72ed642e)

2024-01-31 01:24 UTC, Amnish04 commented
> > @Rachit1313 I would suggest using this option to add changes to batch instead of **commit suggestion**, so there's only one commit and no CI fails :) ![image](https://private-user-images.githubusercontent.com/78865303/301007816-9508c78e-d896-4ede-9053-4130165a58e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQxNzAsIm5iZiI6MTcwNjY2Mzg3MCwicGF0aCI6Ii83ODg2NTMwMy8zMDEwMDc4MTYtOTUwOGM3OGUtZDg5Ni00ZWRlLTkwNTMtNDEzMDE2NWE1OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjc0Y2Y2Zjg1NzkyNTgzOWQ4MzU2ODUwMGJkNmI5Y2Q3NTRmMmNkMTU0Y2RjNzdlZDkxODgxMmExMTBhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-2Kz8UsD5oPPUwD5YbnXYPpAD_PTyhhVj56C2D5YuU)
> 
> Thanks and <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/58596563/301007985-0d9f7ca6-85de-4edf-a210-7c9566144b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjQzNjYsIm5iZiI6MTcwNjY2NDA2NiwicGF0aCI6Ii81ODU5NjU2My8zMDEwMDc5ODUtMGQ5ZjdjYTYtODVkZS00ZWRmLWEyMTAtN2M5NTY2MTQ0Yjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYWI1MGRhZTQwZGVlNmM0MjA4ZmNjN2E3MzAzYmMyM2IxOWZkYTI3ODBjY2JiM2ZmYWU4MGQxYzgyZDdhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNWzxFPodWtpOKVG3h6KC5SB2ub9QXm60_n2XTMo4AU">
> 
> After checking your changes I see that its good in the light mode but we need to do something for the dark mode.

I think that's something related to [theming](https://szhsin.github.io/react-menu/docs) property. Still looking into it.

2024-01-31 01:31 UTC, Amnish04 requested changes
Adding this property gives similar open close animation like we had with **Chakra**

![OpenCloseTransition](https://github.com/tarasglek/chatcraft.org/assets/78865303/52cde118-2ee9-493b-8f3f-a3feee0458ea)


This comes with `@szhsin/react-menu/dist/transitions/slide.css`

2024-01-31 01:31 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +        menuButton={
```suggestion
        transition={true}
        menuButton={
```

2024-01-31 01:31 UTC, Amnish04 commented on src/components/Menu/Menu.tsx
> +import "@szhsin/react-menu/dist/index.css";
```suggestion
import "@szhsin/react-menu/dist/index.css";
import "@szhsin/react-menu/dist/transitions/slide.css";
```

2024-01-31 01:34 UTC, humphd commented
@Amnish04 @Rachit1313 another approach you can take to doing something like this is for each of you to push/pull commits to the branch.

This approach requires a bit of care, but is a great way to work together.  Before you do it, ask the other person if they are OK with you pushing commits.

Then, check out their code:

```
# Assuming tarasgleck/chatcraft.org is your upstream remote
git fetch remote
# Get the branch for this PR
git checkout react-menu
# do your changes
git add ...
git commit -m "Fixing ..."
git push upstream react-menu
```

Now, the key here is to always `git pull upstream react-menu` before you start doing more work, or you risk getting out of sync.

If that happens, you can do:

```
git pull --rebase upstream react-menu
```

You don't have to work this way, it's a bit more advanced and both parties need to feel comfortable with git to do it.  But FYI, you can, since we're working on a branch in the same repo.

Also, I'm really glad to see you to helping each other get this landed.  Amazing work!

2024-01-31 01:48 UTC, Amnish04 commented
> @Amnish04 @Rachit1313 another approach you can take to doing something like this is for each of you to push/pull commits to the branch.
> 
> This approach requires a bit of care, but is a great way to work together. Before you do it, ask the other person if they are OK with you pushing commits.
> 
> Then, check out their code:
> 
> ```
> # Assuming tarasgleck/chatcraft.org is your upstream remote
> git fetch remote
> # Get the branch for this PR
> git checkout react-menu
> # do your changes
> git add ...
> git commit -m "Fixing ..."
> git push upstream react-menu
> ```
> 
> Now, the key here is to always `git pull upstream react-menu` before you start doing more work, or you risk getting out of sync.
> 
> If that happens, you can do:
> 
> ```
> git pull --rebase upstream react-menu
> ```
> 
> You don't have to work this way, it's a bit more advanced and both parties need to feel comfortable with git to do it. But FYI, you can, since we're working on a branch in the same repo.
> 
> Also, I'm really glad to see you to helping each other get this landed. Amazing work!

Thanks for sharing! I was having an itch to push directly from the beginning, but wasn't sure if that's acceptable 😝

@Rachit1313 If it's okay with you, can I push changes directly here? We can always reset if things go in the wrong direction.

2024-01-31 03:36 UTC, Amnish04 commented
Just pushed the following changes:

1. Switch to dark mode theme based on `colorMode` state. 
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/09601b92-27de-4d56-806f-877a2b981f7d)
2. A Menu open/close transition.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/9088af8d-5867-41fa-83b8-5d2440081c11)
3. Added a `Menu.css` file to adapt the **React-Menu** theming to align with Chakra colors.
```css
/*
  Colors from official Chakra docs
  https://chakra-ui-git-fix-typescript-autocomplete.chakra-ui.vercel.app/docs/theming/theme#gray

  Classes from official @szhsin/react-menu docs
  https://szhsin.github.io/react-menu/style-guide
*/
.szh-menu-container {
  /* Light Mode */
  --chakra-gray-100: #edf2f7;
  --chakra-gray-200: #e2e8f0;

  /* Dark Mode */
  --chakra-gray-500: #718096;
  --chakra-gray-600: #4a5568;
  --chakra-gray-700: #2d3748;
}
...
...
```
4. Some [block padding](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block) adds attention to detail. 
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/4c5c1d1f-bcd8-4441-aa9e-da08543cf3ac)

@Rachit1313 @humphd 
Please let me know if its good so far.

2024-01-31 14:55 UTC, humphd requested changes
@Rachit1313 @Amnish04 I think this is really looking great, and we're on track to have it in for 1.1.  What a huge improvement over what we have now!

@Rachit1313 please see my comments below and let's get this fixed up to land before Friday's deadline.  If you need further help from @Amnish04, please let him know.

2024-01-31 14:55 UTC, humphd commented on src/components/Menu/Menu.tsx
> +      <ReactMenu // Use the alias here
Get rid of this comment.

2024-01-31 14:55 UTC, humphd commented on src/components/Menu/Menu.tsx
> +        menuButton={
Is this still necessary?  I see `transition={true}` below.

2024-01-31 14:55 UTC, humphd commented on src/components/Menu/MenuDivider.tsx
> +      // Add any additional styles you want to apply to the divider
Get rid of this

2024-01-31 14:55 UTC, humphd commented on src/components/Menu/MenuDivider.tsx
> +      my={1} // Adjust margin as needed
Same, drop this comment.

2024-01-31 14:55 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +import Menu from "../Menu/Menu"; // Assuming Menu is the new component
Can we create `../Menu/index.tsx` and re-export all of the different files?  A nicer API would be:

```ts
import { Menu, MenuItem, SubMenu, MenuDivider } from '../Menu';
```

Also, drop these comments.

2024-01-31 14:55 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                    onClick={() => {}} // You can leave this empty or handle additional logic if needed
What is the purpose of `onClick` here?

2024-01-31 14:55 UTC, humphd commented on src/components/SubMenu.css
> +.szh-menu__submenu {
Let's move these `.css` files related to the menu into `src/componenents/Menu/*`

2024-01-31 15:51 UTC, Rachit1313 commented on src/components/Message/MessageBase.tsx
> +                    onClick={() => {}} // You can leave this empty or handle additional logic if needed
nothing, its just I set onClick as a required prop so had to leave it empty.  If you want I can make it optional and remove this.

2024-01-31 18:37 UTC, humphd approved these changes
I think this is excellent. I have two questions, but neither is a blocker for me.  Just fix or file issues to deal with it later.

Amazing work.

2024-01-31 18:37 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +import React, {
Why are we adding `React` here?

2024-01-31 18:37 UTC, humphd commented on src/components/Message/MessageBase.tsx
> -                    <MenuItem onClick={() => onDeleteBeforeClick()} color="red.400">
We've lost `color="red.400"` for these, can you add that back, either in this PR or a follow-up?

2024-01-31 18:40 UTC, Rachit1313 commented on src/components/Message/MessageBase.tsx
> +import React, {
Yeah I see. its not getting used anywhere so looks like might be auto imported while making some changes. I'll just remove it.

2024-01-31 19:08 UTC, Rachit1313 commented
> I think this is excellent. I have two questions, but neither is a blocker for me. Just fix or file issues to deal with it later.
> 
> Amazing work.

Made the changes.

2024-02-01 01:35 UTC, Amnish04 commented on src/components/Menu/Menu.css
> +}
Can we define a css variable for this?

```css
--chakra-red-400: #fc8181;
```

2024-02-01 01:37 UTC, Amnish04 commented on src/components/Menu/Menu.css
> +}
```suggestion
```

I don't think we need to have this style if we're using same color in both cases

2024-02-01 01:45 UTC, Amnish04 requested changes
@Rachit1313 I've left some comments for minor changes

2024-02-01 01:51 UTC, Amnish04 commented
Other than that, I also observed a couple of unexpected behaviours.

**1.** When opening submenu, the view automatically exhibits some weird scroll.
![NewScrollBug](https://github.com/tarasglek/chatcraft.org/assets/78865303/a28dde0e-d41a-4b4c-974c-8c2af6f845e5)

I don't think that was happening before.

**2.** When the sidebar is open or on a lower width, opening the menu makes a horizontal scrollbar appear.
![ScrollbarAppears](https://github.com/tarasglek/chatcraft.org/assets/78865303/7f8fa02b-da98-4652-bb21-9a08b5902b4b)

I think the **second** issue can be fixed in a follow up.

Should we try to address the first one now?

2024-02-01 04:26 UTC, humphd commented
Yes, that scroll bug is not good.  Let's get that sorted before we merge.

2024-02-01 14:03 UTC, WangGithub0 commented on src/components/Menu/Menu.tsx
> +          ></IconButton>
If a component doesn't have any children, you can use a self-closing tag 
  <IconButton
            aria-label="Message Menu"
            icon={<TbDots />}
            variant="ghost"
            isDisabled={isLoading}
          />

2024-02-01 16:14 UTC, Rachit1313 commented
> Yes, that scroll bug is not good. Let's get that sorted before we merge.

@Amnish04 @humphd , For me I can't see the scroll to top and the scroll bar, both issues. Can you please confirm?

2024-02-01 16:16 UTC, Rachit1313 commented
https://github.com/tarasglek/chatcraft.org/assets/58596563/574e2397-a8a3-4295-8739-1cbc1d5ba39f

2024-02-01 18:35 UTC, Amnish04 commented
@Rachit1313 The scroll bug I mentioned isn't happening for me either, it was only limited to that particular browser tab I was testing in.
<img width="791" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/bb8af485-f4df-4e43-be2c-d2714ceea550">

But the second one is still there for me. Not sure what's up.
![Feb-01-2024 13-32-47](https://github.com/tarasglek/chatcraft.org/assets/78865303/b6feea45-ea10-4f79-a416-2e2d80807e59)

2024-02-01 18:59 UTC, Rachit1313 commented
> @Rachit1313 The scroll bug I mentioned isn't happening for me either, it was only limited to that particular browser tab I was testing in.
> 
> <img width="791" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/bb8af485-f4df-4e43-be2c-d2714ceea550">
> 
> 
> 
> But the second one is still there for me. Not sure what's up.
> 
> ![Feb-01-2024 13-32-47](https://github.com/tarasglek/chatcraft.org/assets/78865303/b6feea45-ea10-4f79-a416-2e2d80807e59)
> 
> 

Can you check if it shows you this even in cloudflare preview Url?

2024-02-01 19:05 UTC, Amnish04 commented
@Rachit1313 Just retested, I see same behavior there as well.
<img width="1506" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/fa7ef0f0-68d9-40a7-866e-88e870f8328e">


@humphd Is this happening for you as well, or is it just me?

2024-02-02 00:17 UTC, humphd commented
> @humphd Is this happening for you as well, or is it just me?

I've tested on macOS with Chrome and Safari, and I can't reproduce this bug.  It might be Windows only?  Or specific to the browser you are using?

2024-02-02 17:19 UTC, Amnish04 commented
> > @humphd Is this happening for you as well, or is it just me?
> 
> I've tested on macOS with Chrome and Safari, and I can't reproduce this bug. It might be Windows only? Or specific to the browser you are using?

Not sure why its only happening for me then. I tested in both **Windows** and **Mac** - **Firefox** and **Chrome**.

Maybe we have different scaling settings? I have mine set to 100%.

In any case, if it's not happening for anyone else we should be good to land this for now.
And open a follow up if people face issues.

2024-02-02 17:20 UTC, humphd commented
@Amnish04 agreed.  I think if you hit it, it's possible the bug is there and subtle.  Let's land this and improve later on.

2024-02-02 21:40 UTC, Rachit1313 commented
> @Amnish04 agreed. I think if you hit it, it's possible the bug is there and subtle. Let's land this and improve later on.

Are we good to merge this for release 0.1, will work as another issue if anything comes up.

2024-02-02 22:58 UTC, Amnish04 approved these changes

2024-02-02 22:59 UTC, merged

2024-02-03 22:31 UTC, tarasglek commented
great fix, thank you @Amnish04

2024-02-04 13:50 UTC, humphd commented
> great fix, thank you @Amnish04

Great team effort by @Rachit1313 and @Amnish04.  Love to see the collaboration here.