Add a command to show list of supported commands
tarasglek/chatcraft.org pull request #396
Opened 2024-02-01 21:54 UTC by Amnish04

Currently, when a user enters an `unsupported command`, a **toast message** is displayed suggesting the commands was invalid.

I have added a new command called `/commands` that allows users to **quickly** refer to the list of commands instead of the general `/help` command.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/50368c74-f86c-4931-84f5-600d46b01033)

The list of commands is also displayed when an invalid command is entered instead of showing the toast message.

This fixes #356

2024-02-02 02:02 UTC, rjwignar requested changes
The feature works, and the code looks great!
I've added some general comments but the only change I require before approving this is **updating the Commands** section of the `helpText` constant in `src/components/Message/AppMessage/Help.tsx` to include a description for your new command.

2024-02-02 03:11 UTC, tarasglek commented on src/Chat/ChatBase.tsx
> +              title: `Unknown Command`,
Why is /commands better than showing /help with all commands?

We should show the command that we failed to identify. I get a lot of errors from chatcraft when i try to paste /something and it's not immediately obvious without an indicator of what i typed

2024-02-02 03:18 UTC, mingming-ma commented on src/Chat/ChatBase.tsx
> +              title: `Unknown Command`,
it reminds me of 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/918cd7fe-dc76-4540-b5f6-39726c28173b)

2024-02-02 04:01 UTC, rjwignar commented on src/Chat/ChatBase.tsx
> +              title: `Unknown Command`,
> We should show the command that we failed to identify. I get a lot of errors from chatcraft when i try to paste /something and it's not immediately obvious without an indicator of what i typed

That's a good point.
Would it be better to have that indicated in `/commands` or inside the original Toast error message we currently have?
Something like below?

**/commands**
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/b13294af-a28a-4fa0-b44d-82bc531b0443)


**Toast Message:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/f0336955-541f-4e57-b654-3c902c7dda6b)

2024-02-02 17:23 UTC, Amnish04 commented on src/Chat/ChatBase.tsx
> +            });
That is just a fallback if for some reason, the execution of `/commands` command runs into an exception (which I don't think should ever happen).

Should we remove it?

2024-02-02 17:24 UTC, Amnish04 commented on src/components/Message/AppMessage/Help.tsx
> +| /import&nbsp;<url> | Loads the provided URL and imports the text. Where possible, ChatCraft will try to get raw text vs. HTML from sites like GitHub. NOTE: to prevent abuse, you must be logged into
Sure, I missed that. Thanks for noticing

2024-02-02 17:24 UTC, humphd commented on src/Chat/ChatBase.tsx
> +            });
"Should never happen" is not the same as "Is impossible."  I'd leave it so we don't crash.  If it never shows the error toast, that's fine.

2024-02-02 17:33 UTC, Amnish04 commented on src/Chat/ChatBase.tsx
> +              title: `Unknown Command`,
@tarasglek The `/help` command displays all the general help information related to ChatCraft. So it gets a little harder for user to **skim** through and **find** the **supported** commands.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/680302a2-a4f7-41bd-b099-9bde2a529615)

Using `/commands`, it just becomes a little more convenient to look them up.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/376cadfb-77e5-457a-a102-a8fd1d193f1e)

But you're right, we should also show the command that we typed as its not even added to the chat.

@rjwignar I think we should add it to the toast message?

@mingming-ma I like the idea of suggesting a similar command. Should we have a separate issue for that?

2024-02-02 17:42 UTC, Amnish04 commented
Just pushed some changes. I've restored the toast message for `Unknown Command` and now it also displays what command was typed. The list of commands is also displayed.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/e5f1f5a9-1d78-49ba-88a4-ee55f1d63f72)

2024-02-02 17:45 UTC, Amnish04 commented on src/Chat/ChatBase.tsx
> +            });
You're right. I did not remove it, but changed the wording to be same as if it happened with any other command since the `Unknown Command` toast is always shown now
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/9c5d53bc-f99a-46bf-852d-dd360e382652)

2024-02-02 20:08 UTC, rjwignar approved these changes
I like how the toast message displays the unrecognized command now.

With these changes, ChatCraft will now **display both** a Toast error message print the list of commands (by invoking `/commands`) when an unrecognized command is sent:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/e4f10e8b-7795-4264-b167-5ff9561eebb3).

These changes have my approval, but I'd like to see how others feel about both being displayed. @humphd, @mingming-ma, what are your thoughts on this?

2024-02-02 22:02 UTC, mingming-ma reviewed
For the most similar commands, I think it might be not so helpful if we have all commands displayed. I think we can import the `commandsHelpText` to `Help` so when new commands coming in we don't need to change twice

2024-02-02 22:26 UTC, mingming-ma commented on src/components/Message/AppMessage/Help.tsx
>  | /summary&nbsp;[max-length] | Uses ChatGPT to create a summary of the current chat. Optionally takes a maximum word length (defaults to 500). |
```suggestion
${commandsHelpText}
```

2024-02-02 22:50 UTC, Amnish04 commented on src/components/Message/AppMessage/Help.tsx
>  | /summary&nbsp;[max-length] | Uses ChatGPT to create a summary of the current chat. Optionally takes a maximum word length (defaults to 500). |
@mingming-ma Agreed, I'll commit that.

2024-02-03 16:23 UTC, tarasglek commented
I don't think we need to toast here, how about we show the error inline in the commands help message reply?

2024-02-05 18:49 UTC, Amnish04 commented
> I don't think we need to toast here, how about we show the error inline in the commands help message reply?

Yes, I think that makes more sense.

2024-02-07 05:34 UTC, Amnish04 commented
@tarasglek Just pushed the changes.

Any invalid command now shows up inline with the commands help text.

Here are the scenarios:

**1. /typo**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/8d5e425f-826a-40c3-80ca-4eafb6ca7f9a)

**2. /commands**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/6984ddc7-58ea-48d8-9a8e-d9377cfe760b)

**3. /commands query-some-command**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/93e468c9-88cb-420d-a7fd-4bda2d1946f2)

I am now allowing the `CommandsHelpCommand` to accept `arguments` which we can later use to implement a **suggest closest command** feature based on @mingming-ma's suggestion.

My only concern is if I could make my approach simpler.

2024-02-07 16:06 UTC, tarasglek commented
I think this is good for me

2024-02-07 17:26 UTC, Amnish04 commented
@mingming-ma @rjwignar If you guys also think this is good, should I merge?

2024-02-07 20:11 UTC, mingming-ma commented
lgtm

2024-02-07 21:05 UTC, rjwignar approved these changes
Changes look great! LGTM

2024-02-07 21:32 UTC, Amnish04 commented
Thanks for reviewing everyone!

2024-02-07 21:32 UTC, merged