Updated Delete section to use SubMenu
tarasglek/chatcraft.org pull request #406
Opened 2024-02-05 19:52 UTC by Rachit1313

Fixes #399 

Changes Made:

- Updated SubMenu component to accept className for Chakra Red
- Updated MessageBase to display delete options in a different SubMenu

2024-02-05 21:02 UTC, humphd commented on src/components/Menu/SubMenu.tsx
> +  className?: string;
See my change in https://github.com/tarasglek/chatcraft.org/pull/402, which does this in a different way.

2024-02-06 00:41 UTC, humphd requested changes

2024-02-06 08:37 UTC, tarasglek commented
This is good, but please match add icons to menu.
<img width="426" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/1d64b07a-45b4-49a7-9608-fcbc8db2716e">

2024-02-06 14:17 UTC, humphd commented
> please match add icons to menu items.

So you're saying, use the same icons beside these labels as what we use in the toolbar (copy, edit, delete).  Good idea.

2024-02-06 16:41 UTC, Rachit1313 commented
> > please match add icons to menu items.
> 
> So you're saying, use the same icons beside these labels as what we use in the toolbar (copy, edit, delete). Good idea.

Sorry, I didn't quite get this one. Could you please elaborate?

2024-02-06 20:45 UTC, humphd commented
<img width="437" alt="Screenshot 2024-02-06 at 3 44 19 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/3acf5410-3cb2-4b86-b223-3e8be262849f">

He wants the same icons shown in the menu as we use message header, so it's clear what they mean.

2024-02-06 20:54 UTC, Rachit1313 commented
> <img alt="Screenshot 2024-02-06 at 3 44 19 PM" width="437" src="https://private-user-images.githubusercontent.com/427398/302771907-3acf5410-3cb2-4b86-b223-3e8be262849f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTMxMDYsIm5iZiI6MTcwNzI1MjgwNiwicGF0aCI6Ii80MjczOTgvMzAyNzcxOTA3LTNhY2Y1NDEwLTNjYjItNGI4Ni1iMjIzLTNlOGJlMjYyODQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQyMDUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWRjMDhiZTc4Y2NjZGY0ZjQyZWJhZDIzZWI5ODg0YTJmZTQ2MTk5Y2FkMjhjN2Y4NDBjZDk2OTE4ZWVmYWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9k4x9KgyBby9SVzBcnM8Zc0Czdg_YYKg_xJVsFtdoVQ">
> He wants the same icons shown in the menu as we use message header, so it's clear what they mean.

so just the icons, or icons with the text ?

2024-02-06 21:32 UTC, humphd commented
Icons with text

2024-02-07 04:30 UTC, Rachit1313 commented
@humphd , we have the icons set for edit and copy, do we also need them for delete as its already red?

2024-02-07 12:53 UTC, humphd commented
Delete refers to `Delete Message` so maybe add it to that menu item only.

2024-02-07 14:59 UTC, tarasglek commented
> > He wants the same icons shown in the menu as we use message header, so it's clear what they mean.
> 
> so just the icons, or icons with the text ?

I suspect on mobile we should only show icons

Can you check if this renders ok on iphone?

2024-02-08 22:17 UTC, Rachit1313 commented
> > > He wants the same icons shown in the menu as we use message header, so it's clear what they mean.
> > 
> > 
> > so just the icons, or icons with the text ?
> 
> I suspect on mobile we should only show icons
> 
> Can you check if this renders ok on iphone?

I think even the icons with text render properly on iphone. Screenshot attached.
![IMG_4377](https://github.com/tarasglek/chatcraft.org/assets/58596563/cbf1673d-860b-44a3-8392-eda55c61a6bd)
![IMG_4376](https://github.com/tarasglek/chatcraft.org/assets/58596563/d6449054-8b32-443b-b549-7a0bbbc2c949)

2024-02-08 23:12 UTC, humphd requested changes

2024-02-08 23:12 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                            icon={<TbTrash />}
This icon should be red

2024-02-08 23:25 UTC, humphd approved these changes
Rebase this and it's good to go.

2024-02-08 23:25 UTC, humphd commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
FYI, you've added an unrelated change here.

I think it's fin in this case, because VSCode is determined to make this change (I keep undoing it locally).  But it's bad form to sneak unrelated changes into a fix.

2024-02-08 23:25 UTC, humphd commented on src/components/Menu/MenuItem.tsx
> +const MenuItem: React.FC<MenuItemProps> = (props) => {
You should rebase on `main`, to get the changes I just merged related to this.

2024-02-09 04:48 UTC, merged