Fix: Don't use Show More... for final message
tarasglek/chatcraft.org pull request #412
Opened 2024-02-06 19:12 UTC by mingming-ma

Fixes #394 

## Explanation 

Currently all long messages are collapsed, (`isOpen` is `false` by default)

This update adds a `useEffect` to detect message status, if it is the final message and not system message, it toggles the `Show More...` button for users to have a better view.

The `onDeleteAfterClick` property is `undefined` when it is the final message and so can be used for the check.

2024-02-06 20:42 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +  }, []);
Why not include your dependencies here?  `onDeleteAfterClick`, `isOpen`, etc?

2024-02-06 21:51 UTC, mingming-ma commented on src/components/Message/MessageBase.tsx
> +  }, []);
When I write that code I think we can run the useEffect only once as there is only one final message. 

After double checking the dependencies here, I find we should not include `isOpen` in the dependencies because the `onToggle` will change the `isOpen` status and so will call `onToggle` again, so user could not collapse the final message. 

`onDeleteAfterClick ` can be added as user may delete the final message, and the message on top of that if it's a collapsed one, it will then auto expanded. How do you think about this behaviour?

2024-02-06 21:52 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +  }, []);
Sounds good, let's try it.

2024-02-06 22:13 UTC, humphd requested changes

2024-02-06 22:13 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +  }, [onDeleteAfterClick]);
I don't love using `onDeleteAfterClick` to mean "is last message," since we actually have this info:

https://github.com/tarasglek/chatcraft.org/blob/ee9e42b936c5e503f9650f59fac82d125890b874/src/components/MessagesView.tsx#L92

Let's add a new prop to `MessageBase` that lets you know if this is the lastMessage or not, based on that.  Then use it here.

2024-02-07 01:25 UTC, humphd approved these changes
I love how you always include example, shared chats.  This is great.  Thanks for doing a proper fix.

2024-02-07 01:25 UTC, merged