Query available models to determine TTS support
tarasglek/chatcraft.org pull request #420
Opened 2024-02-07 19:21 UTC by Amnish04

I am now querying the available models to determine if tts is supported rather than just checking if we are using openai.

For this, I have modified the `queryModels` function to accept a custom predicate for filtering purposes. I have added the previously used predicate as default value so other placed don't break.
```ts
filterPredicate: (model: ChatCraftModel) => boolean = (model) =>
    !usingOfficialOpenAI() || model.id.includes("gpt")
```

and `isTtsSupported` now looks like this

```ts
export async function isTtsSupported() {
  const { apiKey } = getSettings();
  if (!apiKey) {
    throw new Error("Missing API Key");
  }

  return (
    (
      await queryModels(apiKey, (model: ChatCraftModel) => {
        return model.id.includes("tts");
      })
    )?.length > 0
  );
}
```

This closes #387

2024-02-07 21:28 UTC, Amnish04 commented
> lgtm...though I think .filter applied to results is always better than having every func support filter functionality, but pre-existing code already set the usage pattern

Yes, do you mean we shouldn't filter inside the function?

2024-02-08 02:18 UTC, humphd requested changes

2024-02-08 02:18 UTC, humphd commented on src/lib/ai.ts
> +      .filter((model: any) => filterPredicate(model))
This is overly clever.  I'd prefer to see you filter the results on line 462 below.  You can do stuff like this, but you risk creating code that is harder to maintain.

2024-02-08 06:26 UTC, tarasglek commented
> > lgtm...though I think .filter applied to results is always better than having every func support filter functionality, but pre-existing code already set the usage pattern
> 
> Yes, do you mean we shouldn't filter inside the function?

yes. queryModels().filter() is much better than queryModels(filterCallback) as .filter is standard JS

2024-02-08 18:14 UTC, Amnish04 commented
@humphd @tarasglek Agreed, I also don't like that style.

Just removed default filtering from `queryModels` so all available models are returned (from `useModels` as well). Any model filtering is done by consumers now.

Is that what we were expecting?

2024-02-08 19:10 UTC, humphd requested changes

2024-02-08 19:10 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [isTTSSupported, setIsTTSSupported] = useState(false);
`isTtsSupported` and `isTTSSupported` is not a good idea.

Also, can you not use the `models` from the `useModels()` hook in here?  Ideally you should use our hook for getting that info.

2024-02-09 01:52 UTC, Amnish04 commented on src/lib/ai.ts
> + * @param filterPredicate A function used to filter the array of returned models
Right I forgot about that. Just removed

2024-02-09 01:53 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [isTTSSupported, setIsTTSSupported] = useState(false);
I wasn't using that initially because it was always filtering to gpt models. But now we can definitely use it. Thanks for pointing out!

2024-02-09 01:54 UTC, Amnish04 commented
@humphd Just pushed the requested changes. I am using the `useModels` hook in components now.

2024-02-09 01:59 UTC, humphd approved these changes
Looks good.  A few optimizations you can make.

2024-02-09 01:59 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  function isTtsSupported() {
```tsx
const isTtsSupported = useMemo(() =>
  models.filter((model) => model.id.includes("tts"))?.length > 0,
  [models]
);
```

2024-02-09 01:59 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  function isTtsSupported() {
Same here, you should be able to cache this and only re-calculate on models changing.

2024-02-09 02:07 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +  function isTtsSupported() {
That's right! Just pushed the changes.

2024-02-09 02:07 UTC, humphd approved these changes
Nice

2024-02-09 02:11 UTC, Amnish04 commented
Thanks for helping. Are we good to land this?

2024-02-09 02:11 UTC, humphd commented
Check in with the sheriff.

2024-02-09 02:14 UTC, Amnish04 commented
@Rachit1313 Do you think we need more reviews here?

2024-02-09 17:43 UTC, humphd commented
@Rachit1313 ping, what's up with this one?  Can we merge?

2024-02-09 17:46 UTC, merged