Add pre tag and remove all attributes from the main element to remove aria-hidden tagging
tarasglek/chatcraft.org pull request #424
Opened 2024-02-08 09:22 UTC by bronaugh

This should fix issue 422.

2024-02-08 14:45 UTC, humphd requested changes

2024-02-08 14:45 UTC, humphd commented on src/lib/share.ts
> +  preElement = document.createElement("pre");
`const preElement = ...`

2024-02-09 08:54 UTC, bronaugh commented on src/lib/share.ts
> +  preElement = document.createElement("pre");
Thanks, fixed.

2024-02-09 09:25 UTC, merged

2024-02-09 09:34 UTC, tarasglek commented
Verified in prod that this works :)
![image](https://github.com/tarasglek/chatcraft.org/assets/857083/22b88da2-0370-4533-bfee-55cffdc55459)
Awesomely our prerendered sharing page even renders in [links](https://en.wikipedia.org/wiki/Links_(web_browser)) text-mode browser now...so search engines should give us more love too