Fix html not syntax highlight
tarasglek/chatcraft.org pull request #430
Opened 2024-02-08 23:09 UTC by mingming-ma

Fixes #429 

This is weird, because I couldn't find the html language from the demo list [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter). Currently I can see it is default use `text` type for the html from developer tools.

I trying to use `htmlbars` to solve this issue.

2024-02-08 23:11 UTC, humphd requested changes
This doesn't make sense to me, it's worked for months.

Can we `git bisect` to see what broke it?

2024-02-08 23:12 UTC, mingming-ma commented
Yeah, sure, somehow I find this deployed still not working.

2024-02-08 23:46 UTC, mingming-ma commented
It may at least exists long time, see here the screenshots from my PR from October https://github.com/tarasglek/chatcraft.org/assets/133393905/49bb9503-69dd-4b59-a24a-249ecb4e19b7

2024-02-09 00:32 UTC, humphd commented
Amazing.  Maybe we're wrong and this never worked (cc @tarasglek)?  Looks like people use `xml` as the language for HTML content with highlight.js

2024-02-09 00:53 UTC, mingming-ma commented
It works! `xml` more suitable 👍  There is some difference between local and cloud, maybe from OS, my `htmlbars` version is also working locally, and I don't know why first try fails. Maybe we can solve by this way for now.

2024-02-09 01:45 UTC, humphd approved these changes

2024-02-09 01:45 UTC, merged