Add: Resize the image size to meet OpenAI requirements
tarasglek/chatcraft.org pull request #458
Opened 2024-02-15 20:31 UTC by mingming-ma

## Explanation

This updates make sure users' input image's size is within OpenAI [GPT-4V](https://openai.com/research/gpt-4v-system-card) limit.

The OpenAI requirements for images can be found at [Is there a limit to the size of the image I can upload?](https://platform.openai.com/docs/guides/vision/is-there-a-limit-to-the-size-of-the-image-i-can-upload)
 > Yes, we restrict image uploads to 20MB per image.

And [Calculating costs](https://platform.openai.com/docs/guides/vision/calculating-costs)
> `detail: high` images are first scaled to fit within a 2048 x 2048 square, maintaining their aspect ratio. 

I found this tool [browser-image-compression](https://github.com/Donaldcwl/browser-image-compression) focus on the image compression in web browser is great to handle it, supports both file size and px constraints.

I set the values in imageCompressionOptions as:
```
      const imageCompressionOptions = {
        maxSizeMB: 20,
        maxWidthOrHeight: 2048,
        useWebWorker: true,
      };
```

The `useWebWorker` is optional, means the tool will use multi-thread web worker for the compression, fallback to run in main-thread (default: `true`). Although it is default `true`, I added it to align with the document's (Usage)[https://github.com/Donaldcwl/browser-image-compression?tab=readme-ov-file#usage] 

Fixes #395

2024-02-15 21:26 UTC, Amnish04 requested changes
I've tested this and it works well! Just a few suggestions I commented.

2024-02-15 21:26 UTC, Amnish04 commented on src/components/OptionsButton.tsx
> +          }
```suggestion
          if (
            file.type.startsWith("image/") &&
            // Make sure image's size is within 20MB
            // https://platform.openai.com/docs/guides/vision/is-there-a-limit-to-the-size-of-the-image-i-can-upload
            file.size > imageCompressionOptions.maxSizeMB * 1024 * 1024
          ) {
            try {
              const compressedFile = await imageCompression(file, imageCompressionOptions);
              readFile(compressedFile);
            } catch (err: any) {
              console.error(err);
              error({ title: "Unable to share chat", message: err.message });
            }
          } else {
            readFile(file);
          }
```

I see that there's an unnecessary if statement here, we can probably combine both conditions to reduce repetition.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/0eec2210-67cb-4916-af5d-55bbf36b24d6)


Also can we use try catch syntax as for better readability? (Not a big deal anyways as this is a short piece of code)

2024-02-15 21:26 UTC, Amnish04 commented on src/components/PromptForm/DesktopPromptForm.tsx
> +          });
Same here

2024-02-15 21:30 UTC, Amnish04 commented
I was also wondering if we should set a lower maximum size of image upload for better performance, or would that be a negligible difference?

2024-02-15 23:20 UTC, mingming-ma commented
@Amnish04 Yeah, that's a good way to try. if we set lower value of `maxSizeMB`, it should improve the response since the payload now have smaller image, and also help reduce the costs. 

Maybe we add options in follow up PRs for the user to select uploaded image with different compression rate or wanted size. User can adjust it accordingly by the result.

2024-02-15 23:45 UTC, mingming-ma commented on src/components/PromptForm/DesktopPromptForm.tsx
> +          });
Do you mean the `then()` syntax here? I'd like this way so the function name will not be changed ( add the `async`) and don't need to modify other function invoking places.

2024-02-16 00:58 UTC, Amnish04 commented on src/components/PromptForm/DesktopPromptForm.tsx
> +          });
I guess we have to manually wrap a Promise here anyways, so you're right we don't need to change this.

2024-02-16 02:34 UTC, humphd requested changes

2024-02-16 02:34 UTC, humphd commented on src/components/OptionsButton.tsx
> +import imageCompression from "browser-image-compression";
In a follow-up, let's do a dynamic import for this only when we need it, so we don't download it and add weight to the bundle otherwise.

We can land this as is for now.

2024-02-16 02:34 UTC, humphd commented on src/components/OptionsButton.tsx
> +      // Helper function
Get rid of this, it adds nothing.

2024-02-16 02:34 UTC, humphd commented on src/components/OptionsButton.tsx
> +            file.size > imageCompressionOptions.maxSizeMB * 1024 * 1024
So is this ever going to run? Unless the file is larger than 20M, you won't ever run this.  I feel like we should be running this for images with dimensions larger than 2048 regardless of size.

If I take an image with my phone, it could be 10M, but I don't need to send all that pixel data for an AI to use a 2048x2048 reduced image.  Since OpenAI will throw away all this data after we upload it, in order to shrink it down, let's do it first so we don't a) waste bandwidth; b) store massive images we don't need in the db.

2024-02-16 02:34 UTC, humphd commented on src/components/PromptForm/DesktopPromptForm.tsx
> +    const imageCompressionOptions = {
All this duplication of code across the two forms should get put in a separate file, where the image manipulation happens.  It doesn't need to live in React components.

2024-02-16 05:30 UTC, mingming-ma commented on src/components/OptionsButton.tsx
> +import imageCompression from "browser-image-compression";
Got it, filed https://github.com/tarasglek/chatcraft.org/issues/465 to track

2024-02-16 15:36 UTC, humphd requested changes

2024-02-16 15:36 UTC, humphd commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Can you move this in here too?

```ts
      imageCompression(file, imageCompressionOptions)
        .then((compressedFile) => {
          const reader = new FileReader();
          reader.readAsDataURL(compressedFile);
          reader.onloadend = () => {
            const base64data = reader.result as string;
            resolve(base64data);
          };
        })
```

2024-02-16 21:13 UTC, humphd commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Can we do this too?

2024-02-16 22:40 UTC, mingming-ma commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Do you mean the comments? I've moved in [e5a164b](https://github.com/tarasglek/chatcraft.org/pull/458/commits/e5a164be3409f23959a1af536a956582f5191d8a).

2024-02-16 22:46 UTC, mingming-ma commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Strange, it's also not showing `Outdated` on my side, don't know why

2024-02-17 00:17 UTC, mingming-ma commented
@humphd During refactoring the code, I realized can also solve the dynamic import issue 😄  Let me know if other updates needed. Thanks a lot for the feedback!

2024-02-17 00:20 UTC, mingming-ma commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Fixed at [6c0c2ee](https://github.com/tarasglek/chatcraft.org/pull/458/commits/6c0c2eed9559f3e1ccb66d49d63b1ff50644b87d)

2024-02-17 13:33 UTC, humphd requested changes
Much better!  One small fix.

2024-02-17 13:33 UTC, humphd commented on src/lib/utils.ts
> +export const imageCompressionOptions = {
Move this inline below into your `compressImageToBase64` function, since we don't use this externally now.

2024-02-18 00:03 UTC, humphd approved these changes

2024-02-19 04:31 UTC, merged