Created OpenAiProvider and OpenRouterProvider
tarasglek/chatcraft.org pull request #479
Opened 2024-02-22 11:20 UTC by kliu57

Closes #478

2024-02-23 16:50 UTC, tarasglek commented
These providers have too much copy-pasted code. Maybe make openrouter extend openai?

2024-02-23 23:11 UTC, kliu57 commented
> These providers have too much copy-pasted code. Maybe make openrouter extend openai?

I could remove the `createClient` function from the two providers and we just use the `createClient` function in [ai.ts](https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/ai.ts) which tackles both.

2024-02-24 08:10 UTC, kliu57 commented on src/lib/providers/OpenAiProvider.ts
> +type ProviderName = "OpenAI" | "OpenRouter.ai";
yes I can do that

2024-02-24 08:11 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
I can't make it abstract yet. Right now we are still using ChatCraftProvider and we have not switched to full on using OpenAiProvider and OpenRouterProvider. Once I make it abstract we cannot create ChatCraftProvider objects anymore.

2024-02-24 08:14 UTC, kliu57 commented on src/lib/providers/OpenAiProvider.ts
> +        baseURL: "https://api.openai.com/v1",
I think we should use api url constants defined in ChatCraftProvider.ts instead of hardcoding strings. - Yes I can do that

instead of defining global constants, shouldn't API_URL be a static property of every concrete Provider class? - currently ChatCraftProvider class needs access to these two urls. If I put it in their respective classes and import them into ChatCraftProvider, since they are are child classes I run into a circular dependency issue. To get around that I would need to use dynamic imports. Not sure if this is worth the trouble..

2024-02-24 08:16 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
right now I'm pushing the code for OpenAiProvider and OpenRouterProvider in advance but they are not in use as of yet. Once they are in use then I can make ChatCraftProvider abstract and we wouldn't need fromUrl anymore.

2024-02-24 08:19 UTC, kliu57 commented on src/lib/providers/OpenRouterProvider.ts
> +    const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
the full string has to be this path for the api call to work. Is there benefit to just using the OPENROUTER_API_URL for the first part of the string? having to concatenate a string wouldn't make it faster or anything

2024-02-24 08:20 UTC, kliu57 commented on src/lib/providers/OpenRouterProvider.ts
> +  }
ok I can do that

2024-02-24 22:56 UTC, Amnish04 commented on src/lib/providers/OpenRouterProvider.ts
> +    const res = await fetch(`https://openrouter.ai/api/v1/auth/key`, {
It not about making fast, but to limit the hard coded part of the string. Its a common practice to concatenate the base url and pathnames, but up to you

2024-02-24 22:59 UTC, Amnish04 commented on src/lib/providers/OpenAiProvider.ts
> +        baseURL: "https://api.openai.com/v1",
Makes sense

2024-02-25 05:35 UTC, kliu57 commented on src/lib/providers/OpenRouterProvider.ts
> +  }
actually will just keep the function in its current location in ai.ts for now

2024-02-25 06:54 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
I will make the change to this method so that it returns not ChatCraftProvider objects but specific OpenAiProvider and OpenRouterProvider object

2024-02-25 07:15 UTC, kliu57 commented
@tarasglek for the duplicated methods such as `createClient` and `queryModels` from `OpenAiProvider`, `OpenRouterProvider` to avoid too much duplicate code and just kept them in [`ai.ts`](https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/ai.ts).

@Amnish04 Made the changes you requested:

- removed `createClient`, `queryModels` methods from `OpenAiProvider.ts` and `OpenRouterProvider.ts` since it's better for those methods to stay in [`ai.ts`](https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/ai.ts) (less duplicate code)
- replaced hardcoded strings `"https://api.openai.com/v1"`, `"https://openrouter.ai/api/v1"` with `OPENAI_API_URL`, `OPENAI_API_URL` exported from [`ChatCraftProvider.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-163489fb9d67f12a96f71b1a06ec2c3cc41152124ad90c14adcc6ded77869f1a)
- removed `OPENAI_API_URL`, `OPENROUTER_API_URL` from [`lib/settings.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-b5f5521c9795e314efdf6293ad3afda789a1402bbf5e2a304e20efa8134d2a15) and replaced imports to be importing from [`ChatCraftProvider.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-163489fb9d67f12a96f71b1a06ec2c3cc41152124ad90c14adcc6ded77869f1a)
- removed duplicate code `type ProviderName = "OpenAI" | "OpenRouter.ai";` by exporting it from [`ChatCraftProvider.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-163489fb9d67f12a96f71b1a06ec2c3cc41152124ad90c14adcc6ded77869f1a)
- changed `supportedProviders` to [`loadSupportedProviders()`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-163489fb9d67f12a96f71b1a06ec2c3cc41152124ad90c14adcc6ded77869f1a), which now no longer returns associative array of `ChatCraftProvider` objects. It now returns associatitve array of child objects (one `OpenAiProvider` and one `OpenRouterProvider`). Made subsequent changes in [`Instructions.tsx`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-9fcdb80f3814fd658a3bb7dcaf58478d27938a43cde9049d449210652e77434c) and [`PreferencesModel.tsx`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-1025748a16e04005898c20c05840616be48ca0eb4eb4c156248de41a2f3bdd7d) for calling the async function `loadSupportedProviders()` using useEffects etc.

2024-02-26 07:02 UTC, tarasglek commented
Code looks much better now. Is there any expected change in behavior or is this a pure refactoring?

2024-02-27 12:42 UTC, kliu57 commented
> Code looks much better now. Is there any expected change in behavior or is this a pure refactoring?

No change in behaviour. Mostly refactoring and the introduction of the OpenAiProvider and OpenRouterProvider classes as child classes of ChatCraftProvider.

2024-02-27 21:05 UTC, tarasglek commented
lgtm

2024-03-04 14:48 UTC, kliu57 commented
@humphd Need some guidance. Everything works well prior to commit d7d415c11771853de96216efc759401dfd8a481c.

But in commit d7d415c11771853de96216efc759401dfd8a481c I replaced `settings.apiUrl` and `settings.apiKey` with `settings.currentProvider`. This is a little buggy. I believe the reason it is buggy is because I am using useStates and useEffects in multiple files to access `settings.currentProvider`. I couldn't directly access `settings.currentProvider` since it needs to be deserialized (thus I decided to go with a useEffect). With the useEffects it was working well when I has it just in two files, but once I put it in many more files the buggy behaviour started appearing.

2024-03-05 00:14 UTC, kliu57 commented
[UPDATE] Fixed buggy behaviour by switching from using useEffect and useStates to context. Deserialization of `settings.currentProvider` is now done in one `use-settings` file instead of the previous multiple useEffects. Code ready for testing and review. My tests so far have been successful.

2024-03-06 17:39 UTC, humphd requested changes
@kliu57 I've done a first pass through this code, and made some suggestions to simplify and improve.  I'll review again once you fix the various things I've highlighted and let me know.

Overall, this is coming along really well.

2024-03-06 17:39 UTC, humphd commented on src/components/Message/AiMessage.tsx
> +      if (!settings.currentProvider || !settings.currentProvider.apiKey) {
This type of check can use `if (!settings.currentProvider?.apiKey) }` to cover both cases

2024-03-06 17:39 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
Let's not do a dynamic import on these, and then you don't need to have `fromUrl()` be async.  The size saving on these two files is minimal, they can become part of the bundle.

The time when we want to do this is when we're loading something huge (like we saw today in the call with the `python.wasm` file).

2024-03-06 17:39 UTC, humphd commented on src/components/PromptForm/index.tsx
> +  if (!settings.currentProvider.apiKey) {
Combine this into a single check like I showed above with `?.apikey`

2024-03-06 17:39 UTC, humphd commented on src/hooks/use-chat-openai.ts
> +      const chat = await chatWithLLM(messages, {
Why this change?

2024-03-06 17:39 UTC, humphd commented on src/hooks/use-settings.tsx
> +  const [isMigrated, setIsMigrated] = useState(false);
This is legacy code we're not going to need/want later.  A better way to do this is to check for the existence of the old stuff and migrate to the new vs. having this be a permanent part of our API.

2024-03-06 17:42 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
@humphd If I try to do a regular import a the top of the file I run into a circular dependency issue
Any ideas how to overcome that?

2024-03-06 17:45 UTC, Amnish04 reviewed
A few things I noticed

2024-03-06 17:49 UTC, kliu57 commented on src/hooks/use-settings.tsx
> +  const [isMigrated, setIsMigrated] = useState(false);
@humphd  Where should I do this check? Right now I am checking it in a useEffect in use-settings

2024-03-06 17:55 UTC, kliu57 commented on src/components/Message/AiMessage.tsx
> +      if (!settings.currentProvider || !settings.currentProvider.apiKey) {
I will fix this

2024-03-06 17:55 UTC, kliu57 commented on src/components/PromptForm/index.tsx
> +  if (!settings.currentProvider.apiKey) {
I will fix this

2024-03-06 17:56 UTC, Amnish04 commented on src/components/Message/AiMessage.tsx
> +    [props.chatId, settings.currentProvider, message, callChatApi]
Nvm that's just a part of useEffect dependencies

2024-03-06 17:57 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
You could move the code for these other providers into this file if you want, since it isn't that much.  We do the same the ChatCraftMessage, etc.

2024-03-06 18:00 UTC, kliu57 commented on src/components/Message/AiMessage.tsx
> +      if (!settings.currentProvider || !settings.currentProvider.apiKey) {
I will fix this

2024-03-06 18:01 UTC, kliu57 commented on src/components/PromptForm/index.tsx
> +  if (!settings.currentProvider.apiKey) {
I will fix this

2024-03-06 18:02 UTC, kliu57 commented on src/hooks/use-chat-openai.ts
> +      const chat = await chatWithLLM(messages, {
Seems I have make a mistake here. chatWithLLM did not need to become async since I handled deserialization in the context. I will fix this.

2024-03-06 18:03 UTC, kliu57 commented on src/lib/speech-recognition.ts
> +    }
Seems I have make a mistake here. transcribe did not need to become async since I handled deserialization in the context. I will fix this.

2024-03-06 18:05 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
@humphd Do we still want to have OpenAiProvider and OpenRouterProvider class in our project? Because if we do then I will need to import them in order for fromUrl to return the appropriate object (either an OpenAiProvider object or OpenRouterProvider object). And I can't get that done without using dynamic import.

2024-03-06 18:26 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
The solution to this problem is to separate the logic for `fromUrl()` from the base class.  For example, you could move the `if/else` logic to the calling code instead of putting it in `fromUrl(), making the `fromUrl()` an `abstract` method that gets implemented by derived classes.

2024-03-06 19:05 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
@humphd I thought the point of the fromUrl function is we can check a URL and from that string figure out whether we want to return an OpenRouterProvider object or OpenAiProvider object? if fromURL is in OpenAiProvider what use would it have? Instead of calling `OpenAiProvider.fromUrl` I could just call `new OpenAiProvider()` to make a new object.

2024-03-06 19:14 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
@humphd Sorry I'm still a bit confused. I definitely can make fromUrl abstract and instantiate it in the child classes. But then when the user changes their API URL in the Select dropdown... how would I take that string URL and get a ChatCraftProvider object from it? Right now I am using ChatCraftProvider.fromUrl, but if I make this change I won't be able to any longer.

2024-03-06 19:22 UTC, kliu57 commented
@humphd @Amnish04 Pushed new code which resolves redundant checks (i.e. using '?' => `currentProvider?.apiKey`)
Also removed unecessary code changes

**These two issues still in discussion:**
- [dynamic import issue](https://github.com/tarasglek/chatcraft.org/pull/479/files/ac3e67df87755ad9f94d9864bdfa323de83bc041#r1514902689)
- [migration code issue](https://github.com/tarasglek/chatcraft.org/pull/479#discussion_r1514906887)

2024-03-06 19:23 UTC, Amnish04 commented on src/hooks/use-settings.tsx
> +  const [isMigrated, setIsMigrated] = useState(false);
I think what @humphd means is that you don't need to maintain an `isMigrated` state.

You just need to check if the old `apiUrl` and `apiKey` are there, update to the new model.

Which I think you are already doing here
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/3abe1b69-707f-4f2b-a88a-ed6a14af98c8)

I just tried after removing `isMigrated`, manipulating my settings in localStorage to old format, and still works fine meaning that the flag isn't doing anything anyways

2024-03-06 20:34 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      const { OpenAiProvider } = await import("./providers/OpenAiProvider");
as per our call, I will move the functions that require dynamic imports to providers/index.ts thus removing the need for dynamic imports

2024-03-06 20:34 UTC, kliu57 commented on src/hooks/use-settings.tsx
> +  const [isMigrated, setIsMigrated] = useState(false);
as per our call, I will remove the state variable as well as move my code additions out of this file and into settings.ts => deserializer

2024-03-06 23:51 UTC, kliu57 commented
@humphd 

Solved these two issues as per our call

- dynamic import issue - no more dynamic imports, moved code out of `ChatCraftProvider.ts` and into [`providers/index.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-4c5f3070b0bc8cc1848bbd1824438c5c36d980675884a7a9419c904e865fe81e)
- migration code issue - removed state variable, moved code out of `hooks/use-settings.tsx` and into `deserializer` function of [`lib/settings.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-b5f5521c9795e314efdf6293ad3afda789a1402bbf5e2a304e20efa8134d2a15). The code in the `deserializer` includes deserialization of `currentProvider` and migration code

Everything is working. However I have a few questions for you:

1. Right now the migration code is inside `deserializer` function of [`lib/settings.ts`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-b5f5521c9795e314efdf6293ad3afda789a1402bbf5e2a304e20efa8134d2a15). However it runs many times as you can see by the console.warn messages below. Is this a problem? Once the migration finishes it stop running, but at the very beginning it will run many times. In my old approach when I had the migration code inside the useEffect in [`use-settings.tsx`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-44205fdbbda68a7a732c89f3e7dddb38e6e065a794b4f85eb191ce4e4cc31293) it only runs once. I left the old code commented out in there for now in case you want to compare the two.

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/cc487111-edcf-4c41-b91f-b3ad2d5f0e7a)

2. The old code for the [`use-settings.tsx`](https://github.com/tarasglek/chatcraft.org/pull/479/files#diff-44205fdbbda68a7a732c89f3e7dddb38e6e065a794b4f85eb191ce4e4cc31293) file:

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/9292ff57-f6de-4669-85e8-01b718d4b962)

After I added my code in `settings.ts` to deserialize currentProvider, if I do not change this useEffect's dependency from [settings] to [], then I get glitching whenever I try to swap providers by toggling the dropdown. It seems like by keeping [settings] as the dependency this useEffect is running at the same time that my swap provider code is running and so my code changes the provider, then this useEffect switches it back again. You will notice a "glitching" effect. By settings the dependency to [] I have fixed the problem but I just want to check with you if it is ok to make this change since I am not 100% clear.

2024-03-07 02:47 UTC, humphd commented on src/lib/settings.ts
> +  if (settings.currentProvider) {
This all seems good to me.  It doesn't really matter how many times it runs, because eventually it will get serialized back to JSON and stored.

2024-03-07 03:41 UTC, Amnish04 approved these changes

2024-03-07 04:08 UTC, kliu57 commented on src/hooks/use-settings.tsx
> +// import { providerFromUrl } from "../lib/providers";
removed

2024-03-07 05:12 UTC, merged