Add python-wasi on run-code
tarasglek/chatcraft.org pull request #485
Opened 2024-03-06 15:37 UTC by WangGithub0

Add python-wasi in run-code, and also addressing typeScript type declarations for it.
#312 

<img width="851" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/b3fb9744-0db0-49b5-8d00-da4e2c02427f">

2024-03-06 17:27 UTC, humphd requested changes
This is amazing, such great work.

2024-03-06 17:27 UTC, humphd commented on src/components/CodeHeader.tsx
> +import { isRunnable, isRunnableOnServer, runCode } from "../lib/run-code";
I wonder if we should rename `isRunnable` to `isRunnableInBrowser` to match what you're doing here.

2024-03-06 17:27 UTC, humphd commented on src/lib/run-code.ts
> +const supportedLanguages = [...supportedJS, ...supportedTS, ...supportedPY];
`supportedBrowserLanguages` maybe?

2024-03-06 17:27 UTC, humphd commented on src/lib/run-code.ts
> +  const url = "https://unpkg.com/@antonz/python-wasi/dist/python.wasm";
Can we get this from node_modules vs. unpkg.com?  Vite allows you to get a URL for a WASM https://vitejs.dev/guide/features#accessing-the-webassembly-module

2024-03-06 17:30 UTC, tarasglek commented
thats exciting, lets make the run button run it instead of showing menu when no server option

2024-03-06 17:32 UTC, tarasglek commented
love how small this change is

2024-03-07 03:42 UTC, WangGithub0 commented on src/lib/run-code.ts
> +  const url = "https://unpkg.com/@antonz/python-wasi/dist/python.wasm";
I change to use node_modules and can build successfully on my local, but fail in [CloudFlare](https://dash.cloudflare.com/?to=/:account/pages/view/chatcraft-org/2ae02daa-e807-47a9-80e1-858c95ad4f84), could you help me check the log on CloudFlare

2024-03-07 12:52 UTC, humphd commented on src/lib/run-code.ts
> +  const url = "https://unpkg.com/@antonz/python-wasi/dist/python.wasm";
```

22:37:22.763 | Deploying your site to Cloudflare's global network...
-- | --
22:37:26.503 |  
22:37:26.618 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
22:37:26.619 |  
22:37:26.619 | assets/python-vjebDg3S.wasm is 26.3 MB in size

```

So we're going to have to load it from a CDN.  I guess go back to using unpkg.com.

2024-03-07 14:50 UTC, humphd approved these changes

2024-03-08 05:46 UTC, kliu57 approved these changes
I tested it and it works on running python code from both user's own python code and chatgpt's reply python code. Only thing I found was it will output an error if you try to run any python code that is asking for user input (because obviously we have no terminal to take in user's input I suppose)

Maybe something for future follow up PRs could be to print more details error messages when such fails occur. Right now it just says something like this

```
Error: Script execution failed

ySe/</</<@https://60283562.console-overthinker-dev.pages.dev/assets/index-1LG397X1.js:579:1095
```

2024-03-08 13:28 UTC, merged