Add Ruby in run-code
tarasglek/chatcraft.org pull request #492
Opened 2024-03-13 03:37 UTC by WangGithub0

<img width="839" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/a60e5d0a-23f1-484f-bda4-325b17363f7a">

2024-03-13 16:19 UTC, tarasglek commented
lgtm, love how easy these are to add

2024-03-14 15:39 UTC, humphd requested changes
This is really clean.  A few things to figure out.

2024-03-14 15:39 UTC, humphd commented on src/lib/run-code.ts
> +async function runRuby(code: string) {
This is nearly identical to the python code, can we refactor to share common bits?

2024-03-14 15:39 UTC, humphd commented on src/lib/run-code.ts
> +            resolve(); // Resolves the promise with no value
This comment is not needed.

2024-03-14 15:39 UTC, humphd commented on src/lib/run-code.ts
> +            reject(new Error("Script execution failed")); // Rejects the promise if execution failed
Same here.

2024-03-14 15:39 UTC, humphd commented on src/lib/run-code.ts
> +          reject(error); // Reject on error
And here.  Let the code speak for itself if you have nothing more to add.

2024-03-15 00:35 UTC, humphd requested changes
Looks good, one thing to fix.

2024-03-15 00:35 UTC, humphd commented on src/lib/run-code.ts
> +async function runPythonOrRuby(code: string, language: string) {
`runInWasi()` would be a better name.

2024-03-15 05:36 UTC, kliu57 approved these changes
Tested it in browser, it works as expected!

2024-03-15 14:17 UTC, merged