Add: Generate Image by DALL·E 3
tarasglek/chatcraft.org pull request #493
Opened 2024-03-13 13:51 UTC by mingming-ma

2024-03-13 16:21 UTC, tarasglek commented
we need to change code so commands added automatically show up in /commands atm this command is impossible to discover 
<img width="959" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/17be9b50-4372-48e7-b84a-a43622e13aed">

2024-03-13 16:23 UTC, tarasglek commented
also really confusing that /dalle3 doesn't work

2024-03-13 16:25 UTC, humphd commented
I think it should be `/image ...`

2024-03-13 18:14 UTC, rjwignar commented on src/lib/ai.ts
> +  size: dalle3ImageSize = "1024x1024"
I noticed in the generateImage() call in src/lib/commands/ImageCommand.ts, we only pass the prompt.
I wonder if in the future, we can/should allow the user to select the image size as well.

2024-03-13 18:21 UTC, rjwignar reviewed
One thing I noticed is that once the chat exceeds the screen height, the scrollbar doesn't automatically move down to show the user the generated image:
![dalle3Scrollbar](https://github.com/tarasglek/chatcraft.org/assets/78163326/fe7d95f8-cd10-4eab-8154-4fed63ccc503)

However, this is something to be investigated in a follow-up, and **should not block** this from being merged.

2024-03-13 18:37 UTC, rjwignar approved these changes
@mingming-ma These changes look good! It was a good idea to rename the command to "/image".

At the time of my review, @tarasglek and @humphd's suggestions have been addressed and incorporated into this PR:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/3435818a-fd29-470e-9be2-a7f1fc952e14)

I left ~3 observations/concerns that are either non-issues or can be addressed in follow-up PRs.
They shouldn't prevent this from being merged. @humphd do you agree?

2024-03-14 12:47 UTC, tarasglek commented on src/lib/ai.ts
> +    throw new Error(`Failed to generate image: ${error.message}`);
i think we should do a check to see if dalle3 is among available models and provide a erro message in this PR

2024-03-14 12:48 UTC, tarasglek commented
I think we should also try to store the image similarly to how we upload images into chatcraft, so we can then ask gpt vision to analyze it

2024-03-14 18:26 UTC, Amnish04 requested changes
@mingming-ma This is a pretty cool feature. Just left a few comments after reviewing.

2024-03-14 18:26 UTC, Amnish04 commented on src/lib/ai.ts
> +  const { openai } = createClient(currentProvider?.apiKey, currentProvider?.apiUrl);
I don't think we need a `.?` here since we are already doing the `currentProvider.apiKey` check above.

I'll fix my `textToSpeech` function as well.

2024-03-14 18:39 UTC, Amnish04 commented
@mingming-ma This is unrelated to this PR, but I feel like the images should have a `cursor: pointer` for the user to know something happens on clicking them.

Can we make that change in this PR or a follow up?

2024-03-15 00:34 UTC, humphd commented on src/lib/ai.ts
> +  const { openai } = createClient(currentProvider?.apiKey, currentProvider?.apiUrl);
FYI, @kliu57 is changing how this works right now, too.

2024-03-15 00:42 UTC, mingming-ma commented
> I think we should also try to store the image similarly to how we upload images into chatcraft, so we can then ask gpt vision to analyze it(this can be done in followup)

I filed an issue to fix store problem #496 , just want to inform you that at the moment user is able use vision to analyze the generated image

2024-03-15 01:01 UTC, mingming-ma commented on src/lib/commands/ImageCommand.ts
> +    const prompt = args.join(" ");
Filed https://github.com/tarasglek/chatcraft.org/issues/499 to track

2024-03-15 01:02 UTC, mingming-ma commented on src/lib/ai.ts
> +  size: dalle3ImageSize = "1024x1024"
Filed https://github.com/tarasglek/chatcraft.org/issues/499 to track

2024-03-15 01:04 UTC, mingming-ma commented on src/lib/ai.ts
> +  const { openai } = createClient(currentProvider?.apiKey, currentProvider?.apiUrl);
I'll follow up the changes to see how to fix this

2024-03-15 01:12 UTC, mingming-ma commented
> One thing I noticed is that once the chat exceeds the screen height, the scrollbar doesn't automatically move down to show the user the generated image:

@rjwignar I just saw @Amnish04 fixed an issue related the auto scroll, https://github.com/tarasglek/chatcraft.org/pull/495, I don't know it is related or not, let's see how it is after this be merged, sounds good?

2024-03-15 01:19 UTC, Amnish04 commented
> @rjwignar I just saw @Amnish04 fixed an issue related the auto scroll, #495, I don't know it is related or not, let's see how it is after this be merged, sounds good?
@mingming-ma I just undid that fix in #497 as that was causing nested submenus to break (more details [here](https://github.com/tarasglek/chatcraft.org/pull/497#discussion_r1524153514)). But nonetheless, I don't think that was related to this issue

2024-03-15 01:36 UTC, mingming-ma commented on src/lib/ai.ts
> +export const generateImage = async (
Thanks for the suggestion, I added a comment to doc this and also let dev know why `n` is `1` which makes more sense.

2024-03-15 13:19 UTC, mingming-ma commented on src/lib/ai.ts
> +    throw new Error(`Failed to generate image: ${error.message}`);
Fixed at [e61b83a](https://github.com/tarasglek/chatcraft.org/pull/493/commits/e61b83ab02f21bfca8b1114116fab0983a06b365)

2024-03-15 13:24 UTC, humphd approved these changes

2024-03-15 13:24 UTC, humphd commented on src/lib/ai.ts
> +      prompt: prompt,
nit: when you have the same key/value names, only include it once:

```ts
{
  model: "dall-e-e",
  prompt,
  n,
  size,
}
```

2024-03-15 13:25 UTC, humphd commented
In a follow-up, I wonder if we should add a menu item to the Options menu to allow you to do the same thing, but pop-up a little model where you type your prompt?  Or maybe make it so entering a prompt and asking the dall-e model does this too?

2024-03-15 14:14 UTC, mingming-ma commented
> In a follow-up, I wonder if we should add a menu item to the Options menu to allow you to do the same thing, but pop-up a little model where you type your prompt? Or maybe make it so entering a prompt and asking the dall-e model does this too?

@humphd Just guessing the main concern here, let user know this feature more easily?

2024-03-15 14:43 UTC, humphd commented
> > In a follow-up, I wonder if we should add a menu item to the Options menu to allow you to do the same thing, but pop-up a little model where you type your prompt? Or maybe make it so entering a prompt and asking the dall-e model does this too?
> 
> @humphd Just guessing the main concern here, let user know this feature more easily? Maybe we could also add the `Commands` in the `Options` menu, and list them as submenus.

Lots of users will never use/know about `/slash` commands.  It's pretty advanced.

2024-03-15 18:36 UTC, Amnish04 commented
@mingming-ma Do we have an issue to track this https://github.com/tarasglek/chatcraft.org/pull/493#issuecomment-1998092723

2024-03-15 20:57 UTC, mingming-ma commented
> @mingming-ma Do we have an issue to track this [#493 (comment)](https://github.com/tarasglek/chatcraft.org/pull/493#issuecomment-1998092723)

@Amnish04 Just filed https://github.com/tarasglek/chatcraft.org/issues/504 to track this

2024-03-15 21:02 UTC, mingming-ma commented
I think we can merge this PR for now, @humphd @Amnish04 I'll create another issue follow up the  [react-medium-image-zoom](https://www.npmjs.com/package/react-medium-image-zoom)

2024-03-15 21:04 UTC, Amnish04 approved these changes

2024-03-15 21:16 UTC, merged