Add new provider - in progress
tarasglek/chatcraft.org pull request #498
Opened 2024-03-14 06:57 UTC by kliu57

2024-03-14 07:59 UTC, kliu57 commented
@tarasglek Just wondering if you have ever encountered this CORS issue I'm facing

2024-03-14 12:38 UTC, tarasglek commented
Seems to work here, except it doesn't provide full choice of models..

2024-03-14 12:38 UTC, tarasglek commented on src/lib/providers/FreeOpenRouterProvider.ts
> +    return "openchat/openchat-7b:free";
should just pick first available model instead of hardcoding

2024-03-14 13:49 UTC, humphd requested changes

2024-03-14 13:49 UTC, humphd commented on src/components/Message/AppMessage/Instructions.tsx
> +      ?.validateApiKey(apiKey)
Is it possible for us to get rid of the `undefined` in the `currentProvider` type? That is, can we make sure that we always return this free provider if nothing else is configured in the settings, and then not need to deal with `.currentProvider?`

2024-03-14 13:49 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +export type ProviderName = "OpenAI" | "OpenRouter.ai" | "Demo Provider";
This new name should match what we call this thing.  I'd suggest "Default Provider"

2024-03-14 13:49 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +      throw new Error(err.message ?? `error querying models API`);
```suggestion
      throw new Error(`error querying models API: ${err.message}`);
```

2024-03-14 13:49 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
Question: we store the key in this object, can we avoid needing to pass it in here and use `this.apiKey` instead?  Or, can we do:

```ts
createClient(key?: string) {
  key = key ?? this.apiKey;
  if (!key) {
    throw new Error('missing api key');
  }
  ...
}
```

Then you don't need to manage the key externally.

2024-03-14 13:49 UTC, humphd commented on src/lib/providers/FreeOpenRouterProvider.ts
> +    return "openchat/openchat-7b:free";
Your thing returns a list of models?

2024-03-14 13:49 UTC, humphd commented on src/lib/providers/FreeOpenRouterProvider.ts
> +  async queryModels(key: string) {
Again, I don't think we need this key arg, since it lives on the instance.

2024-03-14 14:21 UTC, kliu57 commented on src/lib/providers/FreeOpenRouterProvider.ts
> +    return "openchat/openchat-7b:free";
@tarasglek How can I acquire a list of available models? I just tried to use our default open ai queryModels function to get a list of models for it but it just returned an empty array.

2024-03-14 14:25 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +      ?.validateApiKey(apiKey)
Right now the currentProvider is never undefined actually, that question mark is just put in the code to avoid lint issues. Because currentProvider is automatically set to OpenAiProvider (with no key) when the user first visits ChatCraft.

If I set currentProvider to the free provider by default, then they won't encounter the Instructions page where they can input their Open Ai / OpenRouter API key anymore. Any new users will just skip automatically to:

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/d45c9b0c-c8fd-4ec0-a7a0-9111506f1b9a)

2024-03-14 14:32 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  get defaultModel() {
the getter (get defaultModel) returns a string, while defaultModelForProvider returns a ChatCraftModel object.

2024-03-14 14:34 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
@humphd The reason I kept the apiKey param is because in Instructions.tsx we only store in the apiKey in settings after it has been validated and not before. If I store the apiKey in settings and then validate it, then when the validation fails I need to add more code to re-set the settings to remove the stored apiKey.

2024-03-14 14:38 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +import { FreeOpenRouterProvider } from "../../../lib/providers/FreeOpenRouterProvider";
I have made this change

2024-03-14 14:39 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +          currentProvider: new FreeOpenRouterProvider("mock_key"),
I have made this change.

2024-03-14 14:39 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +export type ProviderName = "OpenAI" | "OpenRouter.ai" | "Demo Provider";
I have made this change

2024-03-14 14:39 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +      throw new Error(err.message ?? `error querying models API`);
I have made this change

2024-03-14 14:41 UTC, tarasglek commented on src/lib/providers/FreeOpenRouterProvider.ts
> +    return "openchat/openchat-7b:free";
https://taras-free_open_router.web.val.run/api/v1/models

it's open source , capabilities are something one can get from source https://www.val.town/v/taras/free_open_router

2024-03-14 14:42 UTC, kliu57 commented
@humphd Made the following changes according to your reviews:

- Renamed provider to DefaultProvider
- Change the DefaultProvider constructor to not need a key
- Made this code modification: throw new Error(`error querying models API: ${err.message}`);

As for the other unresolved conversations I have replied to them and am awaiting reply

2024-03-14 14:51 UTC, humphd commented on src/components/Message/AppMessage/Instructions.tsx
> +      ?.validateApiKey(apiKey)
But if TypeScript thinks it *could* be undefined, that means it might be at some point (e.g., these types are telling you that there is a bug).  We should make it so that `?.` isn't necessary, then we know it's good.

I think losing the instructions page is OK, since in a follow-up, we can update our logic to show some UI for adding your own provider/key if you are using the default provider.

2024-03-14 14:52 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
Maybe key validation should be `static` and happen without creating the instance?

2024-03-14 15:15 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
@humphd I can make `validateApiKey` static instead but since the OpenAI `validateApiKey` calls `queryModels` which calls `createClient`, all 3 will have to become static. Is that ok?

2024-03-14 15:17 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
Also some of these functions require the apiUrl so once I make them static I will have to add back the code we were previously using to get the apiUrl. So maybe keeping it like this is better?

2024-03-14 15:23 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +      ?.validateApiKey(apiKey)
Actually, I think we are good here. I removed the `?` from `currentProvider?.` and TypeScript did not give me any lint errors. We can talk about setting the default provider to the free one for new users and adding new UI after this release.

2024-03-14 16:29 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
> Maybe key validation should be `static` and happen without creating the instance?

I'm attempting to make `validateApiKey` static in `ChatCraftProvider` but we aren't allowed to make methods static and abstract according to lint. Should I go back to using our previous validateApiKey function (I can use the same code but put it in providers/index.ts intead)?

the code:

```
export async function validateApiKey(apiKey: string) {
  if (usingOfficialOpenAI()) {
    return OpenAiProvider.validateApiKey(apiKey);
  }

  if (usingOfficialOpenRouter()) {
    return OpenRouterProvider.validateApiKey(apiKey);
  }

  if (usingDefaultProvider()) {
    return true;
  }

  // If not either of those providers, something is wrong
  throw new Error("unexpected provider, not able to validate api key");
}
```

2024-03-14 16:32 UTC, kliu57 commented on src/lib/providers/FreeOpenRouterProvider.ts
> +  async queryModels(key: string) {
I have successfully fetched the models

2024-03-14 16:32 UTC, kliu57 commented on src/lib/providers/FreeOpenRouterProvider.ts
> +    return "openchat/openchat-7b:free";
I have successfully fetched the models

2024-03-14 16:40 UTC, kliu57 commented
@tarasglek Just tested all the free models, they all return response except for mythomist-7b:free

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/c43fa612-c914-491c-93cc-8567ae38e994)

2024-03-14 21:45 UTC, tarasglek commented on src/components/Message/AppMessage/Instructions.tsx
> +import { DefaultProvider } from "../../../lib/providers/DefaultProvider";
s/DefaultProvider/FreeModelProvider/

2024-03-14 21:45 UTC, tarasglek commented on src/lib/providers/DefaultProvider.ts
> +    return "openchat/openchat-7b:free";
again, don't hard code model names, just return first model

2024-03-14 21:46 UTC, tarasglek commented on src/lib/providers/DefaultProvider.ts
> +    const res = await fetch(`https://taras-free_open_router.web.val.run/api/v1/models`, {
don't hardcode url everywhere, have a baseurl in class and make everything relative to it

2024-03-14 21:48 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +import { DefaultProvider } from "../../../lib/providers/DefaultProvider";
@tarasglek I had previously named the new provider file `providers/FreeOpenRouterProvider.ts` but Dave wanted me to change it to `providers/DefaultProvider.ts`. Do you not like the name?

2024-03-14 21:48 UTC, tarasglek commented on src/lib/ChatCraftProvider.ts
> +  [DEFAULTPROVIDER_API_URL]: "Default Provider",
Call it "Free AI Models"

2024-03-14 21:48 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +import { DefaultProvider } from "../../../lib/providers/DefaultProvider";
@tarasglek Should I change the name to `FreeModelProvider.ts` and put it in the subfolder `DefaultProvider`

2024-03-14 21:53 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +import { DefaultProvider } from "../../../lib/providers/DefaultProvider";
@tarasglek Should it be `providers/DefaultProvider/FreeModelProvider.ts` or `DefaultProvider/FreeModelProvider.ts` (not under providers)

2024-03-14 23:01 UTC, kliu57 commented on src/lib/providers/DefaultProvider.ts
> +    const res = await fetch(`https://taras-free_open_router.web.val.run/api/v1/models`, {
I have made this fix

2024-03-14 23:01 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +  [DEFAULTPROVIDER_API_URL]: "Default Provider",
I have made this fix

2024-03-14 23:01 UTC, kliu57 commented on src/components/Message/AppMessage/Instructions.tsx
> +import { DefaultProvider } from "../../../lib/providers/DefaultProvider";
I have made this fix

2024-03-14 23:39 UTC, kliu57 commented on src/lib/providers/DefaultProvider.ts
> +    return "openchat/openchat-7b:free";
@tarasglek If I user `queryModels` to get the list of models and then get the first in that list, I would need to make `defaultModelForProvider` and potentially make every function that calls it async as well. Is this what we want?

2024-03-15 00:13 UTC, humphd commented on src/lib/providers/DefaultProvider.ts
> +    return "openchat/openchat-7b:free";
I took a look at this with @kliu57 and it's going to complicate too many things to dynamically get this model--we rely on the default model logic being synchronous, and querying the models will kill that.

In a follow-up we could think about how to handle provider models, but for now, this is the same thing we're doing for every other provider, so I think it's good.

2024-03-15 00:20 UTC, humphd reviewed
Code changes look good to me, thank you for working so hard on this.  @WangGithub0 might be able to test functionality for you.

I've made a couple of comments, only one of which needs attention here or in a follow-up.

I don't need to read this again. From my point of view, it can land when you're ready.

2024-03-15 00:20 UTC, humphd commented on src/Chat/ChatHeader.tsx
> +                  {settings.currentProvider.apiKey && (
Way better with it being required, nice work.

2024-03-15 00:20 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +  createClient(key: string) {
Yeah, OK, let's leave this.

2024-03-15 00:20 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +    return "";
This seems like a bad idea.  Are you assuming this will get implemented in derived classes?  If so, I would `throw new Error('not implemented');` so we catch it as a bug if we get it wrong.

2024-03-15 01:12 UTC, WangGithub0 commented
do we need add icon for the free provider?
<img width="466" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/57ddd1dc-7a69-4247-87a7-63010d50fa89">

2024-03-15 01:56 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
> +    return "";
I will remove these getters called defaultModel() sicne they aren't being used anywhere except in defaultModelForProvider()

2024-03-15 02:16 UTC, kliu57 commented
@WangGithub0 I have fixed the white logo issue by setting the logo bg to green for the free models. The logo is there you just couldn't see it since the bg was white and the logo was white. Code I used to do this is inside `ModelAvatar.tsx`

2024-03-15 02:21 UTC, WangGithub0 approved these changes
Looks good to me

2024-03-15 02:29 UTC, merged

2024-03-15 14:18 UTC, tarasglek commented
omg, we have a chatcraft that one can use without any keys now!

Now if someone wants to figure how to fix my valtown proxy to not buffer SSE before i get to it