Create an index of shared chatcraft chats in R2
tarasglek/chatcraft.org pull request #512
Opened 2024-03-20 02:30 UTC by WangGithub0

add generateAndSaveUserFeed function and run it after puting share

will adding: Appearance and Safety

2024-03-20 10:00 UTC, tarasglek requested changes

2024-03-20 10:00 UTC, tarasglek commented on functions/api/share/[[user_id]].ts
> +    await generateAndSaveUserFeed(env, user);
Just pass in request.body instead of getting it from bucket again

2024-03-20 12:02 UTC, humphd requested changes

2024-03-20 12:02 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +        <entry>
Should also include author info

2024-03-20 12:02 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +    await generateAndSaveUserFeed(env, user);
She has to access the bucket itself, so I think this is necessary.

2024-03-20 12:02 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +  return `Feed generated and saved for user ${user}`;
Let's not do this.  If you want to do this, make it a log message and return nothing.

2024-03-21 02:18 UTC, humphd requested changes

2024-03-21 02:18 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +    description: `This is ${user}'s share chats`,
shared vs. share

2024-03-21 02:18 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +    language: "en",
This may or may not be true

2024-03-21 02:18 UTC, humphd commented on functions/rss-style.xsl
> +            <h2>Recent Posts</h2>
Recent Shared Chats

2024-03-21 02:18 UTC, humphd commented on functions/rss-style.xsl
> +                  Published on
Shared on

2024-03-21 13:39 UTC, humphd requested changes
When I try to share a chat and test this, I get this error in the preview version (browser console):

```
Unable to share chat: Unable to share chat: DOMParser is not defined
```

2024-03-21 14:14 UTC, WangGithub0 commented
> When I try to share a chat and test this, I get this error in the preview version (browser console):
> 
> ```
> Unable to share chat: Unable to share chat: DOMParser is not defined
> ```

Cloudflare Workers don't support DOMParser, I'll revise it using HTMLRewriter

2024-03-21 16:44 UTC, WangGithub0 commented
@humphd I met this error, could you help me check the log?

Error 1102 Ray ID: 867f62ea7e9e5269 • 2024-03-21 16:41:09 UTC
Worker exceeded resource limits
What happened?
You've requested a page on a website (56878ea8.console-overthinker-dev.pages.dev) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. An unknown error occurred while rendering the page.

What can I do?
If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and check the error logs for 56878ea8.console-overthinker-dev.pages.dev.

Cloudflare Ray ID: 867f62ea7e9e5269 • Your IP: Click to reveal 89.208.249.207 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

2024-03-22 14:54 UTC, humphd commented
I can only stream the logs in realtime, but not see old ones.

`Worker exceeded resource limits` implies we've done something to go over the limit (size, calls?)

2024-03-22 16:53 UTC, WangGithub0 commented
> I can only stream the logs in realtime, but not see old ones.
> 
> `Worker exceeded resource limits` implies we've done something to go over the limit (size, calls?)

I test:
1. if only deal with 10 objects, it works;
2. 50 objects, it doesn't work.

I'm thinking to update an existing feed with new item

2024-03-22 20:05 UTC, WangGithub0 commented
@tarasglek  @humphd  I can successfully share a chat and run this, but can't get result from the link I used (/api/feed/${user}/feed.atom) and the log, could you help me check it or could you help me grant Cloudflare permission， thanks.

2024-03-23 01:06 UTC, humphd commented
Let's debug this together next week some time.  Ping me on Discord and I'll help with logs.

2024-03-23 01:07 UTC, humphd commented
> > I can only stream the logs in realtime, but not see old ones.
> > `Worker exceeded resource limits` implies we've done something to go over the limit (size, calls?)
> 
> I test:
> 
> 1. if only deal with 10 objects, it works;
> 2. 50 objects, it doesn't work.
> 
> I'm thinking to get the existing feed and update with the new item.

A feed is often the last N elements in a list vs. everything, so limiting it is fine.  Likely you need to read the objects in pages vs. trying to get them all at once.  So there are probably a few things we can try.

2024-03-26 13:36 UTC, WangGithub0 commented
> > > I can only stream the logs in realtime, but not see old ones.
> > > `Worker exceeded resource limits` implies we've done something to go over the limit (size, calls?)
> > 
> > 
> > I test:
> > 
> > 1. if only deal with 10 objects, it works;
> > 2. 50 objects, it doesn't work.
> > 
> > I'm thinking to get the existing feed and update with the new item.
> 
> A feed is often the last N elements in a list vs. everything, so limiting it is fine. Likely you need to read the objects in pages vs. trying to get them all at once. So there are probably a few things we can try.

@humphd  how about only showing the latest 20 elements?

2024-03-26 13:39 UTC, humphd commented
> @humphd how about only showing the latest 20 elements?

Let's start with that, yes.

2024-03-26 23:06 UTC, humphd approved these changes
Code looks good!

2024-03-26 23:06 UTC, humphd commented on functions/api/share/[[user_id]].ts
> +  const prefix: string = `${user}/`;
tip: you can always skip defining the type when you are assigning a value, since TypeScript can infer what it is from the value.  It feels weird to do this, but it's the norm to leave as many types out as you can, and only help the compiler when it needs it.

2024-03-26 23:06 UTC, humphd commented on package.json
> +    "cheerio": "1.0.0-rc.12",
Published 2 years ago.  Sure feels like this is dead, doesn't it?  Let's do it for now, but I wonder if there is a more well supported option.

2024-03-27 17:56 UTC, WangGithub0 commented on package.json
> +    "cheerio": "1.0.0-rc.12",
yeah, it was published 2 years ago and hasn't seen updates since that. I'll do it in follow-up https://github.com/tarasglek/chatcraft.org/issues/532

2024-03-29 14:32 UTC, merged