Set init provider for new users to free model, added info alert banner
tarasglek/chatcraft.org pull request #517
Opened 2024-03-21 00:45 UTC by kliu57

- Set initial provider for new users to `FreeModelProvider` (can test by clearing cache)
- Users using `FreeModelProvider` will see alert banner with link to Instructions

Closes #501

### Code changes:

- Had to change `FreeModelProvider` from zero param constructor to having api key param in constructor, so that I could set the currentProvider to `FreeModelProvider` with no key and force the Instructions to appear. When we have an api key in currentProvider the Instructions page will not appear
- Modified `ChatBase.tsx` to add the alert banner for users using `FreeModelProvider` as their currentProvider
- When users click the link in alert banner, the currentProvider is set to a `FreeModelProvider` without a key, forcing Instructions page to show up
- Modified `Instructions.tsx` so that the api key field is not a required field for `FreeModelProvider`

2024-03-21 02:25 UTC, humphd requested changes
Love this!

The new alert banner across the top is 48px high, and our header is 42px.  I wonder if we should make it a bit smaller?  Same with the font size, it seems big.

Make "Click here" the same colour (white) and give it an underline so that it's clear it's a link.

Clicking the "Click here" link while you're already in a chat puts the instructions at the bottom of the chat, and you may not see it.  I wonder how we should deal with that?  We could have it be a link that redirects you to the app with `?show-instructions` on the URL in query string, which could be the trigger for showing this?

When I go to the Instructions, the drop-down for picking a provider shows the Free Model as the selected item, and it wants me to enter an API Key.  This makes it seem like I need to put my API key in for this model, which won't work.  Maybe OpenAI should be the default one we select in the drop-down?

2024-03-21 02:33 UTC, kliu57 commented
> We could have it be a link that redirects you to the app with `?show-instructions` on the URL in query string, which could be the trigger for showing this?

What do you mean by this? How to achieve this? Also, maybe this can be a follow up issue because there are many places where we have to implement this "scroll fix". The chatcraft behaviour has always had this problem when if you already had some chat history and then you remove your key the instructions will show up underneath your chat history.

---

I thought about changing the provider to OpenAI but I didn't know what to do if the user already had an OpenAi key saved. If we load their key then they won't see Instructions. If we do not load their key then it's weird for them to have the empty field to enter their key when they already have a key saved.

2024-03-21 03:04 UTC, kliu57 commented
@humphd I have addressed the following:

> The new alert banner across the top is 48px high, and our header is 42px. I wonder if we should make it a bit smaller? Same with the font size, it seems big.

> Make "Click here" the same colour (white) and give it an underline so that it's clear it's a link.

2024-03-21 04:35 UTC, kliu57 commented
> Clicking the "Click here" link while you're already in a chat puts the instructions at the bottom of the chat

@humphd I have found the fix for this

In `MessagesView.tsx` we have the prevMessages stacked above the instructions as you can see here:

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/53ab0bae-ad43-4511-b55e-ff91a2878f2e)

In {instructions} was have a check that makes the instructions only display when user has no key.

I just added something similar to the {prevMessages} so they only display when user DOES have a key.

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/f8ea2ef0-1110-4a2e-a6e9-63eb33274948)

2024-03-21 04:50 UTC, tarasglek commented
i think the free model message should open options. Showing the old enter a key page is very confusing. I couldnt even figure out how to get out of it

2024-03-21 04:55 UTC, kliu57 commented
> i think the free model message should open options. Showing the old enter a key page is very confusing. I couldnt even figure out how to get out of it

@tarasglek For sure, I can just open the ChatCraft user settings instead of showing the instructions. I think Dave was thinking that the instructions page would provide more details about how to use ChatCraft and what is ChatCraft. Do you and Dave want to discuss more about this before I make the change?

2024-03-21 12:41 UTC, humphd commented
Let's simplify in the name of getting this landed: for now, open the user settings.  Doing proper "instructions" can be a follow-up.

The way we'd do it is to define a new route in `router.ts` that is named something like `/welcome` or something, and it would render the instructions or some other component that explains what ChatCraft is.

Later on, having a proper on-boarding experience seems important.  However, this issue doesn't have to be about that.

2024-03-21 16:25 UTC, Amnish04 approved these changes
@kliu57 The changes are pretty clean. 
I have tested the functionality as well. My only concern was that the banner link should rather lead to the **Instructions** page. But going through conversations, I noticed that we are planning to do it in a follow-up, so should be fine.

2024-03-22 14:56 UTC, humphd approved these changes
This is great, ship it.

2024-03-22 15:01 UTC, merged