Support custom providers
tarasglek/chatcraft.org pull request #530
Opened 2024-03-27 14:33 UTC by kliu57

Work in progress

Still to do:

- Get list of models

2024-03-27 15:44 UTC, kliu57 commented
Notes from team meeting:

- when we create new provider, should validate the key, if not valid don't let it be created
- just show the domin of the api url, when they hover over it show the whole url
- In DEFAULT column show a checkmark icon to specify which is the current provider in use
- To change the current provider, have the user check the checkmark on the left of the row and click "Set as Default" button
- If the user selects more than one provider and tries to set as default show an error message
- If the user selects one or more providers that is our built in providers (ex: OpenAI) and tries to delete them then show an error message

Future PRs:

- Perhaps move this to a new modal

2024-03-30 06:35 UTC, kliu57 commented
@humphd I've completed this. Code could use some refactoring but I've implemented everything. I have a question about models though. I console logged all the models I got when I called queryModels on openAI and I got a list of 28 models. But in chatcraft production we already have displayed only 16 models. What is causing this difference? Are we filtering out the models somewhere, where and why?

2024-03-30 19:10 UTC, mingming-ma commented on src/hooks/use-alert.ts
> +        duration: 1000,
Can we make warning a little bit long?
```suggestion
        duration: 3000,
```

2024-03-30 19:12 UTC, Amnish04 requested changes
@kliu57 This is a great improvement. Just left some comments/suggestions

2024-03-30 19:12 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
> +                              />
Do we really need this in an `InputGroup`?

Maybe we should also have `aria-labels` for all elements?
https://www.accessibility-developer-guide.com/examples/forms/in-tables/#optional-alternative-using-aria

2024-03-30 19:12 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
> +                            </InputGroup>
Same here

2024-03-30 19:12 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
> +                          />
I think this should be an `IconButton`, as using div is not semantically correct.

Also this button is inaccessible with keyboard

2024-03-30 19:15 UTC, kliu57 commented on src/components/SmallRevealablePasswordInput.tsx
> +        </Button>
Hmm.. I personally prefer the show/hide text over this eye. I haven't seen this eye icon used in any other websites to show or hide passwords. Do you have any examples of other websites using an icon instead of text to show or hide password, I would like to see what sort of icon they used.

2024-03-30 19:19 UTC, kliu57 commented on src/hooks/use-alert.ts
> +function trimMessage(message?: string): string {
1. Ok, I will rename it to truncate.
2. I feel like no point making the max characters dynamic since the alert popup toast is not very big to begin with. I just had to truncate the message since I had an error message coming back from openrouter that was like thousands of characters long.
3. Let me ask dave in the next team meeting if we want the alert types not created by me truncated, I'm a bit hesitant to make changes to code that is working.

2024-03-30 19:20 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
I'm not sure. this is the abstract parent class of all the providers. If I change the location, I would have to change all the import paths as well.

@humphd Do we want the location of `ChatCraftProvider.ts` to change?

2024-03-30 19:23 UTC, kliu57 commented on src/components/PreferencesModal.tsx
>                      <Button
So, the title text of "Providers" is inside the FormLabel tag. If you are saying I cannot put Buttons inside FormLabel, then how would I do it? I need the buttons to appear next to the "Providers" text.

2024-03-30 19:25 UTC, kliu57 commented on src/components/PreferencesModal.tsx
>                <FormControl>
Any suggestions for what I should embed the table inside then? I am not familiar with UI coding.

2024-03-30 19:26 UTC, kliu57 commented on src/components/PreferencesModal.tsx
> +                              />
I was trying to follow what the past code of ChatCraft was doing for input field. [Here](https://github.com/tarasglek/chatcraft.org/blob/main/src/components/RevealablePasswordInput.tsx) is the code for the old password field. It had an InputGroup so I followed suit.

2024-03-30 19:27 UTC, Amnish04 commented on src/components/SmallRevealablePasswordInput.tsx
> +        </Button>
1. This is the default way suggested in Angular Material documentation, which I used for my Capstone Project.
https://material.angular.io/components/form-field/examples#form-field-prefix-suffix
<img width="288" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/d4f877a5-2175-4530-82b8-ea004d8dc9d2">
2. Zoom (doesn't allow to paste screenshot)
3. Snapchat

2024-03-30 19:31 UTC, Amnish04 commented on src/lib/ChatCraftProvider.ts
There is an automatic update imports option in VsCode when you do that.

But @humphd can confirm if we need to move, I am not sure either

2024-03-30 19:35 UTC, kliu57 commented on src/components/PreferencesModal.tsx
> +                          />
I cannot switch to using an IconButton while still maintaining the same style. When I switch to IconButton styling gets messed up and the icon looks bad. I will make a follow up issue and either you or me could try to tackle this.

2024-03-30 19:59 UTC, kliu57 commented on src/components/SmallRevealablePasswordInput.tsx
> +        </Button>
Filed this in follow up issue. https://github.com/tarasglek/chatcraft.org/issues/542

2024-03-30 20:01 UTC, kliu57 commented on src/components/PreferencesModal.tsx
> +                          />
Filed the `<IconButton>` thing in https://github.com/tarasglek/chatcraft.org/issues/542.
The accessibility issue is now fixed.

2024-03-30 20:13 UTC, kliu57 commented on src/lib/providers/DefaultProvider/FreeModelProvider.ts
> +  FREEMODELPROVIDER_NAME,
I have moved these variables to their respective provider class files.

2024-03-30 20:14 UTC, kliu57 commented on src/hooks/use-alert.ts
> +        duration: 1000,
I have extended the warning messages to 3000 and the success message to 2000.

2024-03-30 20:23 UTC, kliu57 commented on src/hooks/use-alert.ts
> +function trimMessage(message?: string): string {
Filed number 2 and 3 in the follow up issue https://github.com/tarasglek/chatcraft.org/issues/542

2024-03-30 21:23 UTC, kliu57 commented
@Amnish04 made all the requested changes minus the ones you still need input from dave.

2024-03-30 21:24 UTC, kliu57 commented on src/components/PreferencesModal.tsx
> +                              />
Per our talk I think we can file this in a follow up because if we need to remove the InputGroup for single Input fields, we need to do this throughout Chatcraft

2024-03-30 21:59 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
>                      <Button
You could have it outside the label tag and adjust styling using css (like making display of label to inline)

2024-03-30 22:03 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
>                <FormControl>
I guess it could all be put in a generic box since I think `FormControl` is for **one** control.

Or you could also do it using fieldset like so:
```tsx
<FormControl as={"fieldset"}>
    <FormLabel as={"legend"}>
```

similar to how @mingming-ma  has done his Image Settings for now (he's planning to use an Accordion in follow up)

2024-03-30 22:19 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
> +                          />
@kliu57 I was working on this change and I think I was able to replace with styles preserved. Can I make a PR on this branch?

2024-03-30 22:27 UTC, Amnish04 commented on src/components/SmallRevealablePasswordInput.tsx
I think this component should rather be called `PasswordInput` and you can receive size as an input prop

2024-03-30 22:43 UTC, mingming-ma reviewed
I tested and it handles different situations very well! 

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/c218c512-fe17-4733-933e-422d988fec25)
I think click the `Get key` button to open a new tab is better. Just my thought and could be implemented in the follow up PR.

2024-03-30 22:48 UTC, Amnish04 commented
@kliu57 Another thing I noticed is that when you click on Add Provider and a new form appears

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/9bfff845-3153-4dee-b242-01b18f529d28)

Closing the modal and returning does not make that go away. Maybe you should implement and call a `resetProvidersForm` function when the modal is closed

2024-03-31 17:16 UTC, tarasglek commented
Katie, thank you for working on this. 

Sorry to complain but I find this new ux really confusing. I don't think we need to show all the details when we aren't editing an item. Eg a simple list like

```
- [x]OpenAI
- [x] Provider1 | URL | Key
- [ ] Provider2
```
Might be easier to comprehend..Eg should only show details once we click on a provider.

Here is another example of a similar multi-network concept in crypo-land:
![image](https://github.com/tarasglek/chatcraft.org/assets/857083/87d5cb61-f147-42d9-afdb-4b0948c27482)

2024-03-31 17:22 UTC, humphd commented
This is me telling @kliu57 to do it as a table.  Sorry we didn't have more clarity before you began, Katie.

Is it possible for us to do UI changes in a follow-up so that we can land the rest of the work in here?  As far as I can tell, what you want is cosmetic.

2024-04-01 08:42 UTC, tarasglek commented
Yeah always happy to land and iterate. lgtm for now :)

2024-04-03 15:00 UTC, kliu57 commented on src/lib/ChatCraftProvider.ts
Resolved in meeting, no need to change location of this file

2024-04-03 15:04 UTC, kliu57 commented on src/components/PreferencesModal.tsx
>                <FormControl>
resolved during team meeting

2024-04-03 15:06 UTC, kliu57 commented on src/components/PreferencesModal.tsx
> +                              />
@Amnish04 will make follow up issue for refactoring this throughout ChatCraft

2024-04-03 15:18 UTC, kliu57 commented
> @kliu57 Another thing I noticed is that when you click on Add Provider and a new form appears
> 
> ![image](https://private-user-images.githubusercontent.com/78865303/318230896-9bfff845-3153-4dee-b242-01b18f529d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTYwMzEsIm5iZiI6MTcxMjE1NTczMSwicGF0aCI6Ii83ODg2NTMwMy8zMTgyMzA4OTYtOWJmZmY4NDUtMzE1My00ZGVlLWIyNDItMDFiMThmNTI5ZDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE0NDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMWU0NWVjNDdjZWZkYjQwNDNiMTAwNDQ3NTIxZDRjMDgyY2M4NmYzN2QzZjM0NjNmYWMxZmE2OWIyNTdhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ji2XLgkafEIr3Wtbctbb0DOnQaJHQNTKykjePkQAx0)
> 
> Closing the modal and returning does not make that go away. Maybe you should implement and call a `resetProvidersForm` function when the modal is closed

I will file this as a follow up

2024-04-03 15:30 UTC, kliu57 commented on src/hooks/use-alert.ts
> +function trimMessage(message?: string): string {
Number 2 - discussed during team meeting, no need for this
Number 3 - discussed during team meeting, I will make this change in this PR

2024-04-03 15:30 UTC, kliu57 commented on src/components/PreferencesModal.tsx
>                      <Button
@Amnish04 please make a follow up issue for this

2024-04-03 17:13 UTC, kliu57 commented
@Amnish04 @mingming-ma Please review

Changes made:

- Refactored password component into one -> `PasswordInput.tsx` (Removed `SmallRevealablePasswordInput.tsx` and `RevealablePasswordInput.tsx`)
- If you add a new row for new provider and don't fill it out, when you close the modal and come back you will not see that new row
- all alert toasts are now truncated to 200 chars
- Get key from OpenRouter button renamed to Get OpenRouter key

2024-04-03 17:21 UTC, kliu57 commented on src/components/SmallRevealablePasswordInput.tsx
This is now fixed

2024-04-03 18:10 UTC, Amnish04 commented on src/components/PreferencesModal.tsx
> +                              />
Filed #550

2024-04-03 18:16 UTC, mingming-ma approved these changes
LGTM!

2024-04-03 18:49 UTC, Amnish04 requested changes

2024-04-03 18:49 UTC, Amnish04 commented on src/components/PasswordInput.tsx
> +  size?: "sm" | "md";
[InputProps ](https://chakra-ui.com/docs/components/input/props) already have size, we shouldn't override it.

```suggestion
type PasswordInputProps =InputProps & {
```

Make sure to import InputProps from "@chakra-ui/react"

2024-04-03 18:49 UTC, Amnish04 commented on src/components/PasswordInput.tsx
> +  const buttonSize = size === "sm" ? "xs" : "sm";
You can rather add `hideButtonSize` prop to your props interface

2024-04-03 18:49 UTC, Amnish04 commented on src/components/PasswordInput.tsx
> +  const paddingLeft = size === "sm" ? "0.4rem" : undefined;
Same here, the user of this component can pass these props explicitly and you can pass to Input directly.

2024-04-03 19:35 UTC, kliu57 commented on src/components/PasswordInput.tsx
> +  const inputSize = size === "sm" ? "sm" : "md";
I created a follow up issue that we can use to discuss during next week's meeting.

https://github.com/tarasglek/chatcraft.org/issues/553

2024-04-03 19:54 UTC, Amnish04 approved these changes
Looks good to me!

We can discuss #553 after landing this.

2024-04-03 19:56 UTC, merged