Add the Providers selection Menu Group to easy switch between providers
tarasglek/chatcraft.org pull request #535
Opened 2024-03-27 21:53 UTC by Rachit1313

Closes #510 

Tasks Completed:
- [ ] Enable switching between providers from the ask menu for Desktop Prompt
- [ ] Enable switching between providers from the ask menu for Mobile Prompt
- [ ] Use MenuGroup from Chakra UI to group models and providers distinctly

Files Changed:
PromptForm.tsx

Screenshots:
<img width="809" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/1f4a411b-1876-4df5-8c98-a9daee82bbbe">

2024-03-28 00:30 UTC, humphd commented
We've got the same alignment issue here that you fixed elsewhere.  All of the providers should be indented the same amount (left margin) and the icon only showing beside the selected provider.  It shouldn't indent the text when the checkbox is beside it (e.g., the text should already be at that position).

2024-03-28 02:32 UTC, kliu57 requested changes
Some minor changes requested. Also you have to make the change from settings.provider using the apiUrl as the key to using name as the key once the hotfix #537 is merged, thanks.

2024-03-28 02:32 UTC, kliu57 commented on src/components/PromptForm/PromptSendButton.tsx
> +  const supportedProviders = settings.providers;
You can just use settings.providers directory no need to set it to a variable. We don't want to confused it with supportedProviders which is a different array.

2024-03-28 02:32 UTC, kliu57 commented on src/components/PromptForm/PromptSendButton.tsx
> +                  const newProvider = providerFromJSON({
My hotfix from pr #537 will handle deserializing the provider objects inside settings.providers. So you can directly set the currentProvider to the item in the array. You do not need to call providerFromJSON.

`setSettings({ ...settings, currentProvider: settings.providers[provider.name] });`

I am using provider.name as the key here because **after** the hotfix is merged you will need to use the name as key.

2024-03-28 05:39 UTC, Rachit1313 commented
@kliu57 Do you want me change key based on name now or after the PR has been merged. I believe that it would be better to do it after merge as I would be able to test what I'm implementing. Or maybe.. I get this merged and get a PR ready to fix stuff which could be merged right after your PR.

@humphd, What would be the best approach for this?

Could you please also review the indentation changes based on your feedback?

2024-03-28 05:44 UTC, kliu57 commented
> @kliu57 Do you want me change key based on name now or after the PR has been merged. I believe that it would be better to do it after merge as I would be able to test what I'm implementing. Or maybe.. I get this merged and get a PR ready to fix stuff which could be merged right after your PR.
> 
> @humphd, What would be the best approach for this?
> 
> Could you please also review the indentation changes based on your feedback?

You cannot make the change until after my hotfix is merged.

2024-03-29 03:52 UTC, Rachit1313 commented
> I'm not loving the checkmark icon. I wonder if there is something better, maybe an arrow that points at the one
> 
> Maybe we should use a right-hand pointing chevron? https://react-icons.github.io/react-icons/search/#q=chevron
> 
> Something like:
> 
> <img alt="Screenshot 2024-03-28 at 6 30 56 PM" width="555" src="https://private-user-images.githubusercontent.com/427398/317899487-503f1520-2450-4004-b0a0-37cb7d597a83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMzNDIsIm5iZiI6MTcxMTY4MzA0MiwicGF0aCI6Ii80MjczOTgvMzE3ODk5NDg3LTUwM2YxNTIwLTI0NTAtNDAwNC1iMGEwLTM3Y2I3ZDU5N2E4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMzMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGZmMmQxYWVlZTI3MzM1MTA0MTZkNWE4NWE0MTBlMmU4MjAwNmM4YjQ4NDhjZTRlMzY4YTE5Y2JlZjAyNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZGhiNkK0qKHJsT1mv5oyfr6QLQE1B2nTtjCSugKNlAg">
> Another thing I notice: when you change providers, it closes the menu, which is surprising, since you are probably going to want to pick a model from the new list. Can we make it so that choosing the provider doesn't close the menu?
> 
> <img alt="Screenshot 2024-03-28 at 6 26 44 PM" width="251" src="https://private-user-images.githubusercontent.com/427398/317898974-845f3a98-10a6-4d89-ac0f-926862092be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMzNDIsIm5iZiI6MTcxMTY4MzA0MiwicGF0aCI6Ii80MjczOTgvMzE3ODk4OTc0LTg0NWYzYTk4LTEwYTYtNGQ4OS1hYzBmLTkyNjg2MjA5MmJlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMzMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTE0YmM5MGY0YTU2NTYzMmZiNjU0Y2QzYzc4ZjI0YjVjMmE5Nzk0OGVjMzJjNjEzZWVjNTBmN2YwYTRiMjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KSuSryrN6Mw1P9Bsz-0enYQLSaPLAwi74kG3WQu0Hhw">

I changed the icon based on your feedback but not sure how can we achieve the second thing? I tried. using disclosure but even that didn't work. Maybe it has to close the menu after switching providers because it has to re render the model based on the change.

2024-03-29 15:55 UTC, humphd commented
What if you call `e.preventDefault()` when it's a click on the provider?

2024-03-29 16:02 UTC, Rachit1313 commented
> e.preventDefault()

Nope doesn't work

2024-03-29 16:05 UTC, Rachit1313 commented
> > e.preventDefault()
> 
> Nope doesn't work

I found a solution for keeping it open i.e we can add [closeOnSelect={false} ](https://github.com/chakra-ui/chakra-ui/pull/3762) but the problem is this applies to the whole menu and it wont even close when we select model. Is this something acceptable?

2024-03-30 02:42 UTC, kliu57 approved these changes
Thanks for doing the [refactoring](https://github.com/tarasglek/chatcraft.org/pull/535/commits/2dd9addbb845d2263cf0b25b7a90d6a658ceba2e) I asked for, everything looks good to me.

2024-03-30 23:01 UTC, merged