Show Feed to user
tarasglek/chatcraft.org pull request #546
Opened 2024-04-03 14:29 UTC by WangGithub0

Add feed in 2 places: 
 **1. Add share feed button on header;** 
 
<img width="893" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/94aecace-bce2-4faf-890c-84a9baea8bb2">

 **2. In shareModal**
 
<img width="461" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/fdfdfc88-e9d8-459d-a13d-400607eccda2">

closes #514

2024-04-04 12:37 UTC, humphd commented
@WangGithub0 can you rebase for the fix to Header.tsx?

2024-04-04 15:27 UTC, humphd requested changes

2024-04-04 15:27 UTC, humphd commented on src/components/Header.tsx
> +        title: "Copy Shared Chats Feed URL Successfully",
"Copy" should be "Copied"

2024-04-04 15:27 UTC, humphd commented on src/components/ShareModal.tsx
> +      const baseUrl = url.split("/api/")[0];
This kind of thing worries me (hacking on URLs as strings).  Use `new URL()` and then pull stuff out of the pathname with that.  Same for building new URLs.

2024-04-05 00:04 UTC, Amnish04 commented on src/components/Header.tsx
> +      const UserFeedUrl = `https://chatcraft.org/api/share/${user.username}/feed.atom`;
Not a big issue, but this should be camel cased by convention?

2024-04-05 13:39 UTC, humphd approved these changes

2024-04-05 13:39 UTC, humphd commented on src/components/ShareModal.tsx
> +      const newUserFeedUrl = `${parsedUrl.origin}/api/share/${user.username}/feed.atom`;
This is good.  One other way you can do this is to create a URL for a path given another URL:

```ts
const url = new URL('/some/path', parsedUrl.origin);
```

2024-04-05 17:02 UTC, merged