Updated regex to ignore backslash
tarasglek/chatcraft.org pull request #559
Opened 2024-04-04 01:44 UTC by Rachit1313

Closes #427 

Changes Made:
Updated regex to ignore backslash in github commands.

How to test:
Both the links with backslash at the end or without would recieve diff when a link of github PR is imported using /import command.

2024-04-04 06:01 UTC, kliu57 requested changes
```
Behvaiour is different for /import https://github.com/tarasglek/chatcraft.org/pull/421

Than /import http://github.com/tarasglek/chatcraft.org/pull/421
```

```
Moreover, behaviour is different from production for /import https://github.com/tarasglek/chatcraft.org/pull/421/ and all others

Output stops at line 83
```
![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/fadbbeb5-a36b-47e7-9251-a876a2b2db3d)

2024-04-04 07:41 UTC, kliu57 commented
Cancelling this PR since the change was made in commit https://github.com/tarasglek/chatcraft.org/commit/bcdd39ca56ae7a6b73f1516833f3f1488ed6dbf3

2024-04-04 12:13 UTC, humphd requested changes

2024-04-04 12:13 UTC, humphd commented on functions/lib/rewriters/github-rewriter.ts
> +    if (url.origin === "https://github.com" && /\/(.*)\/blob\/(.*)\/?$/.test(url.pathname)) {
```
# Works
/import https://github.com/tarasglek/chatcraft.org/blob/main/.eslintignore

# Fails
/import https://github.com/tarasglek/chatcraft.org/blob/main/.eslintignore/
```

The latter returns a 400 from the server

2024-04-04 12:13 UTC, humphd commented on functions/lib/rewriters/github-rewriter.ts
> +    if (url.origin === "https://github.com" && /\/(.*)\/pull\/(.*)\/?$/.test(url.pathname)) {
This one seems to work well for me.

2024-04-04 12:13 UTC, humphd commented on functions/lib/rewriters/github-rewriter.ts
> +          /^https:\/\/gist\.github\.com\/([a-zA-Z0-9_-]+)\/([a-f0-9]+)\/?$/,
This is working well for me.

2024-04-05 17:35 UTC, Rachit1313 commented on functions/lib/rewriters/github-rewriter.ts
> +    if (url.origin === "https://github.com" && /\/(.*)\/blob\/(.*)\/?$/.test(url.pathname)) {
I just verified that this is something we have in production as well

2024-04-05 17:47 UTC, humphd commented on functions/lib/rewriters/github-rewriter.ts
> +    if (url.origin === "https://github.com" && /\/(.*)\/blob\/(.*)\/?$/.test(url.pathname)) {
Do you want to fix it while you're working on this or split it off into a future issue?

2024-04-05 18:00 UTC, Rachit1313 commented on functions/lib/rewriters/github-rewriter.ts
> +    if (url.origin === "https://github.com" && /\/(.*)\/blob\/(.*)\/?$/.test(url.pathname)) {
I would like to work on debugging this, but as this PR fixes the problem for PRs and gist, i would like to get this merged and create another issue and PR for that one.

2024-04-05 18:21 UTC, Rachit1313 commented
And for the second part i.e difference between https and http, I believe this is because we are only looking for https in the origin of the URL to confirm if we want to rewrite this with github-rewriters.ts. Everywhere in our code we used https to verify.
<img width="983" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/0116f692-c73d-4933-bf07-dd092add313f">
I am not sure, just guessing, @humphd would be able to answer this.

2024-04-05 19:50 UTC, humphd commented
> @kliu57 , for me both the import command on PR 412 without backslash returns the same number of lines i.e 83 in production as well in my branch preview URL. <img alt="image" width="1427" src="https://private-user-images.githubusercontent.com/58596563/320097204-16e266bb-82ea-4e75-98d3-ec4009a8e674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDY4OTAsIm5iZiI6MTcxMjM0NjU5MCwicGF0aCI6Ii81ODU5NjU2My8zMjAwOTcyMDQtMTZlMjY2YmItODJlYS00ZTc1LTk4ZDMtZWM0MDA5YThlNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE5NDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmFkNDkwMWI2ZGY2MTAwZjdiMDBmZjIxZjQ1MTdmNjQxMmZkZTE4MTI0NmQ1ZjNkZjhlZjExYzIxNjU2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaiuEXtHlBq38G82TZe78iOLePALktkPZ4nuPz3mwa0"> <img alt="image" width="1217" src="https://private-user-images.githubusercontent.com/58596563/320097254-82e8779d-fc62-4c1e-995c-81ebe9848823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDY4OTAsIm5iZiI6MTcxMjM0NjU5MCwicGF0aCI6Ii81ODU5NjU2My8zMjAwOTcyNTQtODJlODc3OWQtZmM2Mi00YzFlLTk5NWMtODFlYmU5ODQ4ODIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE5NDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MmMzZDg0YzRkYzE1NjA3MDM3MzgwMmYwYTJmNmNiOWQ3MjRmOWNjMzEwYWQ4YjNmYTYxOTNhNzc1ZWU1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._8IY0Xt6tzz_oLnuZIGnbuhvhPW3gu9iW6ogBH8dLQw">

this is likely due to it being a diff, with only ~6 lines of context (so it naturally cuts if off), which is normal.

2024-04-05 19:51 UTC, humphd commented
> @kliu57 And for the second part i.e difference between https and http, I believe this is because we are only looking for https in the origin of the URL to confirm if we want to rewrite this with github-rewriters.ts. Everywhere in our code we used https to verify. <img alt="image" width="983" src="https://private-user-images.githubusercontent.com/58596563/320099330-0116f692-c73d-4933-bf07-dd092add313f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDY4OTAsIm5iZiI6MTcxMjM0NjU5MCwicGF0aCI6Ii81ODU5NjU2My8zMjAwOTkzMzAtMDExNmY2OTItYzczZC00OTMzLWJmMDctZGQwOTJhZGQzMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE5NDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzY2QyMGEwY2E1N2RkNDBlNmRiYTdhMDg5MzQ2NTFmYWUzODRlYmJhZDViMWRjNDMxNzBhMmMxNDk1NTZhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dBZOJpHnKBxy0oaqmn4W4qjzktSykFHb4V5IIIFKPiA"> I am not sure, just guessing, @humphd would be able to answer this.

I think requiring HTTPS is fine.

2024-04-05 20:00 UTC, mingming-ma reviewed
Here is comparing results:

| | Prod | This PR |
| ------------- | ------------- | ------|
| import https, has end slash| <img alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/685ceb61-a19f-43c8-b68b-5a467c698925">  | <img alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/23f2cd54-cec7-4da4-a0aa-b0e897ebc0ef">  |
| import https, no end slash  | ![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/42d9ef90-9cb7-4b31-84f7-40f6e431e170)| <img width="911" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/6260e7d8-53f1-4466-9893-0ab6bc48c33d"> |
| import http, has end slash| <img width="683" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/d351b41d-6b5a-4b7b-9b72-7bbfb9960cd5">  |<img width="904" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/183bc9f5-4615-4f75-833d-876f62a0448c">  |
| import http, no  end slash  | ![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/b1aad51f-1b1f-4079-b2de-e5a14dd78622)| <img width="880" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/77c0dc14-2ca2-42a2-8360-86a070699f7f"> |

2024-04-05 21:02 UTC, Rachit1313 commented
I think we're good to land this. I'll fix for 400 error of blob as a separate issue.

2024-04-05 22:44 UTC, rjwignar approved these changes
These changes LGTM.
I think the Blob URL issue can be resolved in a followup.

2024-04-05 22:45 UTC, merged