replaced Show/Hide button with Eye ReactIcons
tarasglek/chatcraft.org pull request #579
Opened 2024-04-10 20:32 UTC by rjwignar

This fixes #552
As a followup to #530,
I replaced the Show/Hide Button with the **IoMdEye**/**IoMdEyeOff** [react icons](https://react-icons.github.io/react-icons/search/#q=eye):
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/9aadaee1-1810-43db-86c7-1af13678833e)

I modelled the behaviour based on what I observed on Facebook Messenger (show 'Eye On' when text is obscured, show 'Eye Off' when text is visible:
![messengerEyeIcons](https://github.com/tarasglek/chatcraft.org/assets/78163326/1b97d4e8-c76e-465a-94f0-4ba5ff06c88f)

2024-04-11 16:27 UTC, Amnish04 requested changes
@rjwignar Looks pretty good. 

I was wondering maybe we should also set a title to this button saying "Show" or "Hide" based on its state.

2024-04-11 16:31 UTC, kliu57 approved these changes
Just tested this. Works great!

2024-04-11 16:46 UTC, Amnish04 commented
And I think we should probably be using an `IconButton` now

```tsx
<IconButton
  variant={"ghost"}
  size={buttonSize}
  icon={show ? <IoMdEyeOff /> : <IoMdEye />}
  onClick={() => setShow(!show)}
  aria-label={show ? "Hide" : "Show"}
  title={show ? "Hide" : "Show"}
/>
```

2024-04-12 04:28 UTC, rjwignar commented
> And I think we should probably be using an `IconButton` now
> 
> ```tsx
> <IconButton
>   variant={"ghost"}
>   size={buttonSize}
>   icon={show ? <IoMdEyeOff /> : <IoMdEye />}
>   onClick={() => setShow(!show)}
>   aria-label={show ? "Hide" : "Show"} // This is not needed if we are providing a title, but the linter screams if we don't have this on an IconButton
>   title={show ? "Hide" : "Show"}
> />
> ```

Thanks for your suggestions, @Amnish04. I recently committed them to this PR. I kept the aria-label for [accessibility reasons](https://v2.chakra-ui.com/docs/components/icon-button#usage).
Please let me know if additional changes are required

2024-04-12 04:35 UTC, Amnish04 approved these changes
@rjwignar Thanks for the changes. Looks good now!

2024-04-12 05:32 UTC, rjwignar commented
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/d57e6369-1af5-4eb9-96a7-dc20b29122e1)

Comparison of final changes pre-rebase and post-rebase (and force-push) here for reference.

2024-04-12 05:32 UTC, merged