Added icon to point towards currently selected model and incremental search
tarasglek/chatcraft.org pull request #600
Opened 2024-04-17 22:37 UTC by Rachit1313

Closes #502

2024-04-17 22:50 UTC, kliu57 requested changes
If you type something in the search field and then erase it with backspace, before you finish erasing it the field will lose focus. Can you do something so it doesn't keep losing focus?

2024-04-17 23:19 UTC, rjwignar commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
Do we also want to change this setting?

2024-04-18 00:15 UTC, Rachit1313 commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
No, Thanks for pointing out. I'll just remove it

2024-04-18 00:35 UTC, rjwignar requested changes
I like these features @Rachit1313.
I like that this shows which model is currently selected, and I like the incremental search too.

I just have the same concern as @kliu57
It seems this bug only occurs after you narrow your possible entries, and then expand the list of possible matches by pressing **Backspace** a few times.

Notice how as I narrow my possible matches by typing out `gpt-4-1106-` the text entry remains in focus, but as soon as I hit **Backspace** until `gpt-4-`, the list of possible matches increases and the text entry loses focus
![600_incrementalSearchBug](https://github.com/tarasglek/chatcraft.org/assets/78163326/c36eb888-e841-49be-b3e5-729fb117c405)

2024-04-18 00:52 UTC, rjwignar commented
@Rachit1313 I found this Stackoverflow post which might be helpful:
https://stackoverflow.com/questions/42573017/in-react-es6-why-does-the-input-field-lose-focus-after-typing-a-character

2024-04-18 01:01 UTC, Rachit1313 commented
> I like these features @Rachit1313. I like that this shows which model is currently selected, and I like the incremental search too.
> 
> I just have the same concern as @kliu57 It seems this bug only occurs after you narrow your possible entries, and then expand the list of possible matches by pressing **Backspace** a few times.
> 
> Notice how as I narrow my possible matches by typing out `gpt-4-1106-` the text entry remains in focus, but as soon as I hit **Backspace** until `gpt-4-`, the list of possible matches increases and the text entry loses focus ![600_incrementalSearchBug](https://private-user-images.githubusercontent.com/78163326/323426475-c36eb888-e841-49be-b3e5-729fb117c405.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA4MjAsIm5iZiI6MTcxMzQwMDUyMCwicGF0aCI6Ii83ODE2MzMyNi8zMjM0MjY0NzUtYzM2ZWI4ODgtZTg0MS00OWJlLWIzZTUtNzI5ZmIxMTdjNDA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODJjZTVjMmMzYTI4MGFkYWZkZWIxMGM5NGM2OTA4NmZkNTkwNWU0NTZjM2Y1MmUxZjlmZDM2MjRlMzhiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMvlJeMqloAVKwWHIffdve9P98pilXDak4l5eYu8JHg) [ ![600_incrementalSearchBug](https://private-user-images.githubusercontent.com/78163326/323426475-c36eb888-e841-49be-b3e5-729fb117c405.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA4MjAsIm5iZiI6MTcxMzQwMDUyMCwicGF0aCI6Ii83ODE2MzMyNi8zMjM0MjY0NzUtYzM2ZWI4ODgtZTg0MS00OWJlLWIzZTUtNzI5ZmIxMTdjNDA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODJjZTVjMmMzYTI4MGFkYWZkZWIxMGM5NGM2OTA4NmZkNTkwNWU0NTZjM2Y1MmUxZjlmZDM2MjRlMzhiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMvlJeMqloAVKwWHIffdve9P98pilXDak4l5eYu8JHg) ](https://private-user-images.githubusercontent.com/78163326/323426475-c36eb888-e841-49be-b3e5-729fb117c405.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA4MjAsIm5iZiI6MTcxMzQwMDUyMCwicGF0aCI6Ii83ODE2MzMyNi8zMjM0MjY0NzUtYzM2ZWI4ODgtZTg0MS00OWJlLWIzZTUtNzI5ZmIxMTdjNDA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODJjZTVjMmMzYTI4MGFkYWZkZWIxMGM5NGM2OTA4NmZkNTkwNWU0NTZjM2Y1MmUxZjlmZDM2MjRlMzhiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMvlJeMqloAVKwWHIffdve9P98pilXDak4l5eYu8JHg) [ ](https://private-user-images.githubusercontent.com/78163326/323426475-c36eb888-e841-49be-b3e5-729fb117c405.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA4MjAsIm5iZiI6MTcxMzQwMDUyMCwicGF0aCI6Ii83ODE2MzMyNi8zMjM0MjY0NzUtYzM2ZWI4ODgtZTg0MS00OWJlLWIzZTUtNzI5ZmIxMTdjNDA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODJjZTVjMmMzYTI4MGFkYWZkZWIxMGM5NGM2OTA4NmZkNTkwNWU0NTZjM2Y1MmUxZjlmZDM2MjRlMzhiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMvlJeMqloAVKwWHIffdve9P98pilXDak4l5eYu8JHg)

Yeah, I see that this behavior is getting caused by re rendering of the Menu when we find more/ less possible matches.

2024-04-18 01:10 UTC, Rachit1313 commented
> @Rachit1313 I found this Stackoverflow post which might be helpful: https://stackoverflow.com/questions/42573017/in-react-es6-why-does-the-input-field-lose-focus-after-typing-a-character

tried many solutions, nothing works for me.
Tried
1. use disclosure method
2. switching the input with ChakraUI's Input
3. autoFocus property
4. useEffect to manually focus after setting inputRef

2024-04-18 01:11 UTC, Rachit1313 commented
@humphd/ @Amnish04 do you know anything that might help here?

2024-04-18 04:51 UTC, tarasglek commented
a) This is so freaking awesome!
b) You want to debounce like elsewhere in code to not search while user is typing..eg give user 100ms or so to finish their text before searching
c) you likely lose focus on backspace likely because react is destroying and re-creating the menu..hacky solution is to do setTimeout, get reference to raw element and focus that when it's recreated...but really talk to chatcraft re your approach nd this problem

2024-04-18 05:36 UTC, kliu57 commented
@Rachit1313 I know you need a bit of help so here is the code to do the useDebounce since I am familiar with it. Already tested on my local so it works.

```
import { useDebounce } from "react-use";

function MobilePromptSendButton({ isLoading }: PromptSendButtonProps) {
  // Do the same here as I did in DesktopPromptSendButton
}

function DesktopPromptSendButton({ isLoading }: PromptSendButtonProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");

  // I used 1000 milliseconds just as a test to make sure it is working. You can change it to 500 or something I think it may be enough time for a user to finish typing, I actually think 100 milliseconds was not enough time but do some tests and see
  useDebounce(
    () => {
      setDebouncedSearchQuery(searchQuery);
    },
    1000,
    [searchQuery]
  );
  
  ...
  // notice I changed searchQuery to debouncedSearchQuery below in the {models... } part
            <input
              type="text"
              placeholder="Search models..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{ margin: "10px", padding: "5px", width: "calc(100% - 20px)" }}
            />
            {models
              .filter((model) => !usingOfficialOpenAI() || model.id.includes("gpt"))
              .filter((model) =>
                model.prettyModel.toLowerCase().includes(debouncedSearchQuery.toLowerCase())
              )
              .map((model) => (
                <MenuItem
                  closeOnSelect={true}
                  key={model.id}
                  onClick={() => setSettings({ ...settings, model })}
                >
                  {settings.model.id === model.id ? (
                    <MdOutlineChevronRight style={{ marginRight: "4px" }} />
                  ) : (
                    <span style={{ width: "24px", display: "inline-block" }} />
                  )}
                  {model.prettyModel}
                </MenuItem>
              ))}
  ...
}
```

More information I uncovered while testing the backspace problem. It is not a backspace problem but a general overall focus problem for the input field. Try clicking on the input search field. It now has focus. Now hover your mouse away from that area and hover on to one of the models. It immediately loses focus. This is the root of the problem. We thought the problem was from the backspace, but actually all the backspace does was change the search query which changed the size of the dropdown, which made your mouse hover over one of the models or hover on something else and the search field lost focus immediately.

I don't know why the search field is losing focus when you hover away, gpt does not seem to know. Maybe look into what code is triggered when you hover over the models? Maybe that code is shifting the focus to something else and thus the focus of the search input field is lost?

2024-04-18 11:14 UTC, tarasglek commented
If the problem is mouseovers, this is probably an artifact of how react-menu works

2024-04-18 18:17 UTC, Rachit1313 commented
> If the problem is mouseovers, this is probably an artifact of how react-menu works

Yeah I see, Even the solution @kliu57 gave it not helping us to solve the problem completely. If its a problem of how ChakraMenu is setup, how do we fix this?

2024-04-18 21:45 UTC, Rachit1313 commented
The above method would help us stay in focus until we fully erase the text we want while backspacing and not remove focus just after a single match found but I believe this still have some issues as it delays the response time if that matters.

2024-04-18 22:21 UTC, humphd commented
I love this, great work @Rachit1313!  I pulled it locally and made some fixes, which you can use:

```diff
diff --git a/src/components/PromptForm/PromptSendButton.tsx b/src/components/PromptForm/PromptSendButton.tsx
index e9ddd5b..2dae5e9 100644
--- a/src/components/PromptForm/PromptSendButton.tsx
+++ b/src/components/PromptForm/PromptSendButton.tsx
@@ -9,8 +9,11 @@ import {
   Tooltip,
   MenuDivider,
   MenuGroup,
+  Input,
+  InputGroup,
+  InputLeftElement,
 } from "@chakra-ui/react";
-import { TbChevronUp, TbSend } from "react-icons/tb";
+import { TbChevronUp, TbSend, TbSearch } from "react-icons/tb";
 import { FreeModelProvider } from "../../lib/providers/DefaultProvider/FreeModelProvider";
 
 import useMobileBreakpoint from "../../hooks/use-mobile-breakpoint";
@@ -18,7 +21,7 @@ import { useSettings } from "../../hooks/use-settings";
 import { useModels } from "../../hooks/use-models";
 import theme from "../../theme";
 import { MdVolumeUp, MdVolumeOff, MdOutlineChevronRight } from "react-icons/md";
-import { useMemo, useState } from "react";
+import { useMemo, useRef, useState, type KeyboardEvent } from "react";
 import useAudioPlayer from "../../hooks/use-audio-player";
 import { usingOfficialOpenAI } from "../../lib/providers";
 import { useDebounce } from "react-use";
@@ -106,7 +109,7 @@ function MobilePromptSendButton({ isLoading }: PromptSendButtonProps) {
         />
         <MenuList maxHeight={"70vh"} overflowY={"auto"} zIndex={theme.zIndices.dropdown}>
           <MenuGroup title="Models">
-            <input
+            <Input
               type="text"
               placeholder="Search models..."
               value={searchQuery}
@@ -165,15 +168,30 @@ function DesktopPromptSendButton({ isLoading }: PromptSendButtonProps) {
   const isTtsSupported = useMemo(() => {
     return !!models.filter((model) => model.id.includes("tts"))?.length;
   }, [models]);
+  const inputRef = useRef<HTMLInputElement>(null);
 
   useDebounce(
     () => {
       setDebouncedSearchQuery(searchQuery);
     },
-    500,
+    250,
     [searchQuery]
   );
 
+  const onStatTyping = (e: KeyboardEvent<HTMLElement>) => {
+    // Check if the inputRef is current and the input is not already focused
+    if (inputRef.current && document.activeElement !== inputRef.current) {
+      // Don't handle the keydown event more than once
+      e.preventDefault();
+      // Make sure we are focused on the input element
+      inputRef.current.focus();
+      // Ignore control keys
+      const char = e.key.length === 1 ? e.key : "";
+      // Set the initial character in the input so we don't lose it
+      setSearchQuery(char);
+    }
+  };
+
   const { clearAudioQueue } = useAudioPlayer();
 
   const providersList = {
@@ -227,15 +245,26 @@ function DesktopPromptSendButton({ isLoading }: PromptSendButtonProps) {
           title="Choose Model"
           icon={<TbChevronUp />}
         />
-        <MenuList maxHeight={"70vh"} overflowY={"auto"} zIndex={theme.zIndices.dropdown}>
+        <MenuList
+          maxHeight={"70vh"}
+          overflowY={"auto"}
+          zIndex={theme.zIndices.dropdown}
+          onKeyDownCapture={onStatTyping}
+        >
           <MenuGroup title="Models">
-            <input
-              type="text"
-              placeholder="Search models..."
-              value={searchQuery}
-              onChange={(e) => setSearchQuery(e.target.value)}
-              style={{ margin: "10px", padding: "5px", width: "calc(100% - 20px)" }}
-            />
+            <InputGroup>
+              <InputLeftElement pointerEvents="none">
+                <TbSearch />
+              </InputLeftElement>
+              <Input
+                ref={inputRef}
+                type="text"
+                variant="ghost"
+                placeholder="Search models..."
+                value={searchQuery}
+                onChange={(e) => setSearchQuery(e.target.value)}
+              />
+            </InputGroup>
             {models
               .filter((model) => !usingOfficialOpenAI() || model.id.includes("gpt"))
               .filter((model) =>
```

The main changes:

- add a key down handler to listen for the user typing, and when they do, add the first character to the input and then let your exiting code take over
- reduce the debounce so updates happen sooner
- use Chakra's controls to make it a bit more integrated

2024-04-19 00:09 UTC, Rachit1313 commented
I believe for mobile, we can have debounce itself of 600 as probably we would want the keyboard to close after the new models come so that we can select another model based on our search

2024-04-19 00:10 UTC, Rachit1313 commented
> I believe for mobile, we can have debounce itself of 600 as probably we would want the keyboard to close after the new models come so that we can select another model based on our search

@humphd / @kliu57 / @tarasglek

2024-04-19 00:26 UTC, humphd commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
I hate how VSCode constantly changes this

2024-04-19 00:26 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");
It seems odd to me to have this twice.  Can we do it with a single state value, and debound the `set*` method once?

2024-04-19 00:26 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");
Same comment here

2024-04-19 00:52 UTC, humphd commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");
If this is too hard to make work now, let's not block on it.  File a follow-up to do a better fix later.

2024-04-19 00:56 UTC, Rachit1313 commented
As discussed with dave, will work on trying to refactor the code to store searchQuery in 1 useState() function in a follow up later as trying to fix that now is causing another bugs.

2024-04-19 00:59 UTC, Rachit1313 commented on src/components/PromptForm/PromptSendButton.tsx
> +  const [debouncedSearchQuery, setDebouncedSearchQuery] = useState("");
Done. #603

2024-04-19 01:38 UTC, rjwignar requested changes
@Rachit1313 The new changes look good.
I kept note of things I think can be improved, probably in followups.
If we can iterate on these in followups I'd love to approve this

2024-04-19 01:38 UTC, rjwignar commented on src/components/PromptForm/PromptSendButton.tsx
I noticed that, while typing in keywords to search, if there's content in the prompt entry and you press Enter, it sends the prompt to the LLM:
![enterDuringSearch](https://github.com/tarasglek/chatcraft.org/assets/78163326/e949a3d4-2480-41e2-abdf-c420ba9f51e5).

I'm not sure if this is the behaviour we want. I'd like to hear more opinions, but if it's something we don't want I think we iterate on this in a follow-up

2024-04-19 01:38 UTC, rjwignar commented on src/components/PromptForm/PromptSendButton.tsx
> +  );
In a similar vein, but I think it's more noticeable:
If you're pressing "backspace" after entering a keyword, and the list re-renders to show more/less matches, the next time you press "backspace" the entire keyword will be cleared:
![backspaceDuringSearch](https://github.com/tarasglek/chatcraft.org/assets/78163326/6e95c8c4-6aff-4e75-9cb9-0e0fa69e41b6)

2024-04-19 01:38 UTC, rjwignar commented on src/components/PromptForm/PromptSendButton.tsx
>                  </MenuItem>
I briefly tested the debounce on mobile (Safari) and noticed the model search feature is a little unwieldy, at least on an iPhone 8.
It's nothing that will block these changes. We can update the mobile version in followup issues if required.

2024-04-19 01:47 UTC, Rachit1313 commented on src/components/PromptForm/PromptSendButton.tsx
I think this is because its triggering the enter of chat message as there's no enter function on the search bar.

2024-04-19 01:49 UTC, Rachit1313 commented on src/components/PromptForm/PromptSendButton.tsx
> +  );
@humphd , The above described unusual behavior is what I mentioned you in the chat that I faced after I made the changes to refactor debounce. The difference is that it is more frequent if we make the changes.

2024-04-19 01:50 UTC, Rachit1313 commented on src/components/PromptForm/PromptSendButton.tsx
>                  </MenuItem>
Could you please detail a bit n this?

2024-04-19 03:29 UTC, kliu57 commented
@rjwignar @Rachit1313 @humphd 
Hey Roy, I found out the root of the problem for your backspace issue. It is not anything to do with backspace.

The issue is still to do with hovering your mouse over one of the models in the models list, however now we do not lose focus, which is good. However we do lose the previous content we typed.

**Steps to reproduce the issue:**

1. Get ready to type a long word for example I will type openchat (open then chat)
2. Type open
3. Wait a second or two so the search results load
4. Hover your mouse over a model
5. Now type chat
6. Your search will be wiped and you will only see chat

It does not matter if you backspaced or you typed a new letter, the previous typed content will be wiped.

@humphd not sure if this is something we can fix? But it does look a lot better than before since we do not lose focus. However the user has to restart typing from scratch if they did not manage to finish typing everything before the useDebounce period. Perhaps we should increase the useDebounce from 250 to something more? If I don't finish typing in under 250 I will need to restart typing from scratch.

2024-04-19 12:29 UTC, humphd requested changes
I played with this some more and I think that we need 2 fixes:

1. Don't erase everything in the search input when starting to type, in case there is already something there
2. When the menu closes, reset the search input

I tried implementing both and it seemed to work well:

```diff
diff --git a/src/components/PromptForm/PromptSendButton.tsx b/src/components/PromptForm/PromptSendButton.tsx
index ee458f5..ab700ec 100644
--- a/src/components/PromptForm/PromptSendButton.tsx
+++ b/src/components/PromptForm/PromptSendButton.tsx
@@ -204,7 +204,7 @@ function DesktopPromptSendButton({ isLoading }: PromptSendButtonProps) {
       // Ignore control keys
       const char = e.key.length === 1 ? e.key : "";
       // Set the initial character in the input so we don't lose it
-      setSearchQuery(char);
+      setSearchQuery(searchQuery + char);
     }
   };

@@ -253,7 +253,12 @@ function DesktopPromptSendButton({ isLoading }: PromptSendButtonProps) {
           </Button>
         </Tooltip>
       )}
-      <Menu placement="top" strategy="fixed" closeOnSelect={false}>
+      <Menu
+        placement="top"
+        strategy="fixed"
+        closeOnSelect={false}
+        onClose={() => setSearchQuery("")}
+      >
         <MenuButton
           as={IconButton}
           size="sm"
```

2024-04-19 15:23 UTC, tarasglek commented
> 2. When the menu closes, reset the search input

I actually really like the behavior of keeping state in there. I put 22B in and was able to just have various mistral finetunes in the list to compare between them.

2024-04-19 17:06 UTC, humphd commented
Let's get this in before we ship 2.0 please.

2024-04-19 17:13 UTC, kliu57 approved these changes
LGTM! Not getting any of the previous issues anymore

2024-04-19 18:44 UTC, rjwignar commented on src/components/PromptForm/PromptSendButton.tsx
Agreed. However, do we want to prevent this from happening if the search bar is open?

2024-04-19 18:50 UTC, rjwignar approved these changes

2024-04-19 18:50 UTC, rjwignar commented
It's perfect. These changes fix all the issues I previously had

2024-04-19 18:58 UTC, humphd approved these changes
@Rachit1313 land this when you're ready

2024-04-19 18:59 UTC, merged