Extend ImportCommand to fetch error messages from CloudFlare Worker error pages
tarasglek/chatcraft.org pull request #618
Opened 2024-04-27 20:53 UTC by rjwignar

This fixes #605

Background
---
Currently, if you use /import with a Youtube video that either has no captions or English subtitles, ChatCraft will throw this Error Toast:

![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/d39a8d78-eadd-406e-824d-1cfe582e6f7f)

This Error Toast isn't very descriptive.

When /import successfully parses YouTube video captions, `res.text()` returns the actual content that populates the Message:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/4bf1eb2f-cdca-4b8b-8654-9b953f1c67e4).

However, if /import (when using [youtube-captions-scraper](https://github.com/algolia/youtube-captions-scraper/tree/master)) fails to do so (either due to [no captions in specified language](https://github.com/algolia/youtube-captions-scraper/blob/394ce9d61d2d2166f92ac394fa678c705e94fac8/src/index.js#L47-L49) or [no captions at all](https://github.com/algolia/youtube-captions-scraper/blob/394ce9d61d2d2166f92ac394fa678c705e94fac8/src/index.js#L30-L32)),
**res.text() returns the HTML of a CloudFlare Worker error page**:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/4ee6082d-e3d3-4eee-b454-1dd0a10a2d84)

We only want the actual error message, found in:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/e94faf3e-0368-4909-9fb6-971d038b5061)

Solution
---

I tried modifying the error handling in [youtube-rewriter.ts](https://github.com/tarasglek/chatcraft.org/blob/main/functions/lib/rewriters/youtube-rewriter.ts) and in [proxy.ts](https://github.com/tarasglek/chatcraft.org/blob/main/functions/api/proxy.ts) (API handler for /import command) so **res.text()** would contain just the error message, but it seems no matter what I did, a bad response would always return HTML in **res.text()**.

Instead, I decided to use [Cheerio](https://github.com/cheeriojs/cheerio) (already installed) to extract the error message from any bad responses that have an HTML type. I kept the old error message in case other error responses don't contain HTML.

The result is that if /import fails on a YouTube video, the user will get a useful Error Toast telling them why:
**No English captions (https://www.youtube.com/watch?v=y6120QOlsfU)**:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/9b7650b9-6d88-4351-bf59-1c121c6078c4)

**No captions at all (https://www.youtube.com/watch?v=TKfS5zVfGBc)**:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/b49709ad-75bc-4d00-a289-b42d8a4fc22a)

2024-04-27 20:58 UTC, humphd requested changes

2024-04-27 20:58 UTC, humphd commented on src/lib/commands/ImportCommand.ts
> +import { load } from "cheerio";
You don't need cheerio in a browser, since you have a full DOM already (these kinds of libraries are for situations where you don't have a full browser).

```TS
// Create a new DOMParser instance
const parser = new DOMParser();

// Parse the HTML string into a Document object
const doc = parser.parseFromString(htmlString, 'text/html');
```

Now you can query that `doc` for whatever you need to find, like a regular HTML page in the DOM.

2024-04-27 21:25 UTC, rjwignar commented on src/lib/commands/ImportCommand.ts
> +import { load } from "cheerio";
Thanks for the suggestion!

I recently updated my PR to use DOMParser instead of cheerio.
I'm also ensuring that extracted error messages are trimmed:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/9e078a04-0afa-451b-abe6-fbfd282541e3)

2024-04-28 14:03 UTC, humphd requested changes

2024-04-28 14:03 UTC, humphd commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
Let's put some more safety around this string access and a fallback error message if it fails:

```ts
// Try to extract CloudFlare error message from HTML
const errorMessage = doc.querySelector(".error-message")?.innerHTML?.trim();
throw new Error(errorMessage ?? `Unable to proxy request for URL: ${res.statusText}`);
```

2024-04-28 14:35 UTC, rjwignar commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
Thanks for this.
I've incorporated this into my code.

I'm still a little concerned about this PR.

I'm only fiddling with the CloudFlare HTML because it's the only way I currently know how to get the error message.
I tried adding error handling for these caption errors to the **getSubtitles** call in [YouTubeRewriter](https://github.com/tarasglek/chatcraft.org/blob/65597c70b3d0e484a4400a0836e39678aff871a3/functions/lib/rewriters/youtube-rewriter.ts#L23-L38) but the API call still returned a CloudFlare error page.

Is there a better way to grab these error messages?

2024-04-28 14:51 UTC, humphd commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
https://github.com/algolia/youtube-captions-scraper/issues/15

2024-04-28 15:41 UTC, rjwignar commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
It's funny. I found this post during my investigation and when I tried it out the errors were still returned in a CloudFlare Worker page, so I dismissed it.
However, that was because I was originally just throwing the caught error

I've given this another look, and I can get the **error message to show up as a ChatCraft message instead of an Error Toast** (changes not yet on this branch):
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/d0030fcf-b77f-4556-9066-741b18aef75f)
using this catch block:
```tsx
    } catch (error) {
      return new Response(error?.message, {
        headers: { "Content-Type": "text/markdown; charset=UTF-8" },
      });
    }
```
We now have a couple options on how to solve #605:
- modify the message in the error toast (current branch)
- put the error messages in a ChatCraft message (handle caught errors in YouTubeRewriter)
- however else we can handle caught errors in YouTubeRewriter

I'm kind of partial to putting the error message in a ChatCraft message, but I'd like another opinion on this.

2024-05-01 21:55 UTC, rjwignar commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
@humphd I submitted a new PR that uses these changes instead of the changes I made to `src/lib/commands/ImportCommand.ts`. Please let me know which solution you prefer.

2024-05-01 21:59 UTC, humphd commented on src/lib/commands/ImportCommand.ts
> +        const errorMessage = doc.getElementsByClassName("error-message")[0].innerHTML.trim();
Let's do the other one.

2024-05-01 22:11 UTC, closed without merging

2024-05-01 22:12 UTC, rjwignar commented
Closing as we're exploring #625 instead