Single source of truth for commands help text
tarasglek/chatcraft.org pull request #644
Opened 2024-06-01 05:13 UTC by Amnish04

I always felt that the way we manage commands help text documentation could be done better.
Currently, every time we add a new command we have to manually go and add the corresponding documentation to the `Help` component, which many new developers might not even know about.

In this PR,
1. I have added a `metaData` property to `ChatCraftCommand` class, that takes a `helpTitle` and `helpDescription` as a markdown string.
2. The `ChatCraftCommandRegistry` now exposes a list of all the supported command objects, that is used to generate the relevant documentation markdown for the commands table (instead of static text)
3. Making the `metaData` a mandatory argument in `ChatCraftCommand` constructor also ensures that if anyone adds a new command in the future, they cannot get away without adding corresponding documentation to it.

I did not file an issue prior to this, as I was just experimenting and it turned out to work well.

2024-06-01 12:18 UTC, humphd requested changes

2024-06-01 12:18 UTC, humphd commented on src/lib/ChatCraftCommand.ts
> +    public metaData: ChatCraftCommandMetaData
Seeing the mixed casing in `metaData` is a bad code smell (e.g., `metadata` vs. `metaData`) and a lot of times you can solve this by simply not using a name.  Here, I'd suggest we add `title` and `description` to the `ChatCraftCommand` instead.

2024-06-01 12:18 UTC, humphd commented on src/lib/ChatCraftCommandRegistry.ts
> +  static getCommandsList() {
```ts
return Array.from(this.commands.values())
```

I'd call this `getCommands()` (drop the `List`).

2024-06-01 23:33 UTC, Amnish04 commented on src/lib/ChatCraftCommandRegistry.ts
> +  static getCommandsList() {
Renamed in the latest commit

2024-06-01 23:36 UTC, Amnish04 commented on src/lib/ChatCraftCommand.ts
> +    public metaData: ChatCraftCommandMetaData
I see. I have replaced metadata object with flattened properties based on your advise. I did not remove the `help` prefix though as I thought only `title` and `description` could be ambiguous.

Please let me know if we need further changes.

2024-06-01 23:45 UTC, Amnish04 commented
@humphd Not sure why, I've started getting a lint error in a file I did not even change.

https://github.com/tarasglek/chatcraft.org/actions/runs/9333938306/job/25691497752?pr=644

2024-06-03 11:02 UTC, tarasglek commented
> @humphd Not sure why, I've started getting a lint error in a file I did not even change.
> 
> https://github.com/tarasglek/chatcraft.org/actions/runs/9333938306/job/25691497752?pr=644
> 
> **Update:** I think its related to @tarasglek's latest commit, and #646 should fix it.

sorry, was distracted and forgot to check on first landing and then forgot to land the fixup

2024-06-03 21:43 UTC, merged