Upgrade Eslint to v9
tarasglek/chatcraft.org pull request #697
Opened 2024-10-07 21:22 UTC by menghif

Fixes #689

This PR upgrades Eslint to v9 and moves to a flat config.

All plugins are now up to date and compatible with the new Eslint flat config. The exception was `eslint-plugin-react-hooks` where I had to use the latest rc version (https://github.com/facebook/react/issues/28313#issuecomment-2363692765).

I started the upgrade process with the [configuration migrator](https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file) and then went through each plugin and used the recommended configuration setup found in the docs (while making sure all the original chatcraft custom configurations are kept).

2024-10-07 21:36 UTC, humphd requested changes
Excellent.  Those `catch(err)` issues could be converted to not require the disable.

2024-10-07 21:36 UTC, humphd commented on src/components/CodeHeader.tsx
>      } catch (err) {
You could change this to `} catch {` if we aren't using it vs. disabling the rule

2024-10-07 21:50 UTC, humphd commented
Cloudflare build fails like so:

```

16:56:24.488 | > chatcraft.org@0.0.0 build /opt/buildhome/repo
-- | --
16:56:24.488 | > tsc && vite build
16:56:24.488 |  
16:56:32.623 | src/components/Sidebar/SidebarDesktop.tsx(1,15): error TS2305: Module '"@chakra-ui/react"' has no exported member 'keyframes'.
16:56:32.658 | ELIFECYCLE  Command failed with exit code 2.
16:56:32.690 | Failed: Error while executing user command. Exited with error code: 2
16:56:32.700 | Failed: build command exited with code: 1
16:56:33.704 | Failed: error occurred while running build command
```

2024-10-08 00:17 UTC, menghif commented
> Cloudflare build fails like so:
> 
> ```
> 
> 16:56:24.488 | > chatcraft.org@0.0.0 build /opt/buildhome/repo
> -- | --
> 16:56:24.488 | > tsc && vite build
> 16:56:24.488 |  
> 16:56:32.623 | src/components/Sidebar/SidebarDesktop.tsx(1,15): error TS2305: Module '"@chakra-ui/react"' has no exported member 'keyframes'.
> 16:56:32.658 | ELIFECYCLE  Command failed with exit code 2.
> 16:56:32.690 | Failed: Error while executing user command. Exited with error code: 2
> 16:56:32.700 | Failed: build command exited with code: 1
> 16:56:33.704 | Failed: error occurred while running build command
> ```

This is because I upgraded `@chakra-ui/react` without noticing. I reverted it now!

2024-10-08 12:04 UTC, humphd approved these changes
Excellent

2024-10-08 12:04 UTC, merged