Added ModelProviderMenu component and reused it in PromptsendButton and MessageBase
tarasglek/chatcraft.org pull request #730
Opened 2024-11-15 19:47 UTC by hpatel292-seneca

This is Requested from  #729

2024-11-16 20:13 UTC, humphd commented
Can we close #729?

2024-11-18 04:50 UTC, Amnish04 requested changes
@hpatel292-seneca I've left some feedback. We need to replace this Menu with our custom implementation that supports SubMenus so you don't have to use an ad-hoc approach.

2024-11-18 04:50 UTC, Amnish04 commented on src/components/Menu/ModelProviderMenu.tsx
> +const ModelProviderMenu: React.FC<ModelProviderMenuProps> = ({
I would name this `ModelSelectionMenu`. @humphd What do you think?

2024-11-18 04:50 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +        borderRightRadius="0"
We shouldn't need this inside a `ButtonGroup`. The problem you're facing is because you have an invalid `div` inside ButtonGroup that breaks the following style:
![image](https://github.com/user-attachments/assets/ed74958b-ab37-445b-87da-0cf94d6d5888)

2024-11-18 04:50 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +        </Box>
```suggestion
          <ModelProviderMenu
            onItemSelect={(modelId) => {
              const model = models.find((m) => m.id === modelId);
              if (model) setSettings({ ...settings, model });
            }}
          />
```

Get rid of this `Box` to solve border issues.

2024-11-18 04:50 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +            borderRightRadius="0"
```suggestion
```

2024-11-18 04:50 UTC, Amnish04 commented on src/components/PromptForm/PromptSendButton.tsx
> +      <Menu placement="top" strategy="absolute" closeOnSelect={false} offset={[-90, 0]}>
Why change this?

2024-11-18 04:50 UTC, Amnish04 commented on src/components/Menu/ModelProviderMenu.tsx
> +const ModelProviderMenu: React.FC<ModelProviderMenuProps> = ({
I would name this `ModelSelectionMenu`. @humphd What do you think?

2024-11-18 12:18 UTC, tarasglek commented
Thanks for moving the pull req over. I agree with Amnish re reusing code more. I suspect that might fix the only bug I found..there on first load if I click retry-with and search for "3b", the menu closes itself....on subsequent uses it seems ok

2024-11-18 15:48 UTC, hpatel292-seneca commented on src/components/PromptForm/PromptSendButton.tsx
> +      <Menu placement="top" strategy="absolute" closeOnSelect={false} offset={[-90, 0]}>
Initially, I changed this because previously I was using `60vh` for `MenuList` and it was overflowing in mobile devices to I tried using `absolute` if that can fix my issue but I didn't so I change the height to `50vh` and it was working fine but I forget to change it back to `fixed`.

2024-11-18 15:50 UTC, hpatel292-seneca commented on src/components/PromptForm/PromptSendButton.tsx
> +        </Box>
Understood.

2024-11-18 17:51 UTC, Amnish04 requested changes
@hpatel292-seneca Just wrote some implementation ideas.

2024-11-18 17:51 UTC, Amnish04 commented on src/components/Menu/ModelProviderMenu.tsx
> +          onMouseLeave={adjustedOpenOnHover ? onClose : undefined} // Close on hover out if openOnHover
We shouldn't need to do this ourselves once we migrate to using React-Menu.

2024-11-18 17:51 UTC, Amnish04 commented on src/components/Menu/ModelProviderMenu.tsx
> +      )}
@hpatel292-seneca Right now, this implementation is too specific to be reused anywhere as you'll have to add another `MenuButton` **inside** the component implementation wherever this needs to be used.

There are 2 ways we can solve this:
1. Either accept a `variant: "menu" | "submenu"` and a `MenuButton` in the props so you can dynamically provide the host element for menu. But this will be too dirty, and not much better than the current approach.
2. I would say a **better way** for this would be to just extract the `MenuList` part as a separate component so you could reuse it anywhere - wrap it in a `Menu` with whatever `MenuButton` or throw it inside a `SubMenu`. The component could be renamed to `ModelSelectionMenuList`. Just make sure you also import the `MenuGroup` from the library we are wrapping, i.e. [@szhsin/react-menu](https://szhsin.github.io/react-menu/docs#menu-group)

@humphd What are your thoughts on this?

2024-11-18 21:16 UTC, humphd commented on src/components/Menu/ModelProviderMenu.tsx
> +      )}
Yeah, your "better way" sounds good

2024-11-19 11:04 UTC, tarasglek commented
> Thanks for moving the pull req over. I agree with Amnish re reusing code more. I suspect that might fix the only bug I found..there on first load if I click retry-with and search for "3b", the menu closes itself....on subsequent uses it seems ok

Sweet, functionality-wise this is perfect!

2024-11-19 12:20 UTC, hpatel292-seneca commented
Thanks @tarasglek, I found few bugs on mobile view while working it. I will open issues for those and if you agree to make those changes, I would to work on those.

2024-11-20 04:33 UTC, Amnish04 approved these changes
@hpatel292-seneca This works well and code looks good to me. Thanks for following up!

2024-11-20 13:11 UTC, humphd commented
@hpatel292-seneca can you "Resolve" the issues above that are now dealt with?  It's hard to follow the current state of this PR otherwise.

Let me know when this is ready to land.

2024-11-20 14:11 UTC, hpatel292-seneca commented
Hi @humphd,

I can send a PR for the above issue if needed. However, if we merge the PR for the above issue first, this PR will likely encounter merge conflicts, as it also modifies the same file. Let me know how you'd like to proceed.

2024-11-20 14:47 UTC, humphd commented
I want to get this merged first then you can improve things in follow-ups.  Please resolve whatever is done above, and file a new issue with the things to be fixed next, then resolve, so we can land this.

2024-11-20 15:00 UTC, hpatel292-seneca commented on src/components/Menu/ModelProviderMenu.tsx
> +} from "@chakra-ui/react";
This is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/8e706c19f003c517e2bcc61b0293f65b449b416d

2024-11-20 15:02 UTC, hpatel292-seneca commented on src/components/Menu/ModelProviderMenu.tsx
> +const ModelProviderMenu: React.FC<ModelProviderMenuProps> = ({
I followed your suggested in below comments and named the new component `[ModelSelectionMenuList]` in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/8e706c19f003c517e2bcc61b0293f65b449b416d

2024-11-20 15:06 UTC, hpatel292-seneca commented on src/components/PromptForm/PromptSendButton.tsx
> +        borderRightRadius="0"
This is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/8e706c19f003c517e2bcc61b0293f65b449b416d

2024-11-20 15:07 UTC, hpatel292-seneca commented on src/components/PromptForm/PromptSendButton.tsx
> +        </Box>
This is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/5a286eb40b8abf796c9e9558a1a20320668ffc0e

2024-11-20 15:09 UTC, hpatel292-seneca commented on src/components/PromptForm/PromptSendButton.tsx
> +            borderRightRadius="0"
It is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/5a286eb40b8abf796c9e9558a1a20320668ffc0e

2024-11-20 15:10 UTC, hpatel292-seneca commented on src/components/Menu/ModelProviderMenu.tsx
> +          onMouseLeave={adjustedOpenOnHover ? onClose : undefined} // Close on hover out if openOnHover
This is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/8e706c19f003c517e2bcc61b0293f65b449b416d

2024-11-20 15:10 UTC, hpatel292-seneca commented on src/components/Menu/ModelProviderMenu.tsx
> +      )}
This is fixed in commit https://github.com/tarasglek/chatcraft.org/pull/730/commits/8e706c19f003c517e2bcc61b0293f65b449b416d

2024-11-20 15:15 UTC, hpatel292-seneca commented
I resolved all 'requested changes.' Sorry, I misinterpreted your message at first.

2024-11-21 01:40 UTC, merged

2024-11-21 10:57 UTC, tarasglek commented
@hpatel292-seneca this is a freaking huge quality of life improvement. Awesome work!

2024-11-21 12:35 UTC, hpatel292-seneca commented
Thanks @tarasglek