changed label to 'LLM Providers'
tarasglek/chatcraft.org pull request #740
Opened 2024-11-17 21:23 UTC by Kannav02

This PR Fixes issue #718 

The Objective of this PR is to achieve the following tasks

- [x] Change the Provider label text from "Providers" to "LLM Providers"
- [ ] Add a new section below "LLM Providers" for "Other AI Providers"
- [ ] Hard-code `jina.ai` as the first and only one we support

2024-11-18 04:05 UTC, Kannav02 commented
Hey

I have tested the changes made over here and I observed the following

- [x] API key was being validated and used for subsequent requests to Jina AI Reader
- [x] Personal Document was being converted to markdown with longer lengths than the free tier of Jina AI

Image of the working solution
![Screenshot 2024-11-17 at 10 40 01 PM](https://github.com/user-attachments/assets/fe95a675-9e01-4568-809b-791378b6c7e7)

2024-11-18 13:13 UTC, humphd requested changes
Can you please fix CI failures before we look at this?

2024-11-18 22:41 UTC, humphd commented on src/lib/ChatCraftProvider.ts
> +  get clientHeaders() {
This is a bit odd, I'd remove it.

2024-11-18 22:41 UTC, humphd commented on src/lib/file.ts
> +import { JinaAiReaderResponse } from "./ai";
This type should live with the `JinaAIProvider`

2024-11-18 22:42 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +  get clientHeaders() {
Because you only call this in on place below, I'm not sure what the value of abstracting it out like this is.  I'd move it inline with it's only use.

2024-11-18 22:43 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +    const headers: HeadersInit = {
Also, if you do this inline below, you avoid having to explicitly do types like this.

2024-11-18 22:43 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +  async validateApiKey(key: string) {
Remove this

2024-11-18 22:44 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +      console.error(`Error converting PDF to markdown`, err);
Add a case for when the error means that we have exceeded the free tier so we can provide a better message.

2024-11-19 02:02 UTC, Kannav02 commented on src/hooks/use-file-import.tsx
> +      (settings.nonLLMProviders["Jina AI"] as JinaAIProvider) || new JinaAIProvider();
I wanted to use the API key if it was available, for that the logic that I thought was, if the user puts in the API key, a new object for the same gets stored in the localStorage for us to operate on, if no API key we just use a throwaway object to do our pdfToMarkdown operation, if I go with the static method approach, I was just a bit skeptical about how it would manage the API key.

2024-11-19 02:04 UTC, Kannav02 commented on src/lib/ChatCraftProvider.ts
> +    this.apiKey = key;
Yes , when i was making the object even I thought so the same, for now I just wanted to separate the parent classes for LLM providers and Non LLM providers , maybe I could resolve all of this in another issue if you want, or maybe even in this one, thank you!

2024-11-19 02:06 UTC, Kannav02 commented on src/lib/ChatCraftProvider.ts
> +  abstract validateApiKey(key: string): Promise<boolean>;
sure, I will look into this

2024-11-20 03:22 UTC, Kannav02 commented
> Question: can we deal with errors from Jina.ai when we try to use the free tier and send a file that's too big, indicating that you can add an API key in Settings to handle this case?

I can definitely look into this, although do you want it to be a part of this PR or should I create another PR and a separate issue for the same

Thank you

2024-11-20 13:08 UTC, humphd commented
The jina.ai error logic could happen in a follow-up, sure.

2024-11-23 01:23 UTC, Kannav02 commented
I believe the code should be good for review now, I have tried to incorporate all of the changes, but if  I have missed out on something, please do let me know and I will work on the same,
thank you!

On another note, I never knew JinaAI was really this good, I put in an 85 pages PowerPoint PDF into the files and it gave me all of it back in markdown format, and all of the content was pretty good, I mean I could abstract all of this logic, create a markdown to pdf pipeline and feed it to any LLM for training, its powerful 

here is the image for the reference 

![Screenshot 2024-11-22 at 8 22 14 PM](https://github.com/user-attachments/assets/20f83a32-f558-4b32-9373-c9c34ec45d66)

2024-11-24 21:40 UTC, humphd requested changes
Looking better, some more feedback.

2024-11-24 21:40 UTC, humphd commented on src/components/Preferences/ModelsSettings.tsx
> +    setNonLLMProviders({
Why are we store the same NonLLM Provider data twice in state?  Can we not use what's in settings only?

2024-11-24 21:40 UTC, humphd commented on src/components/Preferences/ModelsSettings.tsx
> +              LLM Providers
Let's add some helper text below this one too, similar to what you did below:

```tsx
              <FormHelperText fontSize="xs">
                OpenAI-Compatible Chat Completion Providers
              </FormHelperText>
```

2024-11-24 21:40 UTC, humphd commented on src/components/Preferences/ModelsSettings.tsx
> +                  <Td fontSize="xs">Jina AI</Td>
Jina Reader API

2024-11-24 21:40 UTC, humphd commented on src/components/Preferences/ModelsSettings.tsx
> +                      href="https://jina.ai/"
https://jina.ai/reader/

2024-11-24 21:40 UTC, humphd commented on src/hooks/use-file-import.tsx
> +    const contents = await jinaAIProvider.pdfToMarkdown(file);
You can simplify this further:

```ts
const contents = await JinaAIProvider.pdfToMarkdown(file);
```

The `pdfToMarkdown` function can be static and call `JinaAIProvider.fromSettings()` internally.

2024-11-24 21:40 UTC, humphd commented on src/hooks/use-file-import.tsx
> +                title: "Free Tier Limit Exceeded",
This doesn't tell you which free tier you exceeded, can you say "Jina Reader API"?

2024-11-24 21:40 UTC, humphd commented on src/lib/file.ts
> +        const jinaAIProvider = JinaAIProvider.fromSettings();
Same comment here

2024-11-24 21:40 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +  async pdfToMarkdown(file: File): Promise<JinaAiReaderResponse> {
To further explain my comments above, I'd leave this code as is, and add:

```ts
static pdfToMarkdown(file: File): Promise<JinaAiReaderResponse> {
  const jinaProvider = JinaAIProvider.fromSettings();
  return jinaProvider.pdfToMarkdown(file);
}
```

2024-11-24 21:40 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +      const headers = {
Another pattern you can use is to make a new Headers object, then do:

```ts
if(this.apiKey) {
  headers.append("Authorization", `Bearer ${this.apiKey}`);
}
```

Which is a bit easier to read.

2024-11-24 21:40 UTC, humphd commented on src/lib/providers/JinaAIProvider.ts
> +            "Free tier limit exceeded. Please add an API key in Settings to process larger files.",
Jina Reader API free tier limit exceeded...

2024-11-26 00:21 UTC, Kannav02 commented on src/lib/providers/JinaAIProvider.ts
> +      const headers = {
I did try this, and the only issue with this is that typescript gives a compile-time error, stating that `Property 'append' does not exist on type '{ "Content-Type": string; Accept: string; }'.ts(2339)
`, so I thought to avoid this we could use the spread operator, the other option that I have is either declaring the headers as a `Headers` object and then try it out with this pattern

2024-11-26 01:01 UTC, Kannav02 commented
I've implemented the changes based on your feedback. Could you please review and let me know if any further adjustments are needed?

On another note, I have still included the helper text, but as a potential user of the platform, it was looking cluttered, should we do something about it? I still have included a margin at the bottom, but again it just doesn't feel right


![Screenshot 2024-11-25 at 7 01 43 PM](https://github.com/user-attachments/assets/cf556f97-25f0-4439-af8d-39babb79101e)

2024-12-09 15:41 UTC, humphd approved these changes
This is great.  Tested locally, and it's working well.  Thanks for the code simplifications.

Excited to see this get added.

2024-12-09 15:41 UTC, merged