Remove RSS icon from the header.
tarasglek/chatcraft.org pull request #744
Opened 2024-11-19 02:39 UTC by KrinsKumar

This PR address issue - #723.

I have removed the icon and its logic from the header component for now.

I have not yet removed `functions/api/share/[[user_id]].ts` logic which is used to generate the RSS feed. Please let me know if you want this to be removed. 

![image](https://github.com/user-attachments/assets/14a243e4-83cd-4f5c-8144-ef8a2e0d4018)

Thank you.

2024-11-19 13:33 UTC, humphd requested changes
You need to rip out the backend code in functions/ too.  Go look at the PRs that added all this.

2024-11-19 23:17 UTC, humphd requested changes
No, you've removed all the sharing backend logic.  Please only remove the RSS feed code.

2024-11-19 23:47 UTC, KrinsKumar commented
Apologies, I have added the files back and removed the function used to generate the feed. Please let me know if this works. Thank you.

2024-11-21 01:41 UTC, humphd requested changes
Need to fix the lint issues https://github.com/tarasglek/chatcraft.org/actions/runs/11923809412/job/33296868143?pr=744

2024-12-04 01:07 UTC, humphd commented on functions/api/share/[[user_id]].ts
> -import { DOMParser } from "linkedom";
If you're removing these, can you confirm that we still need the dependencies, and if we don't `import` them anywhere else, please remove from `package.json` as well?

2024-12-05 00:42 UTC, KrinsKumar commented on functions/api/share/[[user_id]].ts
> -import { DOMParser } from "linkedom";
I dont see us using DOMparsing from linkedom or feed anywhere else, I have removed them from `package.json`.

2024-12-05 01:26 UTC, humphd approved these changes

2024-12-05 01:26 UTC, merged

2024-12-05 01:26 UTC, humphd commented
Thanks for all the work on this, @KrinsKumar!