Update MessageBase to show date on new line for mobile screens
tarasglek/chatcraft.org pull request #751
Opened 2024-11-21 17:23 UTC by hpatel292-seneca

This Fixes #747 

I added a Flex component around heading and date and set direction of flex to row for sm screens

```py
                 <Flex
                    direction={{ base: "column", sm: "row" }} // Stack on mobile, row on larger screens
                    align={{ base: "flex-start", sm: "center" }} // Align items properly for both views
                    justify="space-between"
                    w="100%"
                    gap={2}
                  >
                    <Heading as="h2" size="xs" minW="fit-content">
                      {heading}
                    </Heading>
                    <Text
                      as="span"
                      fontSize="sm"
                      minW="fit-content"
                      color="gray.500"
                      _dark={{ color: "gray.300" }}
                    >
                      <Link as={ReactRouterLink} to={`/c/${chatId}#${id}`}>
                        {formatDate(date, isNarrowScreen)}
                      </Link>
                    </Text>
                  </Flex>
```

2024-11-21 17:25 UTC, hpatel292-seneca commented
Hi @humphd @tarasglek, Please review the PR and let me know if any changes are required.

2024-11-21 22:23 UTC, humphd requested changes
Nice.  A few things I notice:

## Font Too Large, Vertical Gap Too Large

I think we can reduce the font size of the date, and amount of space between the two stacked divs:

<img width="359" alt="Screenshot 2024-11-21 at 5 20 32 PM" src="https://github.com/user-attachments/assets/f83a9445-6ae1-46c7-8462-f3411e53f030">

# Vertically Centre Star Icon

I wonder if we should vertically centre the star icon on mobile?  It seems to be unaligned with anything now

<img width="355" alt="Screenshot 2024-11-21 at 5 21 04 PM" src="https://github.com/user-attachments/assets/1cef87db-f436-4c23-9774-b2a4155b49ba">

2024-11-22 08:05 UTC, hpatel292-seneca commented
Hi @humphd ,
I made the changes, Please review.

Demo:
![image](https://github.com/user-attachments/assets/f4aaf560-9d27-4850-9461-2101ac796b98)

2024-11-22 12:35 UTC, humphd commented on src/components/Message/MessageBase.tsx
> +                    direction={{ base: "column", sm: "row" }} // Stack on mobile, row on larger screens
nit: prefer putting comments above vs. to the right of content, so lines don't extend horizontally.  Vertical > horizontal.

2024-11-22 12:35 UTC, humphd approved these changes
This is really nice, great work!

2024-11-22 12:35 UTC, merged